### ISSUE TITLE
Documentation for getting single issue wrong

### ISSUE THREAD

**Issue by ZASMan** [octokit/octokit.rb#1007]
<img width="1122" alt="screen shot 2018-04-19 at 5 10 46 pm" src="https://user-images.githubusercontent.com/13513340/39018708-d57b5032-43f4-11e8-9bf8-d9e0252b7aa7.png">

Scratched my head over this one for a minute. In your documentation, you put the example for getting a single issue as `issue_comments` rather than `issue_comment`.

**Comment by ZASMan** [comment]
Absolutely, I’ll get on it ASAP. Is the documentation all part of this repo?

**Comment by tarebyte** [comment]
Sure is!

**Comment by tarebyte** [comment]
Closed by #1008
