### ISSUE TITLE
@client.organization_repositories options not working (as expect?)

### ISSUE THREAD

**Issue by chrisallick** [octokit/octokit.rb#1017]
Hello,
New to the octokit library and am trying to list my organization's private repositories sort by "updated." The "private" option appears to be working, but the sort does not. Maybe I'm mis-interpreting the "updated" option, but my expected result was that it would either be ascending or descending based on last changed?

I think I'm not understanding what "updated" constitutes.

Here is my code:

```
require "rubygems"
require "octokit"
require "json"

client = Octokit::Client.new(:login => "_snip_", :password => "_snip_")

user = client.user
puts user.login

client.auto_paginate = true

client.organization_repositories("DeutschLA", options = {:type => "private", :sort => "updated"}).each do |repo|
	puts repo["updated_at"]
	puts repo["id"]
	puts "______"
end
```

And here is the tail end of my results:

```
______
2018-05-17 01:02:27 UTC
123202617
______
2018-03-06 23:59:24 UTC
124133923
______
2018-03-13 19:49:38 UTC
125092587
______
2018-03-23 00:43:19 UTC
126256668
______
2018-03-28 18:36:25 UTC
127182704
______
2018-04-04 18:17:58 UTC
127455530
______
2018-04-11 17:37:38 UTC
128838312
______
2018-05-02 18:37:30 UTC
131660288
______
2018-05-08 23:04:10 UTC
132674332
______
2018-05-08 23:05:21 UTC
132674416
______
2018-05-08 23:06:31 UTC
132674508
______
2018-05-08 23:30:57 UTC
132676202
______
2018-05-09 22:13:29 UTC
132818029
______
2018-05-14 22:33:36 UTC
133406377
______
```

**Comment by tarebyte** [comment]
Hi @chrisallick 

The endpoint in questions [`/organizations/:organization_id/repos`](https://developer.github.com/v3/repos/#list-organization-repositories) doesn't actually support any kind of `sort` query parameter.

So it's not you, it's the endpoint 😄 

I'm going to close this out, but please feel free to continue asking questions.

Thanks!

**Comment by tarebyte** [comment]
@chrisallick unfortunately you cannot authenticate as an organization.

But if you'd like sorting supported for the organization repos endpoint I'd encourage you to reach out to GitHub Support (support@github.com) with your feature request.

**Comment by jessieay** [comment]
> @chrisallick unfortunately you cannot authenticate as an organization.
> 
> But if you'd like sorting supported for the organization repos endpoint I'd encourage you to reach out to GitHub Support ([support@github.com](mailto:support@github.com)) with your feature request.

[Latest API docs](https://docs.github.com/en/free-pro-team@latest/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-a-user) indicate that there is now support sorting for API requests to "List repositories for a user" for anyone who else who found this issue :)
