### ISSUE TITLE
Octokit protect_branch not setting user / team restriction

### ISSUE THREAD

**Issue by glb** [octokit/octokit.rb#1024]
I'm trying to use `protect_branch` to restrict the users / teams that are allowed to merge the branch, but it seems to be clearing the existing settings rather than updating them.

For example:

```
print gitclient.branch_protection("myteam/example", "master").inspect
```

shows me 

```
{:restrictions=>{... :users=>[], :teams=>[{... :slug=>"pr-approvers" ... }]}}
```

but after calling:

```
print gitclient.protect_branch("myteam/example", "master", {
  required_status_checks: {
    strict: true,
    contexts: ["continuous-integration/jenkins/branch", "continuous-integration/jenkins/pr-merge"],
  },
  enforce_admins: false,
  required_pull_request_reviews: {
    dismiss_stale_reviews: true,
    require_code_owner_reviews: false,
  },
  restrictions: {
    users: [],
    teams: ["pr-approvers"],
  },
}).inspect
```

I see:
```
{... :restrictions=>{... :users=>[], :teams=>[]} ...}
```

and

```
print gitclient.branch_protection("myteam/example", "master").inspect
```

also shows:

```
{... :restrictions=>{... :users=>[], :teams=>[]} ...}
```

I have tried both `myteam/pr-approvers` and `pr-approvers` in the request with the same results.

Have I done something wrong?

_possibly relevant:_ I am using this against GitHub Enterprise, not sure the version, but I'm able to set the team in the web UI.

**Comment by tarebyte** [comment]
@glb after you call `gitclient.protect_branch` you should be able to call `gitclient.last_response` Would you minding pasting the results in here?

Thanks!

**Comment by StanleyShen** [comment]
Is this still an issue? I am using octokit (4.25.0), I am trying to set users in restriction part, and I didn't see it work.

And in last response part, I even didn't see restriction.

```
#<Sawyer::Response: 200 @rels={} @data={:url=>
  "https://api.github.com/repos/test/test/branches/master/protection",
 :required_signatures=>
  {:url=>
    "https://api.github.com/repos/test/test/branches/master/protection/required_signatures",
   :enabled=>false},
 :enforce_admins=>
  {:url=>
    "https://api.github.com/repos/test/test/branches/master/protection/enforce_admins",
   :enabled=>true},
 :required_linear_history=>{:enabled=>false},
 :allow_force_pushes=>{:enabled=>false},
 :allow_deletions=>{:enabled=>false},
 :block_creations=>{:enabled=>false},
 :required_conversation_resolution=>{:enabled=>false}}
```

**Comment by timrogers** [comment]
@StanleyShen Thanks for reaching out on this! Would you be able to share the code you're running to protect the branch? Are you hitting GitHub Enterprise Server or GitHub.com?
