### ISSUE TITLE
Readme does not say if I should require octokit in every rb file or not at all.

### ISSUE THREAD

**Issue by CatGirlsAreLife** [octokit/octokit.rb#1027]
I would like to know because I want to create a simple CI that does something similar to the Python/cpython misc/news entry on pull requests or checking for skip news. I would like it if someone could help me convert their Python made CI to Ruby first so I get the general idea for mine. Also what about spell checking those entries as well? I would like to create another status on the same CI that yes, does spell checking. So for example if I use AppVeyor for c# windows builds on a project, then my CI for news entries and spell checking the news entries added.

And yes I never really used Ruby before, only seen some on Travis and some other places.

**Comment by krisleech** [comment]
You might be better to post on a Ruby forum as your question isn't specific to this library.

**Comment by kytrinyx** [comment]
@CatGirlsAreLife As @krisleech mentioned, your question is not specific to this library, so I'm going to go ahead and close it.

**Comment by CatGirlsAreLife** [comment]
Well I figured out that I do need to require it on every rb file I make.

However now I have to make it like how I explained at https://github.com/github/platform-samples/issues/196
