### ISSUE TITLE
Get repository pulls always returns empty array for `requested_reviewers`

### ISSUE THREAD

**Issue by olingern** [octokit/octokit.rb#1030]
## Issue

For all open PRs, I would like to know the reviewers. Currently, the gem returns `requested_reviewers`; however it's always empty.

[Pull Requests Instance Method](http://octokit.github.io/octokit.rb/Octokit/Client/PullRequests.html#pull_requests-instance_method)
```
  Octokit.pull_requests(my_org/my_repo')
```

Sample return excerpt:
```ruby
 ...
 :assignee=>nil,
 :assignees=>[],
 :requested_reviewers=>[],
 :requested_teams=>[],
 :labels=>[],
 :milestone=>nil,
 ...
```

It's also undocumented in the JSON here:  
https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by abinoda** [comment]
@olingern I believe this is by design. The "list pull requests" response doesn't include certain pull request properties. You have to get them via the [Get a single pull request endpoint](https://developer.github.com/v3/pulls/#get-a-single-pull-request), or use the GraphQL API.

**Comment by olingern** [comment]
@abinoda Also, empty in a single pull request.

If I'm already using the gem, I'd like to not mix GraphQL queries alongside with what the gem is doing.

It looks like I'll need to retrieve reviews per pull request via the [pull request review requests](http://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html#pull_request_review_requests-instance_method).

Either way, an empty array, non-functioning array should not be on the pull request resource. It's confusing.

**Comment by abinoda** [comment]
@olingern That doesn't seem right. I do a lot with reviews and review requests with @pullreminders and the `requested_reviewers` array should not be blank when fetching a single pull request. Would you mind posting a screenshot of the pull request itself to show that it has active review requests?

Also, you should know that once a review is submitted, the review request itself disappears. I've documented a write-up about on this and related UX confusion here: https://github.com/pullreminders/backlog/issues/48

**Comment by olingern** [comment]
This is the response from this method on the gem. Much has been redacted for privacy reasons.

**The PR that exists with a reviewer who has requested changes:**

![image](https://user-images.githubusercontent.com/1470297/42610652-8693a3fa-85cd-11e8-9a61-16c4552613b8.png)

**The response from the Github API for that PR:**
```ruby
{:url=>"/pulls/4447",
 :id=> ,
 :node_id=>"",
 :html_url=>"/pull/4447",
 :diff_url=>"/4447.diff",
 :patch_url=>"/4447.patch",
 :issue_url=>"/issues/4447",
 :number=>4447,
 :state=>"open",
 :locked=>false,
 :title=>"",
 :user=>
  {:login=>"olingern",
   :id=>1470297,
   :node_id=>"MDQ6VXNlcjE0NzAyOTc=",
   :avatar_url=>"https://avatars1.githubusercontent.com/u/1470297?v=4",
   :gravatar_id=>"",
   :url=>"https://api.github.com/users/olingern",
   :html_url=>"https://github.com/olingern",
   :followers_url=>"https://api.github.com/users/olingern/followers",
   :following_url=>
    "https://api.github.com/users/olingern/following{/other_user}",
   :gists_url=>"https://api.github.com/users/olingern/gists{/gist_id}",
   :starred_url=>
    "https://api.github.com/users/olingern/starred{/owner}{/repo}",
   :subscriptions_url=>"https://api.github.com/users/olingern/subscriptions",
   :organizations_url=>"https://api.github.com/users/olingern/orgs",
   :repos_url=>"https://api.github.com/users/olingern/repos",
   :events_url=>"https://api.github.com/users/olingern/events{/privacy}",
   :received_events_url=>
    "https://api.github.com/users/olingern/received_events",
   :type=>"User",
   :site_admin=>false},
 :body=> ""
 :created_at=>2018-07-05 07:30:26 UTC,
 :updated_at=>2018-07-11 10:01:21 UTC,
 :closed_at=>nil,
 :merged_at=>nil,
 :merge_commit_sha=>"",
 :assignee=>nil,
 :assignees=>[],
 :requested_reviewers=>[],
 :requested_teams=>[],
 :labels=>[],
 :milestone=>nil,
 ...
```

**Comment by abinoda** [comment]
@olingern I updated my previous comment a bit with information on this, but what's going on with that PR is that there is no review request. When the red :x: is displayed it means that the requested reviewer left a review (requesting changes) and so the review request is nullified. 

Does that make sense?

**Comment by olingern** [comment]
@abinoda It does make sense. Thanks for your help.

My use case is I would like to remind the person who assigned as a reviewer to a PR via a bot. You're right and I was able to use the `pull_request_reviews` to get `shioyama`'s review.

I guess this is a different issue, but it would be nice to grab reviewers who are in either state ( reviewed / non-reviewed ) in one query. Ideally, it would be on every pull request object. 

Going to close this. Thanks again for the pointers, @abinoda.
