### ISSUE TITLE
auto_paginate does not work for retrieving PR statuses

### ISSUE THREAD

**Issue by johan1252** [octokit/octokit.rb#1031]
If doing client.statuses(repo, sha), then the setting of auto-paginate has no affect.
The api call will always return only one page. There are cases where a PR has many statuses set and can go over the one page limit.

In lib/octokit/client/statuses.rb the following line 16
 ```
 def statuses(repo, sha, options = {})
        get "#{Repository.path repo}/statuses/#{sha}", options
 end
```

Should be changed to use paginate function.

```
 def statuses(repo, sha, options = {})
        paginate "#{Repository.path repo}/statuses/#{sha}", options
 end
```

**Comment by tarebyte** [comment]
@johan1252 the change looks fine to me, mind opening up a pull request?

**Comment by johan1252** [comment]
@tarebyte Yep I'll open one up
