### ISSUE TITLE
Regenerate octokit.rb documentation on octokit.github.io

### ISSUE THREAD

**Issue by milani** [octokit/octokit.rb#1035]
I was searching for user app installation functionality and I could not find it at http://octokit.github.io/octokit.rb/Octokit.html. After digging a little bit, I figured out the document is for an older release (`v4.7.0`). 

So updating the documentation is highly appreciated.

**Comment by tarebyte** [comment]
Done! See https://github.com/octokit/octokit.rb/pull/1059
