### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by abinoda** [octokit/octokit.rb#1036]
@tarebyte Any way you could publish a new release? It looks like this projects on a ~quarterly release cycle but there are some nice updates that would be great to get through a release.

**Comment by kytrinyx** [comment]
@abinoda We can definitely cut a release soon. There's one open issue we'd like to get sorted before we do, but we *think* we're close on that.

**Comment by abinoda** [comment]
@kytrinyx Sounds good! Thanks so much, and sorry to bug.
