### ISSUE TITLE
Can we get a release with #1055 in it, please?

### ISSUE THREAD

**Issue by greysteil** [octokit/octokit.rb#1058]
Hey team,

According to [this changelog entry](https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/) the route that apps hit to authenticate an install will change on 4th September.

Without a release that includes #1055 that means all apps using octokit.rb to access that endpoint will break on 4th September.

Would it be possible to get an octokit.rb release before next week? If not then a bunch of us will need to monkeypatch / switch away from using that method, which seems a shame.

**Comment by tarebyte** [comment]
Done https://github.com/octokit/octokit.rb/releases/tag/v4.11.0

**Comment by greysteil** [comment]
Hero, thanks @tarebyte!
