### ISSUE TITLE
 (Faraday::ConnectionFailed) "execution expired"

### ISSUE THREAD

**Issue by casecamp** [octokit/octokit.rb#1061]
Hi Team,

we were facing the above issue from today morning.
we haven't changed any of the code which was working properly.

```
Ruby Version - ruby 2.3.0p0 (2015-12-25 revision 53290)
Rails -version - Rails 5.0.2
```

My code 

```
client = Octokit::Client.new(:login =>username, :password => password) 
issues = client.list_issues(repo_url, state: 'all', per_page: 100,page: page) 
```

Please help me out in resolving the above.

Thanks

**Comment by tarebyte** [comment]
@casecamp this sounds like an issue with GitHub dotcom rather than the client library. Usually `Faraday::ConnectionFailed` is when something times out on GitHub's side and we don't send back a response.

Mind reaching out to [support](https://github.com/contact)?

Thanks!
