### ISSUE TITLE
Search for multiple labels with octokit.search.issues

### ISSUE THREAD

**Issue by runnerpaul** [octokit/octokit.rb#1072]
I have the below search terms in my `octokit.search.issues` function:

`q: "repo:" + repoOrg + "/" + repoName + " is:issue" + " label:sdk" + " state:open"`

Is it possible to edit this to include multiple labels?

**Comment by tarebyte** [comment]
@runnerpaul I'm not entirely sure, I would direct you to [GitHub Support](https://github.com/contact) as they would be more equipped to help you.

Thanks!
