### ISSUE TITLE
Support for Checks?

### ISSUE THREAD

**Issue by ileitch** [octokit/octokit.rb#1074]
Howdy, just wondering if you're planning on adding for support for Checks? https://developer.github.com/v3/checks/

**Comment by tarebyte** [comment]
Hi @ileitch 

We would love to add it, I just haven't had the time to implement it. PRs welcome and happily reviewed if you'd like to take a shot at it.

**Comment by jondavidjohn** [comment]
Seems like it *is* a gap in functionality, just because it's not going to be implemented immediately it be better left open?

**Comment by kytrinyx** [comment]
@jondavidjohn Thanks! At the moment we've not been keeping open issues for unimplemented endpoints. We've considered writing a script to open issues for all of them, but we've not yet decided if that's where we want to go.

For the moment I think for consistency I'd like to keep this closed, with the understanding that we do welcome PRs for *any* unsupported endpoints, though we don't have issues for each of them.

**Comment by laserlemon** [comment]
I have a solid start on adding this functionality at https://github.com/laserlemon/octokit.rb. Here's the [diff](https://github.com/octokit/octokit.rb/compare/master...laserlemon:checks) thus far. Please feel free to contribute to my branch and I'll open a PR when it's ready. I'm open to implementation feedback from the Octokit folks as well!
