### ISSUE TITLE
difficult to use `list_app_installation_repositories` with topics

### ISSUE THREAD

**Issue by rdunlop** [octokit/octokit.rb#1079]
Perhaps this is supposed to be difficult, because it's still in "preview", but I had to jump through some hoops to get `list_app_installation_repositories` to return the topics I wanted.

According to https://developer.github.com/v3/apps/installations/#list-repositories, it _can_ return 'topics', and according to https://developer.github.com/v3/apps/installations/#installations, we need to specify the `application/vnd.github.mercy-preview+json ` accept header in order to get those `topics`.

My confusion is that I had to do the following in order to get it to work:
```
    accept = [
      ::Octokit::Preview::PREVIEW_TYPES[:topics], # need this one to return the topics list
      ::Octokit::Preview::PREVIEW_TYPES[:integrations] # need this one to get at /installations/repositories
    ]
    client.list_app_installation_repositories(accept: accept)
```

I would not have expected that I would need to specify the `::Octokit::Preview::PREVIEW_TYPES[:integrations]` accept header, since it's implied by the fact that I'm calling `list_app_installation_repositories` (which requires that I have that header).

but, `ensure_api_media_type` doesn't actually **ensure** that media type, if given a hash which includes another `accept` header. And, since I need to have 2 different accept headers specified, that causes me some confusion. (ref: https://github.com/octokit/octokit.rb/blob/master/lib/octokit/preview.rb#L25)

I am opening this Issue because I would like to hear whether having 2 different accept-headers is the right way to do this, and whether there is an improvement which can be made to this API to make it easier to use.

**Comment by nickfloyd** [comment]
Hey, thanks for the effort here. Given that this issue has been around for a while and many changes have been added since this was first introduced, I am going to close this issue and mark it as stale. If you feel strongly about this needing to be implemented please feel free to reopen and make the changes stated above and we’ll do what we can to get it merged in. Thanks again!
