### ISSUE TITLE
Integration must generate a public key

### ISSUE THREAD

**Issue by jqtruong** [octokit/octokit.rb#1080]
Hello, i'm getting an error:

    POST https://api.github.com/installations/4/access_tokens: 401 - Integration must generate a public key // See: https://developer.github.com/v3:

i am following this [guide](https://developer.github.com/enterprise/2.13/apps/building-your-first-github-app/), and the error stems from this function call:

    installation_token = @client.create_app_installation_access_token(installation_id)[:token]

in the `authenticate_installation`. 

Do you know why that might be happening?

**Comment by tarebyte** [comment]
@jqtruong can you show me how you're create the `@client` ?

**Comment by jqtruong** [comment]
@client ||= Octokit::Client.new(bearer_token: jwt)

i think i'm missing something, the `:integrations`, right? i am currently looking into how i can add that media type

**Comment by tarebyte** [comment]
The media type is built into the helper methods, how are you creating the `jwt`

**Comment by jqtruong** [comment]
``` ruby
    payload = {
        # The time that this JWT was issued, _i.e._ now.
        iat: Time.now.to_i,

        # How long is the JWT good for (in seconds)?
        # Let's say it can be used for 10 minutes before it needs to be refreshed.
        # TODO we don't actually cache this token, we regenerate a new one every time!
        exp: Time.now.to_i + (10 * 60),

        # Your GitHub App's identifier number, so GitHub knows who issued the JWT, and know what permissions
        # this token has.
        iss: APP_IDENTIFIER
    }

    # Cryptographically sign the JWT
    jwt = JWT.encode(payload, PRIVATE_KEY, 'RS256')
```

where PRIVATE_KEY is set by
```ruby
    PRIVATE_KEY = OpenSSL::PKey::RSA.new(ENV['GITHUB_PRIVATE_KEY'].gsub('\n', "\n")) # convert newlines
```

**Comment by tarebyte** [comment]
@jqtruong out of curiosity, why are you converting the newlines?

**Comment by jqtruong** [comment]
:) i'm just following orders... i mean instructions steps from the guide in this [section](https://developer.github.com/enterprise/2.13/apps/building-your-first-github-app/#prepare-the-runtime-environment).

**Comment by jqtruong** [comment]
oh i guess it is useless in this code since it's already been converted in the environment variable.

**Comment by jqtruong** [comment]
actually, nvm, that is needed because of the step in the guide. step replaces `\n` with the literal characters, and the code reverses that change, for a reason i do not quite understand at the moment. either way, the original issue still happens.

do you have any new thoughts that might help me? i'm willing to try anything at this point...

**Comment by jqtruong** [comment]
closing, user error. i needed to specify the `api_endpoint` to my company's GHE... (facepalm)

**Comment by jakyns** [comment]
@jqtruong I have found this issue right now, could you explain how you add `api_endpoint`? 😅

**Comment by ctran** [comment]
> @jqtruong I have found this issue right now, could you explain how you add `api_endpoint`? 😅

Octokit.configure do |c|
  c.api_endpoint = "https://<hostname>/api/v3/"
end
