### ISSUE TITLE
Octokit crashing in console.

### ISSUE THREAD

**Issue by jeanm182** [octokit/octokit.rb#1087]
I'm having this issue when trying to use the octokit instance methods, whenever  I put my creds on rails console and try to use them on my rails console, it crashes with the following error 
`$ client.repos
objc[58433]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[58433]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.`

Currently using : 
Rails 5.2.1
ruby 2.4.1
gem 'octokit', '~> 4.0'

**Comment by NedHenry** [comment]
I have the same issue, and it seems to be related to how OS Mojave (the new Mac OS). Apparently a change in how it handles forks is causing a bunch of bugs in ruby code. I haven't found a workaround yet that works for me, but I have confirmed that the problem doesn't occur when running the same project on OS High Sierra or on linux.

**Comment by spikex** [comment]
This is a Ruby 2.4.x/Mojave issue. Upgrading to 2.4.4 or greater should fix it.
