### ISSUE TITLE
Initialize ignores falsy values

### ISSUE THREAD

**Issue by nickstanish** [octokit/octokit.rb#1088]
https://github.com/octokit/octokit.rb/blob/737748e4e5f2de23e7744b5e9c1ec57133d6ebad/lib/octokit/client.rb#L122

If a value is set to `false` then initialize will fallback to the default configuration for that key. In most cases this shouldn't matter because nothing is set, but it will likely lead to future bugs.

For example, initializing with `{ :auto_paginate => false }` would set `nil` rather than `false`.

**Comment by tarebyte** [comment]
Yeah I think that's a reasonable expectation, mind opening a pull request?
