### ISSUE TITLE
client.create_issue throws a 404

### ISSUE THREAD

**Issue by iandouglas** [octokit/octokit.rb#1093]
I'm using a personal access token (I didn't select any options when generating it) and I log in through Octokit just fine and can get a repo's issues and repo_obj populates with a Repository object. But I'm unable to create new issues on a repo my user owns (or any other I've tested).

```ruby
  issues = client.issues(repo)
  repo_obj = client.repository(repo)

  # then trying to do one or the other of these:
  client.create_issue(repo, 'issue with repo string')
  client.create_issue(repo_obj.id, 'issue with repo obj.id')
```

I get this output when using the repo string of "username/repo-name"

```
/path/to/gems/2.4.0/gems/octokit-4.13.0/lib/octokit/response/raise_error.rb:16:in 
`on_complete': POST https://api.github.com/repos/iandouglas/REPO-NAME/issues: 
404 - Not Found // See: https://developer.github.com/v3/issues/#create-an-issue 
(Octokit::NotFound)
```

When I use the Repository object's ID instead, I get this output:

```
/path/to/2.4.0/gems/octokit-4.13.0/lib/octokit/response/raise_error.rb:16:in 
`on_complete': POST https://api.github.com/repositories/123456789/issues: 
404 - Not Found // See: https://developer.github.com/v3/issues/#create-an-issue 
(Octokit::NotFound)
```

(I replaced REPO-NAME and an id of 123456789 since it's a private repo, but I've also tried public repos too and get the same 404 error)

I notice the API URI path is different whether I'm using a string of a repo ("/repos/username/repo-name/issues" vs "/repositories/12345/issues")

Thanks for any ideas.

**Comment by tarebyte** [comment]
@iandouglas I would look at the token you are using to make that request.

Does it have the `public_repo` or `repo` scope?

**Comment by iandouglas** [comment]
@tarebyte I had no options chosen. I've updated it for public repos. Will this allow me to inject issues into any public repo, or only those where I am a collaborator or owner?

Background: I teach software development at turing.io and we want to inject 70-80 GitHub issues to repos owned by our students for an upcoming project to save them the time of building their own GitHug issues. If they have to add me as a collaborator that's fine.

**Comment by tarebyte** [comment]
> Will this allow me to inject issues into any public repo, or only those where I am a collaborator or owner?

It will allow you to open issues on any repo that is public.

**Comment by iandouglas** [comment]
Awesome, apologies for the noise then, I couldn't find which permissions were needed to use the issues creation. It works fine. Thanks for pointing me in the right direction!
