### ISSUE TITLE
status.github.com is deprecated

### ISSUE THREAD

**Issue by ahayworth** [octokit/octokit.rb#1107]
As noted in [this blog post](https://github.blog/2018-12-11-introducing-the-new-github-status-site/) dated 2018-12-11, the old github status site ([status.github.com](https://status.github.com)) is deprecated. It has been replaced with a new site located at [www.githubstatus.com](www.githubstatus.com).

It looks like octokit directly calls out to the old api: https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/service_status.rb#L11

As of 2019-03-04, the old API will be disabled entirely: https://twitter.com/githubstatus/status/1098992086970454016

octokit should be updated to use the api from the new status page, which is documented [here](https://www.githubstatus.com/api) if this functionality is still desired.

**Comment by stantona** [comment]
*NB*: The API will be disabled on 4th March which is, at this time, 4 days away.
