### ISSUE TITLE
List of tags for a repo?

### ISSUE THREAD

**Issue by lawrence-berry** [octokit/octokit.rb#1110]
Is there any way to get a list of tags for a repository? I was trying 
`my_repo.rels[:git_tags].get`

but that gives `Octokit::NotFound: GET https://api.github.com/repos/myorg/my_repo/git/tags` and struggling to find it referenced in the V3 docs.

**Comment by tarebyte** [comment]
@lawrence-berry the docs you are looking for would be https://developer.github.com/v3/repos/#list-tags

You could do something as easy as:

```ruby
client = Octokit::Client.new(access_token: <YOUR_GITHUB_TOKEN>)
client.tags("myorg/my_repo")
```

**Comment by lawrence-berry** [comment]
Ah, that's great - thanks for the prompt response!
