### ISSUE TITLE
Find a substitute for sawyer in this gem or find a maintainer for it

### ISSUE THREAD

**Issue by rafaelfranca** [octokit/octokit.rb#1116]
Sawyer is currently unmaintained and this is already causing issues in applications given new versions of adressable can't be used because sawyer is restricting its version. https://github.com/lostisland/sawyer/issues/59

Because of that, applications that uses octokit can't upgrade adressable without having to either find a replacement for octokit or forking octokit to find a replacement for sawyer.

**Comment by tarebyte** [comment]
Thanks for opening this @rafaelfranca, everyone I know who has access is probably not interested in working on it anymore.

I'm gonna start experimenting with some alternative wrappers.

**Comment by jpittis** [comment]
Is there a specific feature of Addressable that is required which is not supported by the stdlib?
I thought that used to be the case but may no longer be the case.

**Comment by rhymes** [comment]
@tarebyte what if you use Faraday directly?

**Comment by tarebyte** [comment]
@rhymes definitely a possibility, we could just implement our own `Octokit::Object` and use that instead of `Sawyer` object.

**Comment by lparry** [comment]
If you're replacing Sawyer, can you please use something that doesn't break basic hash expectations? (or at least maybe doesn't `#inspect` giving the illusion of being a hash)

ie. `thing_that_appears_to_be_a_hash.fetch("key_that_I_am_asserting_is_present")` should not just go and return nil (since "fetch" isn't a key on the response)

**Comment by tarebyte** [comment]
Sawyer is getting it's `Addressable` dependency relaxed!

https://github.com/lostisland/sawyer/pull/61

**Comment by ashmaroli** [comment]
A new version of `sawyer` has been shipped with relaxed version constraints on Addressable and Faraday:
https://rubygems.org/gems/sawyer/versions/0.8.2
