### ISSUE TITLE
Preview code references wrong accept header for branch protection

### ISSUE THREAD

**Issue by snowe2010** [octokit/octokit.rb#1126]
https://github.com/octokit/octokit.rb/blob/9bc8cd25c335cadbc898e11976a32aa8ce77ec8c/lib/octokit/preview.rb#L7 is referencing the wrong `Accept` header for `:branch_protection`

**Comment by tarebyte** [comment]
@snowe2010 there are a few different preview headers for that API, which one do you think is correct in this case?

**Comment by snowe2010** [comment]
Hitting that api with loki fails to work for me, only if I use the luke cage header does updating branch protection work. `application/vnd.github.luke-cage-preview+json`

**Comment by spikex** [comment]
@snowe2010 Based on your other open issues, I presume you are passing in `required_approving_review_count` as part of `required_pull_request_reviews`? It looks like that's the feature that requires a bump from _loki_ to _luke-cage_. Give that it's over a year old, we should probably make the change.

https://developer.github.com/changes/2018-03-16-protected-branches-required-approving-reviews/

**Comment by snowe2010** [comment]
@spikex 	yes I was passing that in.

**Comment by hmharvey** [comment]
Fixed in #1132
