### ISSUE TITLE
Offer lazy pagination

### ISSUE THREAD

**Issue by afeld** [octokit/octokit.rb#1145]
Currently, the only options for pagination are [manual](http://octokit.github.io/octokit.rb/#Pagination) and [`auto`](http://octokit.github.io/octokit.rb/#Auto_Pagination), the latter of which will "fetch and concatenate the results from every page into a single array" up front. This means that users may be fetching a lot more results than they need to much faster than they may need to, and may hit their rate limit as a result. Could Octokit offer an [`Enumerable::Lazy`](https://ruby-doc.org/core-2.6.3/Enumerator/Lazy.html) interface for pagination, akin to [Octokit REST.js's iterator support](https://octokit.github.io/rest.js/#pagination)?

**Comment by nickfloyd** [comment]
Related: https://github.com/octokit/octokit.rb/issues/1273
