### ISSUE TITLE
Mobile Web dropdown Menu placement

### ISSUE THREAD

**Issue by ccppoo** [octokit/octokit.rb#1146]
![Screenshot_20190822-171619_Samsung Internet](https://user-images.githubusercontent.com/46418312/63498441-de31fa80-c500-11e9-90fa-7c0660f7cbe0.jpg)

link : https://developer.github.com/v3/

using in Galaxy s9+, Samsung default internet App

Sorry I didn't follow issue template while submitting this on modile

As you see the screen shot, I can't see left side of dropdown menu. Even zoom out isn't allowed

**Comment by tarebyte** [comment]
Hi @ccppoo this repo is actually for the Octokit Ruby Gem.

This would be an issue you would want to reach out to [GitHub Support](https://github.com/site/report-bug) for.

Thanks!
