### ISSUE TITLE
Get issue and issue comments in one request

### ISSUE THREAD

**Issue by norinux** [octokit/octokit.rb#1148]
I want to get issue comments in issue lists.
Usecase is backup of repository data.

Becouse , list_issues method is not include issue comments.
So , It requires a lot of work to get of issue_comments.

### feature request
add include **comments** option in list_issues method.
or. add new method list_issues_with_comments.

**Comment by tarebyte** [comment]
@norinux this isn't really a limitation with the Octokit client so much as a limitation with the REST API.

If you want to list issues with their comments I would recommend looking at [GraphQL AP](https://developer.github.com/v4/). In GraphQL you can list a repositories issues and then get a set of comments.

**Comment by norinux** [comment]
@tarebyte
I see , I'll try to GraphQL API .
Thank you for your comment !
