### ISSUE TITLE
Missing update_pull_request_review

### ISSUE THREAD

**Issue by eric-silverman** [octokit/octokit.rb#1150]
There doesn't seem to be a method for [Update pull request review](https://developer.github.com/v3/pulls/reviews/#update-a-pull-request-review
)

**Comment by tarebyte** [comment]
Doesn't look like it! Happy to review a PR if you're willing to submit it @eric-silverman

**Comment by eric-silverman** [comment]
@tarebyte  https://github.com/octokit/octokit.rb/pull/1151
