### ISSUE TITLE
Faraday 0.16.0 release breaking Octokit

### ISSUE THREAD

**Issue by stuyam** [octokit/octokit.rb#1155]
I'm getting this error: 
```
/usr/local/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError (NameError)
Did you mean?  Faraday::ClientError
```

It looks like a new version of Faraday just came out 2 hours ago and it is breaking one of the dependencies you use. https://github.com/lostisland/faraday/releases/tag/v0.16.0

May have to lock the version number or something.

**Comment by stuyam** [comment]
Hopefully this PR will fix this and make it backwards compatible: https://github.com/lostisland/faraday/pull/1030

**Comment by stuyam** [comment]
Looks like there is an open PR here too: #1154

**Comment by hmharvey** [comment]
#1154 was merged and a [new release](https://github.com/octokit/octokit.rb/releases/tag/v4.15.0) with the fix has been released so closing this out ✨
