### ISSUE TITLE
list-tags API

### ISSUE THREAD

**Issue by yfll** [octokit/octokit.rb#1168]
Two questions:

1. What's the order of the tags returned? thought it was reverse lexicographical order but this [example](https://api.github.com/repos/yfll/tag-api/tags) proves me wrong . 
2. What options can we pass to limit the number of tags being returned? I was unable to find such information from this [reference](https://developer.github.com/v3/repos/#list-tags).

**Comment by tarebyte** [comment]
@yfll we don't have any kind of special ordering in Octokit, can you reach out to support@github.com?

Thanks!
