### ISSUE TITLE
Faraday deprecation notice

### ISSUE THREAD

**Issue by orien** [octokit/octokit.rb#1170]
When collaborating with Faraday version 0.17.1 a deprecation notice is printed to STDERR:

```
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
```

**Comment by orien** [comment]
I see this has been resolved in #1154. Any chance of a release?

**Comment by cetinajero** [comment]
Hi @orien,

The `faraday` theme had released [v0.17.3](https://github.com/lostisland/faraday/releases/tag/v0.17.3) which by default doesn't show those warnings (requires a `FARADAY_DEPRECATE=warn` env variable to show them).

More on that here: https://github.com/lostisland/faraday/pull/1098

Maybe this version will help you.

**Comment by hmharvey** [comment]
A new release has now been cut, [v4.15.0](https://github.com/octokit/octokit.rb/releases/tag/v4.15.0). See [#1177 (comment)](https://github.com/octokit/octokit.rb/issues/1177#issuecomment-570311185). ✨

**Comment by orien** [comment]
Thanks!
