### ISSUE TITLE
Announced deprecated APIs still in use

### ISSUE THREAD

**Issue by augustocravosilva** [octokit/octokit.rb#1174]
Github has announced some deprecations here
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#deprecating-and-adding-endpoints-for-the-oauth-authorizations-and-oauth-applications-apis

But octokit.rb seems to still be using the deprecated methods.
For example, https://github.com/octokit/octokit.rb/blob/a0ecb99860238cb3c3e79d851440f991f02116eb/lib/octokit/client/authorizations.rb#L154-L161

Should be replaced by `POST /applications/:client_id/token`

**Comment by donalod** [comment]
Howdy, got another email about this today from Github and as far as I can tell, am not using any explicit queries, so it's just the underlying code above? [https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/)

**Comment by tarebyte** [comment]
No you’re right it’s the underlying code, I think we forgot about the new endpoints before shipping the last release.

I’ll take a look and see which ones need updating.

**Comment by MGudgin** [comment]
@tarebyte I've submitted a [PR](https://github.com/octokit/octokit.net/pull/2116) to update octokit.net.

**Comment by tarebyte** [comment]
I appreciate the effort ✨ unfortunately I don't know C# very well to review it 😅 

I'll leave that up to the maintainers of the repo. I only support the Ruby version.

**Comment by tarebyte** [comment]
Closed by https://github.com/octokit/octokit.rb/pull/1203, will report back when we cut a release.
