### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by plutino** [octokit/octokit.rb#1177]
Last release was 9 months ago in March, and there are lots of valuable fixes in current master.  Especially https://github.com/octokit/octokit.rb/pull/1154 fixes a very annoying deprecation message from upstream Faraday change.  

Please create a new release to allow easy access to these fixes and new features.

**Comment by jdeluyck** [comment]
Version 1.0.0 of Faraday has been released, which breaks with the latest version of Octokit. Please release a new version!

**Comment by Atem18** [comment]
Can confirm, can’t build anymore my Jekyll website. :(

**Comment by parkr** [comment]
Hi @hmharvey! Are you able to cut releases of this gem? Thanks!

**Comment by hmharvey** [comment]
Hello all 👋yes, we'll have a release out early next week when we're back from the holidays.

**Comment by akhilles** [comment]
`octokit` gem is completely broken atm due to the `faraday` 1.0.0 release. would it be possible to use some sort of semantic versioning in the `gemspec` to avoid situations like this in the future? This needs to be stricter: `spec.add_dependency 'faraday', '>= 0.9'`

```
Traceback (most recent call last):
	2: from ...
	1: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- octokit (LoadError)
	12: from ...
	11: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	10: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	 9: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	 8: from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit.rb:4:in `<top (required)>'
	 7: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `<top (required)>'
	 4: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
	 1: from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
/var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError (NameError)
```

**Comment by akhilles** [comment]
Temporary workaround for people running into the same issue:
```
gem install specific_install
gem specific_install -l https://github.com/octokit/octokit.rb.git
```
or if using `Gemfile`:
```
gem 'octokit', :git => 'https://github.com/octokit/octokit.rb.git'
```

**Comment by tarebyte** [comment]
I've released https://github.com/octokit/octokit.rb/releases/tag/v4.15.0 which is now live on Rubygems.

Shout out to @hmharvey for putting in the time to write the release notes ✨ 

Happy New year y'all

**Comment by parkr** [comment]
Thank you, @tarebyte and @hmharvey!

**Comment by Atem18** [comment]
Thanks a lot !
