### ISSUE TITLE
Release formatting issues

### ISSUE THREAD

**Issue by olivierlacan** [octokit/octokit.rb#1181]
FYI the release formatting for https://github.com/octokit/octokit.rb/releases/tag/v4.15.0 needs to have dashes or stars at the beginning of each line or Markdown parsing will treat anything no split by a new paragraph as a single line.

See this Dependabot preview: 
![image](https://user-images.githubusercontent.com/65950/72114514-c8876b00-3311-11ea-941d-37b29f6a7faf.png)

I know the GitHub Releases page respects line breaks but not all tools using the release or tag message will do that.

Plus historically you've used lists in previous release notes so it'd be good to remain consistent: https://github.com/octokit/octokit.rb/releases

**Comment by tarebyte** [comment]
Thanks for the feedback @olivierlacan I've gone ahead and updated the latest release.
