### ISSUE TITLE
Creating contents to .github/workflows/ fails

### ISSUE THREAD

**Issue by eric-silverman** [octokit/octokit.rb#1184]
Hi, I'm using the create contents API to add/update a file's contents to  .github/workflows/

is .github/workflows/ a protected path? This gives a 404 even though I can read the contents of this path

```
 client.create_contents(repo_id,
                                              ".github/workflows/test.yml",
                                              "message",
                                              "contents",
                                              :branch => branch_name)

```

**Comment by tarebyte** [comment]
@eric-silverman there's a few things that can be wrong. First, can you tell us what kind of credential you are using Personal Access Token / OAuth token / GitHub App etc.

**Comment by eric-silverman** [comment]
Personal access token. 

I can add a file to .github/ but not github/workflows and the path already exists

**Comment by tarebyte** [comment]
@eric-silverman what are the scopes on that Personal Access token? You might be missing the `workflow` scope.

**Comment by eric-silverman** [comment]
scopes are 

[
    [0] "read:org",
    [1] "read:user",
    [2] "repo",
    [3] "user:email"
]

you would need a workflow scope to add a file to that path?

**Comment by eric-silverman** [comment]
Additionally, if this was done as a github app, what permission would it need to have?

**Comment by tarebyte** [comment]
> you would need a workflow scope to add a file to that path?

Yes

> Additionally, if this was done as a github app, what permission would it need to have?

There is a new Actions permission coming out soon I believe.
