### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by kaspernj** [octokit/octokit.rb#1191]
I started getting mails with the following subject: Deprecation notice for authentication via URL query parameters

I allow users to authenticate through Github and uses their OAuth token to read a configuration file they add to their repository.

I use Octokit like this:
```ruby
Octokit::Client.new(
  access_token: access_token,
  client_id: ENV.fetch("GITHUB_KEY"),
  client_secret: ENV.fetch("GITHUB_SECRET")
)
```

As far as I understand, Octokit should use HTTP basic auth instead of passing the client ID and secret as query parameters? :-)

**Comment by rai-hi** [comment]
Apologies - I'm not familiar with the release schedule of Octokit.

Any idea how long this will take to be included in a release?

Thanks for getting a fix in place so quickly!

**Comment by tarebyte** [comment]
@rai-hi we're going to try and get a release out this week.

**Comment by tarebyte** [comment]
https://github.com/octokit/octokit.rb/releases/tag/v4.16.0has been released.
