### ISSUE TITLE
Test failures on arm64

### ISSUE THREAD

**Issue by utkarsh2102** [octokit/octokit.rb#1198]
Hi there,

Thanks for your work on this gem.
However, while building this against Ruby2.7 on arm64, I got the following error:
```
Failures:

  1) Octokit::Client.agent caches the agent
     Failure/Error: expect(agent.object_id).to eq(Octokit.client.agent.object_id)

       expected: 93826036147220
            got: 93826036172140

       (compared using ==)
     # ./spec/octokit/client_spec.rb:316:in `block (3 levels) in <top (required)>'

Finished in 45.85 seconds (files took 2.04 seconds to load)
778 examples, 1 failure

Failed examples:

rspec ./spec/octokit/client_spec.rb:314 # Octokit::Client.agent caches the agent

Randomized with seed 43730
```

Could you perhaps help us figure this out?

**Comment by tarebyte** [comment]
@utkarsh2102 I imagine that since you're using a different processor that whatever we're running on the tests that we'll always run into different object ids. But that would be a best guess.

Is there a reason for running these specs on arm64?

**Comment by utkarsh2102** [comment]
Hi @tarebyte,

> I imagine that since you're using a different processor that whatever we're running on the tests that we'll always run into different object ids.

In that case, would it make sense for me to disable this particular test?

> Is there a reason for running these specs on arm64?

I maintain this gem in Debian and therefore this needs to be built on all architectures, as we generally do with all Debian packages.

**Comment by tarebyte** [comment]
@utkarsh2102 I think this might've actually been fixed in https://github.com/octokit/octokit.rb/pull/1201

Mind verifying?

**Comment by utkarsh2102** [comment]
Hi @tarebyte,
Thanks for this, I've uploaded this snapshot to Debian again.
Likely this should fix this problem. In case it doesn't, I shall report back!

**Comment by MSP-Greg** [comment]
@utkarsh2102

Any news?  You didn't mention whether the issue was intermittent. If so, seed values (for the failures) would be helpful.

**Comment by utkarsh2102** [comment]
Hi @MSP-Greg @tarebyte,
#1201 works pretty alright :)
I haven't faced any failures or regressions so far, so looks like everything is good indeed!
Thank you for your help! <3
