### ISSUE TITLE
Listing starred repos with star creation timestamps

### ISSUE THREAD

**Issue by namiwang** [octokit/octokit.rb#1204]
As stated in the [doc](https://developer.github.com/v3/activity/starring/#alternative-response-with-star-creation-timestamps-1), there's an approach to list starred repos with a `starred_at` field, which is very useful and it'd be great if we could have this function in octokit.rb.

**Comment by tarebyte** [comment]
@namiwang you in fact can do that now:

```ruby
client = Octokit::Client.new(access_token: YOUR_GITHUB_TOKEN)
client.starred("namiwang", accept: "application/vnd.github.v3.star+json")
```

This will pass the proper `Accept` header to the API to return the result.

**Comment by namiwang** [comment]
Ah sorry for missing that! Thank you good sir.

**Comment by namiwang** [comment]
@tarebyte 

Hi!

I just found that while 

```
client = Octokit::Client.new(access_token: YOUR_GITHUB_TOKEN)
client.starred("namiwang", accept: "application/vnd.github.v3.star+json")
```

works fine,

```
client = Octokit::Client.new(access_token: YOUR_GITHUB_TOKEN)
client.starred(accept: "application/vnd.github.v3.star+json").first # nil
```
 doesn't work.

I thought the user doesn't have to provide the login after authed via access_token.

Do you think this is expected? Thanks!

**Comment by tarebyte** [comment]
@namiwang you have to set `:login` at the client initialization in order for it know what login you want to use.

```ruby
client = Octokit::Client.new(login: "namiwang", access_token: YOUR_GITHUB_TOKEN)
client.starred(accept: "application/vnd.github.v3.star+json")
```
