### ISSUE TITLE
Description about the default value of the `per_page` option

### ISSUE THREAD

**Issue by ybiquitous** [octokit/octokit.rb#1215]
Hi there,

I found the difference between README and the actual code, about the default `per_page` value.

REAMDE: `30`

> Default results from the GitHub API are 30, if you wish to add more you must do so during Octokit configuration.

https://github.com/octokit/octokit.rb/blob/c5037e4abbf154b2123019e8d109e24490bf1be5/README.md#default-results-per_page

Code: `100`

https://github.com/octokit/octokit.rb/blob/116ddac2a9c962b4016ca31fb69f62b14361adb0/lib/octokit/connection.rb#L81

It seems that the README description is incorrect, but what do you think?
Thanks.

**Comment by tarebyte** [comment]
@ybiquitous the actual GitHub API defaults to 30 if we don't pass in a `per_page` query parameter. It looks like we set it in the client as `100` if we are auto paginating so that we make fewer requests.

I'm not sure I see the inconsistency here.

**Comment by ybiquitous** [comment]
Surely, there is no inconsistency.
But the behavior, which `per_page` is `100` if `auto_paginate` is set, seems undocumented and may confuse users (like me 😅 ).

So, what about documenting that behavior on this README?
