### ISSUE TITLE
Get contribution list of commit by file path

### ISSUE THREAD

**Issue by mpermperpisang** [octokit/octokit.rb#1224]
Hi, first of all thanks a lot for this awesome repository
I want to ask how to get a list of contribution by file like this `https://api.github.com/repos/:owner/:repo/commits?path=README.md`?

I read `http://octokit.github.io/octokit.rb/Octokit/Client/Commits.html` but still not sure how to do it. Is it possible to do that?

Thanks

**Comment by tarebyte** [comment]
Hi @mpermperpisang 👋 

In order to limit the commits by path you would just need to update the call to look something like:

```ruby
client = Octokit::Client.new
client.commits("tarebyte/dotfiles", path: "README.md")
```

Adding the `path` as a KWARG adds it to the path as a query parameter.
