### ISSUE TITLE
Coveralls is not working

### ISSUE THREAD

**Issue by ybiquitous** [octokit/octokit.rb#1244]
I noticed that the `coveralls` gem is not working on CI. See below:

https://github.com/octokit/octokit.rb/runs/583312202?check_suite_focus=true#step:6:26

```
Coveralls encountered an exception:
NoMethodError
undefined method `coverage' for #<SimpleCov::SourceFile:0x0000559805623520>
Did you mean?  coverage_data
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/coveralls-0.7.2/lib/coveralls/simplecov.rb:50:in `block in format'
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/coveralls-0.7.2/lib/coveralls/simplecov.rb:40:in `format'
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/simplecov-0.18.5/lib/simplecov/formatter/multi_formatter.rb:10:in `block in format'
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/simplecov-0.18.5/lib/simplecov/formatter/multi_formatter.rb:8:in `map'
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/simplecov-0.18.5/lib/simplecov/formatter/multi_formatter.rb:8:in `format'
```

The cause of the error seems that the `coveralls` gem does support the latest `simplecov` gem.
The `simplecov` gem had the API change with the [v0.18.0](https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md#0180-2020-01-28).
See also <https://github.com/colszowka/simplecov/commit/6e7a9ab3fa2c03ee86930596139270d822e2cc77>.

In addition, according to <https://github.com/lemurheavy/coveralls-ruby/issues/130>, the `coveralls` gem seems unmaintained.

**Comment by hmharvey** [comment]
Thanks for opening this up and adding all the context! We'll look at removing the `coveralls` dependency as it's not one we use much 🙇‍♀️

**Comment by janosrusiczki** [comment]
I logged an issue and a solution on the coveralls repo too.

https://github.com/lemurheavy/coveralls-ruby/issues/161

The solution is to switch away from the official coveralls gem.
