### ISSUE TITLE
[Feature Request] Return Octokit::RateLimit struct as context for 401 / Forbidden errors to have better error handling

### ISSUE THREAD

**Issue by jatindhankhar** [octokit/octokit.rb#1265]
At times when Github Rate Limiting kicks in, Octokit starts throwing `Octokit::Forbidden`, usually it is `TooManyRequests` or `AbuseDetected` 

In such cases it is help to get the `Octokit::RateLimit` so the consumer can appropriate take action of retrying the error ( for example using the `resets_at` / `resets_in` to trigger retry after the prescribed time )

For `AbuseDetected` we can also expose `Retry-After` from the response headers

If this seems something that have chances of merging, I can submit a PR.

From the surface, the changes seems simple, just need to modify the error initialiser 

`lib/octokit/error.rb` 
 

```ruby 
def initialize(response=nil,context=nil)
      @response = response
      super(build_error_message)
      context = Octokit::RateLimit.from_response(response) if self.superclass == Octokit::Forbidden
    end
```

So consumer can use it 

```ruby 
    sidekiq_retry_in do |attempt, exception|
    case exception
    when Octokit::TooManyRequests
      exception.context.resets_in
    when Octokit::AbuseDetected
      exception.context.resets_in
    end
  end
```

**Comment by tarebyte** [comment]
This sounds like a neat feature, we'd love to see a PR @jatindhankhar ✨

**Comment by jatindhankhar** [comment]
Hi @tarebyte,

Thanks for validating the initial idea, here is the PR that should work - https://github.com/octokit/octokit.rb/pull/1270

Please check whenever you have a free moment :)

**Comment by jatindhankhar** [comment]
Closing since PR #1270 was merged
