### ISSUE TITLE
The documentation looks old; the last update seemed to be done on v4.11.0

### ISSUE THREAD

**Issue by yykamei** [octokit/octokit.rb#1268]
I found out some methods are not described on http://octokit.github.io/octokit.rb/. As I see the last commit of [gh-pages](https://github.com/octokit/octokit.rb/tree/gh-pages), this document seems to show the APIs for v4.11.0.

It would be great that the document is updated to the latest version.

Thanks,

**Comment by yykamei** [comment]
I think it may be good to add a workflow to automatically publish the GitHub page. How about using [GitHub Pages action](https://github.com/marketplace/actions/github-pages-action)? This action looks well maintained and popular. If it makes sense, I'm ready to address it :muscle:

**Comment by hmharvey** [comment]
👋🏻  @yykamei 

Thank you for opening up this issue, the docs are really out of date! We're going to wait for some internal work to finish up so we can remove the `gh-pages` branch dependency but we should be able to update it soon. Once we do, we'd definitely love to add an action to keep it automatically up to date  🎉

**Comment by yykamei** [comment]
Thank you for replying, and I'm glad to hear that. I'm looking forward to the new pages. I'll close this PR after I confirm it.

**Comment by dzaslavskiy** [comment]
any updates?
