### ISSUE TITLE
How do you set Accept Headers in a post request?  (Maybe a bug, maybe a documentation clarification request)

### ISSUE THREAD

**Issue by pconrad** [octokit/octokit.rb#1274]
When using the `post` method of `Client`, Octokit.rb , how do you set custom `Accept:` headers in order to turn on a "preview" API?

Here are two tries that don't work.  I can't tell if I'm following the documentation incorrectly, or if there is a bug.

For context: the method `graphql_query_string` forms the correct query string, and `github_machine_user` is an instance of an Octokit `Client` object

```ruby
   def perform_graphql_query(repo_name, org_name, after="")
      graphql_query_string = graphql_query(repo_name, org_name, after)
      options = {:query => graphql_query_string, 
        :headers => {:accept => "application/vnd.github.starfox-preview+json"}
      }.to_json
      github_machine_user.post('/graphql', options)
     
   end
```

This results in the default `Accept` header being used, which is, apparently `"application/vnd.github.v3+json"`  (I can tell because I followed the [advice in the Octokit documentation about turning on debugging info](http://octokit.github.io/octokit.rb/#Debugging) and here's what the output shows:

```
I, [2020-07-24T12:26:37.989030 #64350]  INFO -- request: POST https://api.github.com/graphql
I, [2020-07-24T12:26:37.989109 #64350]  INFO -- request: Accept: "application/vnd.github.v3+json"
User-Agent: "Octokit Ruby Gem 4.15.0"
Content-Type: "application/json"
Authorization: "token REDACTED_FOR_STACK_OVERFLOW_POST"
```

This doesn't work either:

```ruby 
   def perform_graphql_query(repo_name, org_name, after="")
      graphql_query_string = graphql_query(repo_name, org_name, after)
      options = {
          :query => graphql_query_string, 
          :accept => "application/vnd.github.starfox-preview+json"
      }.to_json
      github_machine_user.post('/graphql', options)
    end
```

 From reading both the [documentation for post](http://octokit.github.io/octokit.rb/Octokit/Connection.html#post-instance_method)  the source code for the [post](https://github.com/octokit/octokit.rb/blob/dbea2c6c72637965f75517c006cea0870c920798/lib/octokit/connection.rb#L27) method and the underlying [request](https://github.com/octokit/octokit.rb/blob/dbea2c6c72637965f75517c006cea0870c920798/lib/octokit/connection.rb#L147) method, I would have expected this to work.  

I did verify that using `curl`, I was able to get the exact same graphql query to work properly by passing the  `Accept` header.; and the error I'm getting when using Octokit is the same error you get when the header is NOT set correctly. 

Am I doing something wrong, or is it a bug in Octokit?
 
I also posted a question to [StackOverflow](https://stackoverflow.com/questions/63080709/with-octokit-rb-ruby-library-for-github-api-how-do-you-set-accept-header-in-p)

**Comment by pconrad** [comment]
An update: This didn't work either:

```
def perform_graphql_query(repo_name, org_name, after="")
      graphql_query_string = graphql_query(repo_name, org_name, after)
      options = {
          :query => graphql_query_string, 
          :accept => Octokit::Preview::PREVIEW_TYPES[:project_card_events]
      }.to_json
      github_machine_user.post('/graphql', options)
    end
```

I see that there is a method `#ensure_api_media_type(type, options) ⇒ Object`  but it isn't clear how to invoke that, or whether it would even make any difference.   It appears to be a pure method with no side effects on anything other than the options hash, and printing out a warning about preview APIs.

**Comment by hmharvey** [comment]
It looks like you found an answer given the response on StackOverflow, but GitHub also has a [GraphQL client](https://github.com/github/graphql-client) that might better fit your needs since this is a REST API client. However, it looks like you are doing the right steps, so maybe setting the accept header in the client would work.
