### ISSUE TITLE
[Feature request] Add an option to request team reviewers

### ISSUE THREAD

**Issue by AndreiNikitin** [octokit/octokit.rb#1275]
As github documentation says it is possible to add not only single users but a team also. See the link below
https://developer.github.com/v3/pulls/review_requests/#create-a-review-request

Would be great if you will add this possibility to "request_pull_request_review" command
https://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html#request_pull_request_review-instance_method

**Comment by AndreiNikitin** [comment]
Sorry, just saw that I can do that with an "option" argument. But it is quite confusing. Renaming it to smth like "team-reviewers" might help.

**Comment by tarebyte** [comment]
We appreciate the feedback, renaming the preview would be a breaking change though unless we kept both.

Glad you found the answer!
