### ISSUE TITLE
How to access the list of dependabot warnings?

### ISSUE THREAD

**Issue by rdunlop** [octokit/octokit.rb#1284]
I have enabled the "Dependency Graph" and "Dependabot Alerts" on my private repository.
Under the "Security" tab, there is a "Dependabot alerts" which shows me the alerts for Gemfile.lock and yarn.lock library vulnerabilities.

I would like to access this information via the Github API so that I can aggregate it together across all of my repositories.

I thought that perhaps this was possible via the `code-scanning/alerts` [API](https://docs.github.com/en/rest/reference/code-scanning#list-code-scanning-alerts-for-a-repository), but I have not had success with this.

I am unclear whether there's a difference between the Dependabot Security warnings, and the "[Code Scanning an Secret Scanning](https://github.com/features/security/advanced-security/signup)". I'm not trying to sign up for advanced code scanning....I'm trying to access information which is already being published to the UI of my repository....but via the API.

Does anyone know how this works? Is there any API to access this information? Would the "Private Beta" grant me access to the alerts through the `/code-scanning/alerts` endpoint?

**Comment by rdunlop** [comment]
Ah, there is [a thread which implies that it's possible](https://github.community/t/are-security-vulnerabilities-available-via-api/13522/5)...

**Comment by rdunlop** [comment]
I've managed to retrieve the information [using GraphQL Explorer](https://developer.github.com/v4/explorer/) via:

using the command:
```
query { 
  repository(owner:"<redacted>", name:"<redacted>") {
    id
    name
    description
    vulnerabilityAlerts(first: 10) {
      totalCount
      nodes {
        id
        securityAdvisory {
          description
          summary
        }
        securityVulnerability {
          advisory {
            id
          }
          severity
        }
        vulnerableManifestFilename
        vulnerableManifestPath
        vulnerableRequirements
      }
      
    }
  }
  
}
```

I'm not sure if I'll be able to do this through the Octokit, since it appears to be only focused on the REST Api...I don't know if this is a not available in the REST API because we're on Rest v3  and GraphQL is v4...or if those are even related....

I continue to troubleshoot figuring out how to access this information programatically.

**Comment by stevekrouse** [comment]
Thanks for this! Very helpful for me. 

Here's how I ran it on Octokit:

```ruby
client = Octokit::Client.new(access_token: access_token)
query = <<~GRAPHQL
  query { 
    repository(owner:"#{owner}", name:"#{name}") {
      id
      name
      description
      vulnerabilityAlerts(first: 100) {
        totalCount
        nodes {
          createdAt
          dismisser {
            id
            name
          }
          dismissedAt
          dismissReason
          repository {
            id
            nameWithOwner
          }
          id
          securityVulnerability {
            advisory {
              id
              ghsaId
              description
              summary
              severity
              updatedAt
            }
            severity
          }
          vulnerableManifestFilename
          vulnerableManifestPath
          vulnerableRequirements
        }
      }
    }
  }
GRAPHQL
client.post("/graphql", { query: query }.to_json).to_hash.dig(:data, :repository, :vulnerabilityAlerts, :nodes)
```

**Comment by tarebyte** [comment]
Closing this as it looks like this has been resolved.
