### ISSUE TITLE
Waiting for new version of Octokit

### ISSUE THREAD

**Issue by gat-bryszard** [octokit/octokit.rb#1292]
Hello, 

Last version of Octokit.rb is now from March (4.18.0) and I can see that there are many updates from this point of time on `4-stable` branch, including support for Actions API, which I currently would need. 

Is there any plan for new release?

**Comment by tarebyte** [comment]
https://github.com/octokit/octokit.rb/releases/tag/v4.19.0 🎉

**Comment by gat-bryszard** [comment]
@tarebyte Wow! I'm not sure if that was a reaction to my issue or it was planned, but the effect is amazing. Thanks!
