### ISSUE TITLE
Private Orgnaziation Repos Not Listed:

### ISSUE THREAD

**Issue by ddavisgraphics** [octokit/octokit.rb#1295]
```ruby
client = Octokit::Client.new(access_token: token, per_page: 200)
repos = client.repositories('myorganizationhere', per_page: 200)
puts repos.count # yeilds 39 expected 125
```

When I login using my personal token to the client, if I can see my user and information.  I can't find anyway to list all the public and private repositories that are in the organization github.  

The idea is that we can use all the repo information to clone all the items in the Github repositories everyone once in a while as an automated backup.

**Comment by tarebyte** [comment]
@ddavisgraphics a few notes:

- It looks like you want `client.org_repositories` not `client.repositories` https://github.com/octokit/octokit.rb/blob/519512aed8bbbc781ad1c1743c162aa6dbcb4862/lib/octokit/client/organizations.rb#L105-L129
- Does your personal access token have the `repo` scope?
- Is the organization in question protected by SAML SSO?
