### ISSUE TITLE
Appears Impossible for App to Assign Team when Creating New Repo

### ISSUE THREAD

**Issue by briandoyle81** [octokit/octokit.rb#1305]
The :team_id option in #create_repository appears to be unusable with secret teams.  It returns an error that a user must be a member of the team to assign it to a repo.  However, it appears impossible to add an installed app to a team.

**Comment by tarebyte** [comment]
@briandoyle81 I would reach out to GitHub Support. This sounds like an issue with the API rather than with out client.

If I'm mistaken please let me know.
