### ISSUE TITLE
getting pull request opener?

### ISSUE THREAD

**Issue by AraHaan** [octokit/octokit.rb#1320]
I would like to retrieve the pull request opener (to be specific I want to use this to find if dependabot opened the pull request).

However I am stuck with finding how I can do such a task.

**Comment by tarebyte** [comment]
If you're looking at a single pull request you'll find the author of the pull request under the `user` field. The payload body can be found here: https://docs.github.com/en/rest/reference/pulls#get-a-pull-request.

If you're trying to find all PRs by an author you'll be able to use the https://docs.github.com/en/rest/reference/issues#list-repository-issues endpoint. The issues that have pull requests will have a `pull_request` field. You'll be able to search by author.

Hope this helps!

**Comment by AraHaan** [comment]
Thanks, also is it also possible to deploy a cetain action when it sees a label change on a pull request as well too?

**Comment by tarebyte** [comment]
I'm not sure sorry, the best people to ask would be [GitHub Support](https://github.com/contact)
