### ISSUE TITLE
Crash on response 'Link" header parsing

### ISSUE THREAD

**Issue by ivailop** [octokit/octokit.rb#1325]
Since yesterday, the "Link" header returned when doing [Web application flow](https://docs.github.com/en/developers/apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github), i.e.
```
POST  login/oauth/access_token
```
is formatted in a way that results in a crash when calling [exchange_code_for_token](https://github.com/octokit/octokit.rb/blob/d56af021d21d9a8f623e0b41cac073c272864ec2/lib/octokit/client/users.rb#L46):
```
NoMethodError: undefined method `captures' for nil:NilClass
.../vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/response.rb:52:in `block in process_rels'
.../vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/response.rb:51:in `map'
.../vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/response.rb:51:in `process_rels'
.../vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/response.rb:20:in `initialize'
.../vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:107:in `new'
.../vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:107:in `call'
.../vendor/bundle/ruby/2.6.0/gems/octokit-4.19.0/lib/octokit/connection.rb:156:in `request'
.../vendor/bundle/ruby/2.6.0/gems/octokit-4.19.0/lib/octokit/connection.rb:28:in `post'
.../vendor/bundle/ruby/2.6.0/gems/octokit-4.19.0/lib/octokit/client/users.rb:57:in `exchange_code_for_token'
```

Besides questioning why GitHub API changed, apparently `sawyer` has a bug! 

FYI, to address the bug, in `sawyer`, I opened https://github.com/lostisland/sawyer/issues/68 issue and related https://github.com/lostisland/sawyer/pull/69 PR.

**Comment by osowskit** [comment]
@swinton any insight into recent changes that may have broken this?

**Comment by jeremie-stripe** [comment]
If it helps anyone, we are working around this by introducing a Faraday middleware step to strip the `Link` header in this situation (since the JS libraries are irrelevant in this case):

```ruby
class LinkHeaderRemover < Faraday::Response::Middleware
  OAUTH_LOGIN_URL_PATH = "/login/oauth/access_token"

  def on_complete(env)
    request_path = URI(env.url).path
    return if request_path != OAUTH_LOGIN_URL_PATH

    response_headers = env.response_headers
    return if response_headers.nil?

    response_headers.delete("link")
  end
end
```
Setup in your pipeline like so:

```ruby
middleware = Octokit::Default.middleware.dup
middleware.insert_before(middleware.handlers.length - 1, LinkHeaderRemover)
Octokit.middleware = middleware
```

**Comment by tarebyte** [comment]
I think this has been fixed on the GitHub side, is anyone running into these issues still?
