### ISSUE TITLE
Branch renaming support

### ISSUE THREAD

**Issue by gmcgibbon** [octokit/octokit.rb#1328]
I see support for branch renames in the [JS client](https://octokit.github.io/rest.js/v18#repos-rename-branch), but not here in the Ruby client. Are there any plans to add support for this? If there hasn't been any work done yet, I'd be happy to help!

Note that I'm not referring to _setting_ a default branch. I'm referring to the new `rename` feature that auto-switches PR targets, inherits protection rules, etc.

**Comment by tarebyte** [comment]
For my reference, this is the endpoint in question: https://docs.github.com/en/rest/reference/repos#rename-a-branch

We're happy to 👀 pull requests @gmcgibbon ✨
