### ISSUE TITLE
Login with Octokit::Client.new in the console rails

### ISSUE THREAD

**Issue by Ramsteven** [octokit/octokit.rb#1330]
Hello,i want login from console rails, then i create the oauth app inside of github and generate secret key, but when i try login with the console.
but when i try:
`client = Octokit::Client.new(login: ENV['GIT_U'],  password: ENV['GIT_PASS'])  # the GIT_U contains my username and GIT_PASS my password.` 
i get this response.
`Octokit::Unauthorized (GET https://api.github.com/user: 401 - Requires authentication // See: https://docs.github.com/rest/reference/users#get-the-authenticated-user).`

i install gem "octokit", "~> 4.0" , using ruby 2.7.2 and rails  6.1.3.1, also happen this with ruby 3 version. any advice?

**Comment by tarebyte** [comment]
@Ramsteven as of November 2020, the GitHub API does not allow you to authenticate to the API via username and password. See https://github.blog/changelog/2020-11-13-token-authentication-required-for-api-operations/ for more details.
