### ISSUE TITLE
Add Discussions to API

### ISSUE THREAD

**Issue by seigel** [octokit/octokit.rb#1331]
I am looking to see if management of the now-in-beta "Discussions" are in the API and can't seem to find a reference to it.  Is there an ETA?

**Comment by iftimasum** [comment]
Ibam

**Comment by tarebyte** [comment]
@seigel we don't have an ETA, but pull requests are always welcome!

**Comment by seigel** [comment]
I would like to know how to access it. I would do a pull request if I knew what to call. :)

**Comment by tarebyte** [comment]
@seigel you can [fork this repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo) to your GitHub Account, make the contributions on your fork then open a pull request against this repository.

**Comment by tarebyte** [comment]
@seigel in my haste I misunderstood your question and gave you an incorrect answer.

There currently is not a REST API for the Discussions feature. GitHub is currently only supporting the GraphQL API for it https://docs.github.com/en/graphql/reference/objects?query=discussions#discussion.

Sorry again about the confusion.

**Comment by seigel** [comment]
Thank you.  That helps a ton.  Thanks for following up with that.

Cheers
James
