### ISSUE TITLE
4.21 checks api changes break enterprise usage

### ISSUE THREAD

**Issue by lokucrazy** [octokit/octokit.rb#1334]
Hi, my team is using this octokit library in a tool that connects with our enterprise github.  in 4.21 the preview header needed for check runs in enterprise was [removed](https://github.com/octokit/octokit.rb/blob/v4.21.0/lib/octokit/preview.rb#L9), [4.20 for comparison](https://github.com/octokit/octokit.rb/blob/v4.20.0/lib/octokit/preview.rb#L9).  I am wondering why this was changed and if there is a possibility to still support enterprise in later versions or not.

**Comment by tarebyte** [comment]
@lokucrazy we removed it because it's not longer a preview on github.com, what version of Enterprise are you using?

Luckily this is not a breaking deal for you, as you can set `Accept` header on the Octokit client calls that you need.

Example:

```ruby
client = Octokit::Client.new(access_token: "foo")
client.check_runs_for_ref("octocat/Hello-World", "7638417db6d59f3c431d3e1f261cc637155684cd", status: "in_progress", accept: "application/vnd.github.antiope-preview+json")
```

**Comment by lokucrazy** [comment]
We're enterprise 2.22.4, I assume we're some versions behind so is it supported on later versions?

**Comment by tarebyte** [comment]
Yeah you're fairly far behind https://docs.github.com/en/enterprise-server@2.22/admin/release-notes#2.22.4 (November of 2020). Once you upgrade I believe this will resolve itself.
