### ISSUE TITLE
/user/repos endpoint missing

### ISSUE THREAD

**Issue by 0kzh** [octokit/octokit.rb#1345]
I'm trying to list all the repositories the user has access to, as specified by
https://docs.github.com/en/rest/reference/repos#list-repositories-for-the-authenticated-user

However, it seems like this route is missing from the client.
From the docs, there is:
- [client.all_respositories](https://octokit.github.io/octokit.rb/Octokit/Client/Repositories.html#all_repositories-instance_method) which fetches all public repostories
- [client.repositories](https://octokit.github.io/octokit.rb/Octokit/Client/Repositories.html#repositories-instance_method), which fetches the repositories for a given user

**Comment by tarebyte** [comment]
@0kzh if you don't pass in a `user` to the client.repositories method the request is `GET /user/repos`.

Step by step in the code

https://github.com/octokit/octokit.rb/blob/be7c105ec7b70e6dc5f83339df82edb3860a9458/lib/octokit/client/repositories.rb#L75
https://github.com/octokit/octokit.rb/blob/be7c105ec7b70e6dc5f83339df82edb3860a9458/lib/octokit/user.rb#L14-L15

If you pass a user in then it updates the path accordingly.

**Comment by 0kzh** [comment]
Ah, I was missing an OAuth scope which was why `client.repositories` was only returning some repos under my name. Thanks :)
