### ISSUE TITLE
pull_request_comments returns an empty array

### ISSUE THREAD

**Issue by congt** [octokit/octokit.rb#1346]
Octokit:: Client.pull_request_comments return an empty array for PRs with comments.

I also tried the REST API, which also returned an empty array. Here is an example:
```
curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/octocat/hello-world/pulls/46/comments
```

**Comment by tarebyte** [comment]
@congt you're probably looking for 

```sh
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/octocat/hello-world/issues/46/comments
```

This will list all of the comments on the pull request (confusing I know, all PRs have an issue backing them).

The route you were trying to use is actually for Pull Request Review comments https://docs.github.com/en/rest/reference/pulls#list-review-comments-on-a-pull-request.

Hope this helps ✨

**Comment by congt** [comment]
Ah, thanks for the quick reply!
