### ISSUE TITLE
Deprecation warning since Faraday 1.7.1

### ISSUE THREAD

**Issue by ybiquitous** [octokit/octokit.rb#1357]
Since [Faraday 1.7.1](https://github.com/lostisland/faraday/releases/tag/v1.7.1), the following methods of the `Faraday::Connection` class emits a deprecation warning:

- `#basic_auth`
- `#token_auth`
- `#authorization`

See also PR lostisland/faraday#1306

When running the specs on my local machine with the current HEAD revision (605a08a2), we can see the many warnings:

```console
$ bundle exec rspec
...
WARNING: `Faraday::Connection#authorization` is deprecated; it will be removed in version 2.0.
While initializing your connection, use `#request(:authorization, ...)` instead.
See https://lostisland.github.io/faraday/middleware/authentication for more usage info.
...
```

Used gem versions are as below:

```console
$ bundle list | grep faraday
  * faraday (1.7.1)
  * faraday-em_http (1.0.0)
  * faraday-em_synchrony (1.0.0)
  * faraday-excon (1.1.0)
  * faraday-httpclient (1.0.1)
  * faraday-net_http (1.0.1)
  * faraday-net_http_persistent (1.2.0)
  * faraday-patron (1.0.0)
  * faraday-rack (1.0.0)
```

I think Octokit needs to fix the warnings to prevent users' application logs from being flooded with them.

**Comment by ybiquitous** [comment]
These methods have been deleted on Faraday HEAD: https://github.com/lostisland/faraday/pull/1308

**Comment by xiaoxipang** [comment]
Thanks for the fix! Looking forward to seeing this PR merging in soon because we use tons of octokit APIs and got tons of warnings now :p

**Comment by unicornzero** [comment]
I'm seeing a lot of deprecation warnings now that I've had to update faraday because of a critical dependency. Is there any word on getting this change into a release soon?

**Comment by claybridges** [comment]
In the meantime, I fixed this in my own usage (scripts) by putting this in my `Gemfile`:
```
gem 'octokit'
gem 'faraday', '1.7.0'
```

**Comment by kaiomagalhaes** [comment]
@ybiquitous thanks for your solution on: https://github.com/ybiquitous/octokit.rb/tree/issue-1357

I'll be using it until we get a final solution on master.
