### ISSUE TITLE
[Announcement] @tarebyte stepping down as maintainer

### ISSUE THREAD

**Issue by tarebyte** [octokit/octokit.rb#1365]
Hi folks 👋 

I just wanted to make a quick announcement that as of today I am no longer maintaining the octokit.rb ruby gem. It's been a pleasure over the last few years, and I sincerely thank everyone who has contributed to make this library so popular and accessible to the Ruby community.

With all of those wonderful contributions means that there is an expectation around timely releases, code review, new API support, etc. However, I am not able to dedicate that time in my off hours and that's not fair to the community.

**Who is maintaining this going forward?**

I'm not sure, this is a GitHub owned library and so I'm positive they will find someone else to take this over in my stead. An announcement will probably be made when that time comes.

Thank you all again for your support and best of luck in the future.

All the best,
@tarebyte

**Comment by Christoc90** [comment]
> Salut les gens ??
> 
> Je voulais juste faire une annonce rapide qu'à partir d'aujourd'hui, je ne maintiens plus la gemme ruby ​​octokit.rb. Cela a été un plaisir au cours des dernières années, et je remercie sincèrement tous ceux qui ont contribué à rendre cette bibliothèque si populaire et accessible à la communauté Ruby.
> 
> Avec toutes ces merveilleuses contributions, cela signifie qu'il y a une attente autour des versions opportunes, de la révision du code, de la nouvelle prise en charge des API, etc. Cependant, je ne suis pas en mesure de consacrer ce temps pendant mes heures de repos et ce n'est pas juste pour la communauté.
> 
> **Qui maintient cela à l'avenir?**
> 
> Je ne suis pas sûr qu'il s'agisse d'une bibliothèque appartenant à GitHub et je suis donc certain qu'ils trouveront quelqu'un d'autre pour prendre le relais à ma place. Une annonce sera probablement faite le moment venu.
> 
> Merci encore à tous pour votre soutien et bonne chance pour la suite.
> 
> Tout le meilleur, @tarebyte
