### ISSUE TITLE
Add cross-support for Faraday 1.x.x and 2.x.x

### ISSUE THREAD

**Issue by ashishkeshan** [octokit/octokit.rb#1388]
With the merge of: https://github.com/octokit/octokit.rb/pull/1359 to silenece deprecation warnings, and based on the comment here: https://github.com/octokit/octokit.rb/pull/1359#issuecomment-924648404, we will need to modify the code to cross-support Faraday 1.x.x and 2.x.x when octokit pulls in the latest version of Faraday. Opening this issue now to track the work necessary when the times comes.

**Comment by klueless-io** [comment]
I'm not sure if this is related, but when I run this code 

`Octokit::Client.new(access_token: token)`

I get this warning

> WARNING: `Faraday::Connection#authorization` is deprecated; it will be removed in version 2.0.
While initializing your connection, use `#request(:authorization, ...)` instead

I'm aware of this [Faraday Middleware Guide](https://lostisland.github.io/faraday/middleware/authentication) but I'm not sure how this relates to `Octokit::Client`

Is there a way of suppressing the warning with Octokit at the moment?

**Comment by dsandstrom** [comment]
@klueless-io It's what #1359 addresses. The fix is not published yet, but you could use the github version of the gem.

```rb
gem 'octokit', github: 'octokit/octokit.rb', tag: '4-stable'
```

**Comment by hmharvey** [comment]
Cross referencing other issues showing that such support would be widely appreciated: 
- https://github.com/octokit/octokit.rb/issues/1392
- https://github.com/octokit/octokit.rb/issues/1391 
- https://github.com/octokit/octokit.rb/issues/1389

**Comment by professor** [comment]
Thanks for doing this work. 

Note that for octokit to be installed with Faraday 2.x.x, we'll need to bump `sawyer` to either `0.9.0` or `0.9.1`

**Comment by nickfloyd** [comment]
Cross-referencing given that [v4.23.0](https://github.com/octokit/octokit.rb/releases/tag/v4.23.0) introduces v2 support via  #1411

**Comment by nickfloyd** [comment]
This is now supported from [v4.23.0](https://github.com/octokit/octokit.rb/releases/tag/v4.23.0) and on.  I'm closing this issue but if you feel that the latest releases have not solved this please feel free to repoen this and we'll have a look.
