### ISSUE TITLE
Looks like 4.22.0 is breaking CI builds that rely on 5.16.1 of `danger` gem

### ISSUE THREAD

**Issue by afilbert** [octokit/octokit.rb#1389]
CI started breaking around the org, for us, as soon as 4.22.0 was released.

![dangerfailure](https://user-images.githubusercontent.com/523157/149238934-6b02676c-eab6-419e-919d-5f1fa69d0c96.png)
![Screen Shot 2022-01-12 at 5 21 36 PM](https://user-images.githubusercontent.com/523157/149239044-56e5cd36-de0f-4f46-907d-2a39562ee697.png)

Cost a few of us the afternoon. I didn't have the time to troubleshoot and figure out the cause, but locking the gem in our envs to the previous version worked:

```
gem install danger --version '~> 5.0' && gem install octokit -v '4.21.0' && gem uninstall octokit -v '>= 4.22.0'
```

**Comment by afilbert** [comment]
A lil more context, danger is configured with a github user that uses a personal access token with access to the repos. `curl` GET requests to the repo worked just fine passing our token, but whatever changed in this latest release treats those requests like they're not setting the auth headers

**Comment by dsandstrom** [comment]
Not sure if related, but it appears that you are using a really old version of faraday. Are you able to update to 1.9.3?

**Comment by afilbert** [comment]
> Not sure if related, but it appears that you are using a really old version of faraday. Are you able to update to 1.9.3?

You're right, we were pinning Faraday to a very early version in our config, but that didn't actually seem to be the problem. We had another project that wasn't pinning Faraday to 0.15.4 that was also failing on danger version 5.16.1. Bumping danger's version to latest (8.4.2) seemed to do the trick. We're still evaluating if it's ok to bump that dependency that many versions across all our projects.

**Comment by dangkaka** [comment]
Bumping danger's version to latest (8.4.2) fixed the issue. it worked for my case

**Comment by Tada-0709** [comment]
I am having the same issue the github action ran smoothly 2 days ago and the version of octokit is v4.21
<img width="667" alt="Screen Shot 2022-01-14 at 13 53 08" src="https://user-images.githubusercontent.com/45982145/149464300-4e328689-d60f-4e74-9701-8e0de85d4ce7.png">

<img width="789" alt="Screen Shot 2022-01-14 at 13 52 26" src="https://user-images.githubusercontent.com/45982145/149464247-72610af7-f913-412e-ac3f-d8db077e8b6f.png">

**Comment by dentarg** [comment]
I guess https://github.com/octokit/octokit.rb/discussions/1492 / https://github.com/octokit/octokit.rb/issues/1392 explains this issue, and seeing #1392 is closed I assume this can be closed too

**Comment by kfcampbell** [comment]
Agreed with @dentarg; closing this now.
