### ISSUE TITLE
`Octokit::RateLimit` fields are all `nil` after a `Octokit::TooManyRequests` exception

### ISSUE THREAD

**Issue by andyw8** [octokit/octokit.rb#1400]
I'm trying to call `RateLimit#context` (as added in https://github.com/octokit/octokit.rb/pull/1270) but the fields are all `nil`:

```
[2] pry(#<GithubClient>)> e
=> #<Octokit::TooManyRequests: GET https://api.github.com/search/issues?[...]: 403 - API rate limit exceeded for user ID 12345. // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting>
[3] pry(#<GithubClient>)> e.context
=> #<struct Octokit::RateLimit limit=nil, remaining=nil, resets_at=nil, resets_in=nil>
```

Running v4.22.0 (against GitHub Enterprise, in case that matters).

**Comment by moiseya** [comment]
Any update on this issue?

**Comment by timrogers** [comment]
Hi @moiseya ! This isn't something we have looked at yet. You'd be welcome to take a look and try to come up with a fix if you have time.

**Comment by DougEdey** [comment]
This one bit me today, I've done everything that I can in the PR above
