### ISSUE TITLE
Octokit creating issue: Wrong creator

### ISSUE THREAD

**Issue by VeraRibeiro** [octokit/octokit.rb#1404]
Hello,

I've implemented GitHub with octokit on the platform I work on, https://stage.trackonperformance.com/. When creating an issue, instead of fetching the user that is logged in (and gave permission to GitHub) it is fetching a completely different user, and saying that the issue was created by them

My user is Vera Ribeiro, I've created the issue as Vera Ribeiro on my platform and I'm even the one who owns the Auth0 application. However, it is creating in the name of my colleague, Rita Moreira

Please let me know how I can fix this
Thank you

![Screenshot 2022-02-24 at 11 13 05](https://user-images.githubusercontent.com/47228478/155709617-324a28df-8be5-41bb-9383-4c16cfdfc1bf.png)

![Screenshot 2022-02-24 at 11 14 22](https://user-images.githubusercontent.com/47228478/155709621-5fe36caa-054f-4c71-a19f-d95c3ebb273e.png)

Best regards,
Vera Ribeiro

**Comment by timrogers** [comment]
@VeraRibeiro Hi there! 👋🏻 Sorry that it has taken us a long while to get back to you on this Are you still having this issue? It seems unlikely that it'll be caused by Octokit itself - it looks more like something to do with how authentication works in the API.
