### ISSUE TITLE
404 failure for netrc auth in 4.22.0

### ISSUE THREAD

**Issue by ivanboykoatitv** [octokit/octokit.rb#1409]
We  use `~/.netrc` for authentication with GitHub.
```
      client = Octokit::Client.new(netrc: true)
      client.get_public_key("....")
```

It works fine with octokit  version `4.21.0` but fails with version `4.22.0`:
```
Octokit::NotFound: GET https://api.github.com/repos/***/***/actions/secrets/public-key: 404 - Not Found // See: https://docs.github.com/rest/reference/actions#get-a-repository-public-key
~/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
~/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
```

Manual curl using netrc authentication also works fine:
```
curl -n https://api.github.com/repos/***/***/actions/secrets/public-key
```

**Comment by timrogers** [comment]
On second thoughts, I think this is probably related to #1392. Do you know which Faraday version you're using? You should be able to see that in your `Gemfile.lock`.
