### ISSUE TITLE
NameError: uninitialized constant Octokit::RateLimit

### ISSUE THREAD

**Issue by collinsauve** [octokit/octokit.rb#1422]
In 4.22 we had a unit test that raised this error, so we could test that our code behaved accordingly.  With the upgrade to 4.23, when we try to

```ruby
raise Octokit::TooManyRequests
```

we get the following:

```
NameError: uninitialized constant Octokit::RateLimit

     @context = Octokit::RateLimit.from_response(@response)
                       ^^^^^^^^^^^
from ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/octokit-4.23.0/lib/octokit/error.rb:39:in `build_error_context'
```

This can be reproduced easily with a new project that only depends on Octokit 4.23, and using `pry` to raise it.  I have put together a repository with that reproduction here:

https://github.com/collinsauve/Octokit-toomanyrequests-error

Additionally, the same issue *cannot* be reproduced in 4.22 as shown in this branch of that repository:

https://github.com/collinsauve/Octokit-toomanyrequests-error/tree/4.22

**Comment by nickfloyd** [comment]
Fixed in release [v4.24.0](https://github.com/octokit/octokit.rb/releases/tag/v4.24.0)
