### ISSUE TITLE
Reintroduce client autoloads

### ISSUE THREAD

**Issue by nickfloyd** [octokit/octokit.rb#1427]
RE: https://github.com/octokit/octokit.rb/pull/1351 | https://github.com/octokit/octokit.rb/pull/1425 | https://github.com/octokit/octokit.rb/issues/1422 for more information

The original change for this [PR](https://github.com/octokit/octokit.rb/pull/1351) was introduced in [v4.23.0](https://github.com/octokit/octokit.rb/releases/tag/v4.23.0).  

For the most part, this change is/was beneficial but after @collinsauve highlighted an [issue](https://github.com/octokit/octokit.rb/issues/1422) that he was having as a result of this change we realized other areas where autoloading could cause issues due to modules not being loaded or load order even - details [here](https://github.com/octokit/octokit.rb/pull/1425).

- [x] We need to rollback the original PR and post another release (https://github.com/octokit/octokit.rb/pull/1428)
- [x] Make a note in the original [changelog](https://github.com/octokit/octokit.rb/releases/tag/v4.23.0) of this issue
- [ ] We need to consider optional ways to introduce this change (as part of the instantiation opts, etc...) 
- [ ] Reintroduce this change as an opt-in feature

**Comment by collinsauve** [comment]
Thanks for that investigation @nickfloyd - makes sense now why we were having this issue.  

My 2 cents, though I'm just one of many users:  We can probably work-around the breaking change, now that we know the cause.   Calling it out in a changelog somewhere (with a documented workaround 🙏) would be helpful for others.

**Comment by nickfloyd** [comment]
@collinsauve fantastic idea, once I get the "rollback" done I'll annotate the release notes. Thanks, and great catch!

**Comment by nickfloyd** [comment]
> Thanks for that investigation @nickfloyd - makes sense now why we were having this issue.

@timrogers was the one that finally tracked it down I believe ([here](https://github.com/octokit/octokit.rb/pull/1425)).  I'll reach out to him to get his thoughts on what he feels would be a good workaround to document for others might be.
