### ISSUE TITLE
Update pull request branch missing?

### ISSUE THREAD

**Issue by bjedrocha** [octokit/octokit.rb#1471]
:wave:

Looking through the REST API docs I noticed that pull requests have a [`update-branch`](https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request-branch) endpoint that will update the pull request branch with the latest upstream changes from the base branch but that this functionality is missing from the Octokit Ruby client. Is this intentional or just an oversight? Would a contribution to add this functionality be welcomed?

**Comment by timrogers** [comment]
👋🏻 A contribution to add this would be most welcome. As much as we'd love to, we don't have full parity with the surface of the REST API - we rely on contributions to get there. 

If you make a PR, I'll review it right away.
