### ISSUE TITLE
TooLargeContent Exception no longer thrown

### ISSUE THREAD

**Issue by goldstar611** [octokit/octokit.rb#1482]
I'm not sure how long this has regressed but our github enterprise (version 3.6.1) instance is delivering the following message inside a Sawyer::Resource

```
Either the raw or object media type must be used for this endpoint for blobs between 1-100 MB. The raw type will return the file contents, and the JSON type will return the file's metadata. Please try again with a valid media type.
```

We can see there's a regex in error.rb#L80 that controls when an exception is raised:
https://github.com/octokit/octokit.rb/blob/15be7251e795044f2bb9537db7c58c95fdd4cbec/lib/octokit/error.rb#L80

This message does not match the regex because the text has changed from
"blobs up to XXX MB"
to
"blobs between X-YYY MB."

The TooLargeContent exception and regex was introduced in PR #1106

**Comment by goldstar611** [comment]
I'm happy to PR this issue with either a non-greedy match like 
`/returns blobs .*? MB/i` 
or update the regex for a stricter match like
`/returns blobs (up to|between) [0-9\-]+ MB/i`

**Comment by timrogers** [comment]
Great spot on this! ✨ It'd be great to have a PR to fix this. I'd go for the stricter regex I think to avoid any surprises.
