### ISSUE TITLE
Client not authorizing when access token is passed

### ISSUE THREAD

**Issue by stevenc-haku** [octokit/octokit.rb#1487]
I am using v4.22.0 and I am trying to initialize an `Octokit::Client` object and pass in the access_token.
The token has both the `repo` and `user` scopes.
```
  client = Octokit::Client.new(access_token: ENV['GITHUB_ACCESS_TOKEN'])
```
However I try to get the user (`client.user`) or try to login (`client.user.login`), it gives me an error.
```
Octokit::Unauthorized: GET https://api.github.com/user: 401 - Requires authentication // See: https://docs.github.com/rest/reference/users#get-the-authenticated-user
```
The issue is not the token because it works when making requests through the CLI. The client seems to be ignoring the token completely. When I make a request for the repositories, it returns only the public repositories even though most of the requested ones are private. 

Has anyone had this issue before? Is this fixed in later versions?

**Comment by timrogers** [comment]
Hi there! 👋🏻 Are you sure that your token is present in `ENV['GITHUB_ACCESS_TOKEN`]? That is the most likely cause of this issue.
