### ISSUE TITLE
We've renamed the `4-stable` branch to `main` 🔀

### ISSUE THREAD

**Issue by anhy999** [octokit/octokit.rb#1498]
### Discussed in https://github.com/octokit/octokit.rb/discussions/1455

<div type='discussions-op-text'>

<sup>Originally posted by **timrogers** July 12, 2022</sup>
Hey all 👋🏻 

This is a heads-up that we've renamed some of the branches on `octokit/octokit.rb` to make it easier for us to evolve the project and make it better and better ✨ 

Until today, our default branch was `4-stable` because the current major version of Octokit was `v4.x`. But we're about to release a new major version, `v5.x`, [dropping support for deprecated Ruby versions](https://github.com/octokit/octokit.rb/pull/1454) 

To avoid having a branch name that refers to an old version, we've now renamed the `4-stable` branch to `main`. Open pull requests pointing to the `4-stable` branch have automatically been moved to target the new default branch.

If you've already cloned `octokit.rb` locally, you can run the following commands in your shell so your local repository understands the new repository structure.

```sh
git branch -m 4-stable main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

There was also a `5-alpha` branch which contained some two-year old experimental code aiming to shift the package to be auto-generated from [GitHub's OpenAPI specification](https://github.com/github/rest-api-description). We've renamed that branch to `next-alpha`.</div>

**Comment by kfcampbell** [comment]
@anhy999 are there questions you have about #1455 you'd like to address in this issue?
