### ISSUE TITLE
Unable to access repository webhooks

### ISSUE THREAD

**Issue by fillipeppalhares** [octokit/octokit.rb#1534]
Greetings, sorry to bother with such a simple question, but I'm having troubles to interact with repository webhooks from the org that I'm a member. I set up a fine grained personal access token with the right permissions and my org as resource owner, but when I try to make some requests I'm receiving error 403. Couldn't find a way out.

![image](https://user-images.githubusercontent.com/55896823/214669424-51699b19-2ebb-4074-ae75-8a2fa9a685c4.png)

Can someone give me a hand? Thank you in advance.

**Comment by kfcampbell** [comment]
Closing this issue due to lack of recent response, though please feel free to reopen if it's warranted.
