### ISSUE TITLE
[FEAT]: Environments API

### ISSUE THREAD

**Issue by jer-k** [octokit/octokit.rb#1552]
### Describe the need

https://docs.github.com/en/rest/deployments/environments

Add the ability to create, list, update, and destroy environment objects.

I'm currently able to perform actions on Deployment objects, but I found that Octokit isn't currently exposing the environments API. Is there any reason to not expose this API?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @jer-k, thanks for dropping this out here. ❤️   Is this something that you'd be interested in taking a stab at and putting together a PR for? I am going to put an "up for grabs" on it and put it in our backlog on this but feel free to pick up if you have time/want to.

**Comment by jer-k** [comment]
I can definitely implement this. I just wanted to make sure there wasn't any reason it hadn't been done.
