### ISSUE TITLE
[BUG]: Octokit.rb exceptions leak api_key and secret settings

### ISSUE THREAD

**Issue by tibbes** [octokit/octokit.rb#1559]
### What happened?

Yesterday, I noticed that a routine operation failed whilst updating a GHES instance's settings using the management console API. The operation was triggered using Octokit.rb (in particular `ManagementConsole.edit_settings`).

The failure was not Octokit's fault, but I noticed that the Octokit.rb exception logged the full URL of the request, which included:
- the **unredacted `api_key`** for the management console
- the settings, which were passed as URL query parameters

As the call was changing the `github_ssl` settings, the query parameters included the unredacted HTTPS certificate and **private key**.

I would expect that management console settings and the `api_key` would be sent in the body of the request, not as query parameters, and that anything sensitive sent as query parameters is properly redacted in exceptions.

### Versions

I noticed the problem with Octokit.rb 4.21.0, but I've reproduced with 4.25.1.

I reproduced with the following code:
```ruby
require "octokit"

client = Octokit::EnterpriseManagementConsoleClient.new(
  management_console_endpoint: "http://127.0.0.1:8989",
  management_console_password: "    THIS IS A SECRET    ",
)

client.edit_settings({
  subdomain_isolation: true,
  github_ssl: {
    enabled: true,
    cert: "certificate",
    key: "    THIS IS A SECRET AS WELL    "
  }
})
```

And I ensured that an exception occurred by the use of `http://127.0.0.1:8989`, which on my box is a listening HTTP server, but _not_ GHES, so I was guaranteed a 404 response.

The log output is pasted below.

### Relevant log output

```shell
/home/me/repro/vendor/bundle/ruby/2.6.0/gems/octokit-4.25.1/lib/octokit/response/raise_error.rb:14:in `on_complete': PUT http://127.0.0.1:8989/setup/api/settings?api_key=++++THIS+IS+A+SECRET++++&settings=%7B%22subdomain_isolation%22%3Atrue%2C%22github_ssl%22%3A%7B%22enabled%22%3Atrue%2C%22cert%22%3A%22certificate%22%2C%22key%22%3A%22++++THIS+IS+A+SECRET+AS+WELL++++%22%7D%7D: 404 -  (Octokit::NotFound)
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/faraday-2.7.4/lib/faraday/middleware.rb:18:in `block in call'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/faraday-2.7.4/lib/faraday/response.rb:42:in `on_complete'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/faraday-2.7.4/lib/faraday/middleware.rb:17:in `call'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/octokit-4.25.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/octokit-4.25.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/faraday-2.7.4/lib/faraday/rack_builder.rb:153:in `build_response'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/faraday-2.7.4/lib/faraday/connection.rb:444:in `run_request'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/faraday-2.7.4/lib/faraday/connection.rb:280:in `put'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/octokit-4.25.1/lib/octokit/connection.rb:156:in `request'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/octokit-4.25.1/lib/octokit/connection.rb:37:in `put'
	from /home/me/repro/vendor/bundle/ruby/2.6.0/gems/octokit-4.25.1/lib/octokit/enterprise_management_console_client/management_console.rb:72:in `edit_settings'
	from ./repro.rb:8:in `<main>'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @tibbes thank you for reaching out about this.  We will want to redact the sensitive data from the stack trace in these exceptions.  We do that in other [places](https://github.com/octokit/octokit.rb/blob/046cf8853d6ae695d373cda12a8feed8814084b1/lib/octokit/error.rb) in the SDK I am not sure how this [one](https://github.com/octokit/octokit.rb/blob/main/lib/octokit/response/raise_error.rb) was missed but apologies for the trouble and thank you for letting us know ❤️. 

We plan on getting to this quickly, but please feel free to fix it if you have the time - we'll approve it and release it as soon as possible.
