### ISSUE TITLE
[FEAT]: Add support line property to create_pull_request_comment

### ISSUE THREAD

**Issue by tick-taku** [octokit/octokit.rb#1565]
### Describe the need

Hi🙋

I want to post a multiline comment using `create_pull_request_comment`, but it seems like I need to use 'line' instead of 'position'. [The API reference](https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-comment) mentions that 'position' is deprecated and recommends using 'line' instead. Do you know if there are any plans to support this change? If I missed something, I apologize.

### API Version

2022-11-28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
We're not keeping it `position` intentionally! We'd be accepting of PRs to update the call.

**Comment by tick-taku** [comment]
Got it!
I'll give it a try.💪
