### ISSUE TITLE
[BUG]: `check_runs_for_check_suite` generates invalid path if a repo string is passed in

### ISSUE THREAD

**Issue by zrdaley** [octokit/octokit.rb#1574]
### What happened?

`check_runs_for_check_suite` accepts a repo name or id and then renders it to an API url using the [path helper](https://github.com/octokit/octokit.rb/blob/d5eec6e8db61b7548e0235b84414e8ffa272a5b2/lib/octokit/repository.rb#L49):

1. Repo name case ❌ :
    - result: `repos/:repo_nwo/check-suites/:check_suite_id/check-runs`
    - [expected](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#get-a-check-run): `/repos/{owner}/{repo}/check-runs/{check_run_id}`
2. Repo ID case ✅ :
    - result: `repositories/:repo_id/check-suites/:check_suite_id/check-runs`
    - expected: same as above

### Versions

`gem "octokit", "~> 4.18.0"`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DeepakRaj228** [comment]
Hi @nickfloyd and @zrdaley - I'm sorry, but I had difficulty understanding. Could you kindly clarify or provide more information? can you kindly explain what should be the expected one with the example?

I got values for both the endpoints which is mentioned 
```
Repo name case ❌ :
current: repos/:repo_nwo/check-suites/:check_suite_id/check-runs
expected: /repos/{owner}/{repo}/check-runs/{check_run_id}
```

should it return list of all the check_run_ids from the check_suite from the expected endpoint?

1. current(/check-suites/#{id}/check-runs) behaviour returns details of the check_suites
<img width="1336" alt="Screenshot 2023-12-20 at 11 43 48 PM" src="https://github.com/octokit/octokit.rb/assets/30191223/70a054f2-114a-49ed-9198-4c7077e152f4">

2. Expected path which is mentioned `/check-runs/{check_run_id}` returns details of the check run but, we should pass the check_run_id instrad of check_suite_id
<img width="1119" alt="Screenshot 2023-12-20 at 11 44 02 PM" src="https://github.com/octokit/octokit.rb/assets/30191223/b1d99522-9424-41ad-99b5-ab8b3d03d429">
