### ISSUE TITLE
[DOCS]: Broken link for request-reviewers-for-a-pull-request

### ISSUE THREAD

**Issue by willyamacaroni** [octokit/octokit.rb#1597]
### Describe the need

The link under "see also" is broken for the [request pull request review page](http://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html#request_pull_request_review-instance_method)

Change 
https://developer.github.com/v3/pulls/review_requests/#create-a-review-request 
to
https://developer.github.com/v3/pulls/review_requests/#request-reviewers-for-a-pull-request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by willyamacaroni** [comment]
I've submitted a PR for review here: https://github.com/octokit/octokit.rb/pull/1598

**Comment by kfcampbell** [comment]
Closed via #1598.
