### ISSUE TITLE
[FEAT]: add missing endpoints

### ISSUE THREAD

**Issue by wJoenn** [octokit/octokit.rb#1633]
### Describe the need

Hey
I've noticed some endpoints are missing from Octokit, specifically I've had a need to [list](https://docs.github.com/en/free-pro-team@latest/rest/reactions/reactions?apiVersion=2022-11-28#list-reactions-for-a-release), [create](https://docs.github.com/en/free-pro-team@latest/rest/reactions/reactions?apiVersion=2022-11-28#create-reaction-for-a-release) and [delete](https://docs.github.com/en/free-pro-team@latest/rest/reactions/reactions?apiVersion=2022-11-28#delete-a-release-reaction) a release's reactions.

From what I can see it should be as easy as adding this to [client/reactions.rb](https://github.com/octokit/octokit.rb/blob/main/lib/octokit/client/reactions.rb) and throw in a couple tests which I'd be willing to do if you're open to the idea.
```ruby
module Octokit
  class Client
    module Reactions
      # List reactions for a release
      #
      # @param repo [Integer, String, Hash, Repository] A GitHub repository
      # @param id [Integer] The Release id
      #
      # @see https://docs.github.com/en/free-pro-team@latest/rest/reactions/reactions?apiVersion=2022-11-28#list-reactions-for-a-release
      #
      # @example
      #   @client.release_reactions("octokit/octokit.rb", 1)
      #
      # @return [Array<Sawyer::Resource>] Array of Hashes representing the reactions.
      def release_reactions(repo, id, options = {})
        get "#{Repository.path repo}/releases/#{id}/reactions", options
      end

      # Create reaction for a release
      #
      # @param repo [Integer, String, Hash, Repository] A GitHub repository
      # @param id [Integer] The Release id
      # @param reaction [String] The Reaction
      #
      # @see https://docs.github.com/en/free-pro-team@latest/rest/reactions/reactions?apiVersion=2022-11-28#create-reaction-for-a-release
      # @see https://developer.github.com/v3/reactions/#reaction-types
      #
      # @example
      #   @client.create_release_reaction("octokit/octokit.rb", 1)
      #
      # @return [<Sawyer::Resource>] Hash representing the reaction.
      def create_release_reaction(repo, id, reaction, options = {})
        options = options.merge(content: reaction)
        post "#{Repository.path repo}/releases/#{id}/reactions", options
      end

      # Delete a reaction for a release
      #
      # @param repo [Integer, String, Hash, Repository] A GitHub repository
      # @param issue_id [Integer] The Release id
      # @param reaction_id [Integer] The Reaction id
      #
      # @see https://docs.github.com/en/free-pro-team@latest/rest/reactions/reactions?apiVersion=2022-11-28#delete-a-release-reaction
      #
      # @example
      #   @client.delete_release_reaction("octokit/octokit.rb", 1, 2)
      #
      # @return [Boolean] Return true if reaction was deleted, false otherwise.
      def delete_release_reaction(repo, release_id, reaction_id, options = {})
        boolean_from_response :delete, "#{Repository.path repo}/releases/#{release_id}/reactions/#{reaction_id}", options
      end
    end
  end
end
```

### API Version

2022-11-28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey thank you for highlighting these missing APIs.  You are correct, until we can get to generative SDKs, the SDKs have to be added manually.

I am going to assign the labels `hacktoberfest` and `Up for Grabs` to signal to the community that this is something that has been verified and can be worked. It looks like you'd be up for this so please feel free to pick the issue up! Thank you again for all that you do for this community :heart: !

**Comment by wJoenn** [comment]
I would really like to but it seems I can't make the test script work 🤔 
I get `Octokit::Unauthorized: POST https://api.github.com/user/repos: 401 - Bad credentials` despite doing
```bash
script/bootstrap
export OCTOKIT_TEST_GITHUB_TOKEN=...
export OCTOKIT_TEST_GITHUB_LOGIN=wJoenn
export OCTOKIT_TEST_GITHUB_PASSWORD=...
script/test
```

If you wouldn't mind taking some time to tell me what I could be missing I'd really appreciate it @nickfloyd 🙏
