### ISSUE TITLE
[BUG]: HTTP caching middleware returns cached responses to wrong users

### ISSUE THREAD

**Issue by DimitriosLisenko** [octokit/octokit.rb#1660]
### What happened?

In version 4.22.0 (**and onwards**), `http.authorization 'Bearer', @bearer_token` (which immediately sets the `Authorization` header) was changed to `http.request :authorization, 'Bearer', @bearer_token`, which instead adds the `Faraday::Request::Authorization` to the middleware chain, which sets the `Authorization` header when called.

Since the authorization middleware is added at the point of the request, while the caching middleware is added on Faraday initialization (as suggested in the README), it means that the HTTP caching middleware runs first, and the authorization middleware runs second.

This means that when the caching middleware runs, it does not have the `Authorization` header set, and therefore caches requests and then returns them without having the ability to know that these requests are for different users.

For example, `GET /user/installations?per_page=100` should return different results for different users, but with the HTTP caching enabled, it does not.

I have a PR that fixes the issue here: https://github.com/octokit/octokit.rb/pull/1661/files. Open to other approaches as well.

### Versions

Octokit v8.0.0, Ruby v3.2.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @DimitriosLisenko, great catch! Thanks for tracking this down. Let us know if you'd be interested in fixing the issue and submitting a PR.  For now I have labeled this as "Up For Grabs" so that the community can take a stab at getting this fixed as well. ❤️

**Comment by DimitriosLisenko** [comment]
Hey @nickfloyd! I have already submitted a PR at https://github.com/octokit/octokit.rb/pull/1661/files :)

**Comment by nickfloyd** [comment]
> Hey [@nickfloyd](https://github.com/nickfloyd)! I have already submitted a PR at https://github.com/octokit/octokit.rb/pull/1661/files :)

Oof, sorry about that I completely missed that.  Thank you for the follow up and the contributions! We'll have a look shortly! ❤

**Comment by nickfloyd** [comment]
Thanks for the ping and the changes.  I've merged the changeset and will get it released soon.

**Comment by DimitriosLisenko** [comment]
Thank you! :)

**Comment by alistairfairweather** [comment]
@DimitriosLisenko most handsomest contributor of week
