### ISSUE TITLE
[MAINT]: Rename `find_app_installations` to `list_app_installations`

### ISSUE THREAD

**Issue by pbstriker38** [octokit/octokit.rb#1718]
### Describe the need

All the other index endpoints start with `list_`. I always need to come and search the code to figure out the name of this one.

This is also referred to as `listing` installations in the API documentation.

https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installations-for-the-authenticated-app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Perhaps we could alias that function for now to avoid a breaking change, and remove `find_app_installations` in a future release.

**Comment by pbstriker38** [comment]
That sounds good to me

**Comment by pbstriker38** [comment]
@kfcampbell Would you like me to open a PR for that?

**Comment by kfcampbell** [comment]
If you have the time and inclination, that would be wonderful!

**Comment by pbstriker38** [comment]
@kfcampbell 
As I was working on the alias I noticed that the apps endpoint have a few deprecations that have existed since `v4.8.0`. These should probably be removed by now since it will be odd that a deprecated method points to another method that could also become deprecated soon.

There's actually a few deprecated methods that have existed since integrations was renamed to apps.

https://github.com/octokit/octokit.rb/blob/v9.2.0/lib/octokit/client/apps.rb#L30
https://github.com/octokit/octokit.rb/releases/tag/v4.8.0
