### ISSUE TITLE
Handle pagination of results

### ISSUE THREAD

**Issue by walquis** [octokit/octokit.rb#255]
It would be great if the client could abstract away the pagination headaches, a la https://github.com/jwilger/github-v3-api.  The current version only returns the first 100 repos, 

The only way to get all the results is to parse the "Link" header for the "since" arg, and pass it to the next request, etc., stringing results together until there are no more "Link" headers with "since" args.

**Comment by Dorian** [comment]
Doesn't work with on the organization's members API for instance, e.g.:

```
>> Octokit.org('google').rels[:public_members].get.data.size
=> 30
>> Octokit.auto_paginate = true
=> true
>> Octokit.org('google').rels[:public_members].get.data.size
=> 30
```

**Comment by AnriKoul** [comment]
>> Octokit.auto_paginate = true
