### ISSUE TITLE
Accessing private repositories seems to be broken, keep getting an Octokit::NotFound exception

### ISSUE THREAD

**Issue by devmyndstatus** [octokit/octokit.rb#280]
When I try to access a private repository I get a 404 and an Octokit::NotFound error.  This is what I'm attempting to do:

``` ruby
client = Octokit::Client.new(login: github_username, password: github_password)
    self.issue_count = client.list_issues("devmynd/radiate").count
```

And here is what's returned:

```
Octokit::NotFound: GET https://api.github.com/repos/devmynd/radiate: 404: Not Found
from /Users/jcgrubbs/.gem/ruby/2.0.0/gems/octokit-1.25.0/lib/faraday/response/raise_octokit_error.rb:22:in `on_complete'
```

The odd thing is that this was working with this exact code yesterday.  Was there a change to the Github API that caused this breakage?  Also, when I try this with a public repository it works like a charm - that could be a red herring, but I thought I'd mention it.

**Comment by gbaudry303** [comment]
I am getting this same issue, doing a curl request works fine, but with octokit, using a token that has the [read:org] scope, I still get 404: Not Found for private repos. Any help on fixing this?

**Comment by pengwynn** [comment]
@gbaudry303 The `read:org` scope only provides [read-only access to organization, team, and membership resources][scopes], not repositories. If you'll hit us up [at support][support] with your curl output, we'd be happy to help troubleshoot.

[scopes]: https://developer.github.com/v3/oauth/#scopes
[support]: https://github.com/contact?form%5Bsubject%5D=API+help,+please

**Comment by irace** [comment]
I’m still seeing this same behavior. The token works fine when using it via `curl`, but octokit.rb returns 404s for all private repositories. Please advise.

**Comment by dmil** [comment]
+1

**Comment by toby5box** [comment]
I'm also having this problem, using a personal access token to a private repo, but I suspect it's the set of permissions I've granted? I've only allowed **repo_deployment**.

**Comment by gabrieljoelc** [comment]
Trying to run this:
```ruby
client.search_issues('org:foo assignee:humanperson1 is:private')
```

I selected each one progressively, reauthenticating each time, for all of the `repo` scopes and didn't get results until I checked `repo` (Full control of private repositories).
