### ISSUE TITLE
client looses application authentication when calling Client#root

### ISSUE THREAD

**Issue by rmetzler** [octokit/octokit.rb#337]
When I set up application authentication with github_client_id and github_client_secret, Octokit is authenticated. As soon as I call [Octokit::Client#root](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client.rb#L219), the client becomes unauthenticated.

Test:

``` ruby

client = Octokit::Client.new \
      :client_id     => Settings.github_client_id,
      :client_secret => Settings.github_client_secret

puts "client authenticated #{ !! client.application_authenticated?}"

root = client.root

puts "client authenticated #{ !! client.application_authenticated?}"
```

I think, the problem is in [Client#agent](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client.rb#L208) which handles basic and token authentication but not application authentication.

I tried to fix the problem or to find a workaround, but couldn't fix it in the last 30min.

**Comment by kingofrock** [comment]
I'm seeing the same sort of issue while using the github_api gem | https://github.com/peter-murach/github.

I am seeing rate limiting failures that appear to be for IP even with successful application creds. I've got sleeps in my code to try an make sure I'm not exceeding limits, but I'm still getting:

403 API rate limit exceeded for XX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

Is it possible that once you hit the limit, your IP is throttled for some period of time before you can start testing the basic authentication method again?

Also, is there a timeout on the authentication? For example, I authenticate once and then make 4 separate requests with sleeps inbetween. Is there a period after which you need to authenticate again?

**Comment by pengwynn** [comment]
@kingofrock If you're seeing an IP address in the rate limiting error message, it's most probably missing creds. (Incorrect creds would give you a `401`)

Can you share your `X-GitHub-Request-Id` from the response headers and I can do some digging server-side?

**Comment by kingofrock** [comment]
Thanks Wynn, The more current ID is: 43B68A92:2023:602E13:54CD6888
