### ISSUE TITLE
Search code required attributes

### ISSUE THREAD

**Issue by joeyw** [octokit/octokit.rb#380]
I am trying to perform a [code search for "gem octokit"](https://github.com/search?q=gem+octokit&type=Code) but a raised error states "Must include at least one user, organization, or repository" and unless I am blind or overlooked it, [the API docs](http://developer.github.com/v3/search/#search-code) don't indicate any requirement. 

``` irb
irb(main):012:0> Octokit.search_code 'gem octokit'
Octokit::UnprocessableEntity: GET https://api.github.com/search/code?q=gem+octokit: 422 - Validation Failed
Error summary:
  message: Must include at least one user, organization, or repository
  resource: Search
  field: q
  code: invalid // See: http://developer.github.com/v3/search/#search-code
```

Is this a user error, oversight in the docs or just not possible to perform the same search with the api?

**Comment by amueller** [comment]
Still not clear from the documentation:
https://developer.github.com/v3/search/#search-code

Also: the worst feature ever. Now I have to write a scraper for the web search. That clearly decreases the load on your servers, right?

**Comment by daattali** [comment]
I 100% agree with @amueller , I'm also resorting to scraping the github website search results because of this rule (that isn't documented anywhere except for in an old blog post).  I'm pretty sure it DOES decrease their  server load because most people would be too lazy to write a scraper, so it still works from their perspective..

**Comment by amueller** [comment]
(yeah I know, it probably does decrease the server load. Unless someone open sources their scraper and gives it a nice API ;)
