### ISSUE TITLE
Auto-paginating user.rels

### ISSUE THREAD

**Issue by ColemanGariety** [octokit/octokit.rb#404]
I'm trying to automatically paginate a user's starred repos.

I'm doing the following:

```
client = Octokit::Client.new netrc: true, auto_paginate: true
client.user.rels[:starred].get.data.each do |repo|
  # logic here
end
```

But it only returns the most recently starred repos, not all of them. Am I using `auto_paginate` incorrectly?

**Comment by Nakilon** [comment]
> `client.starred(client.user.login)`

What the magic is that?
