### ISSUE TITLE
Parsing hook payloads

### ISSUE THREAD

**Issue by passcod** [octokit/octokit.rb#453]
I'd like to be able to give Octokit an event name (e.g. `pull_request`, `status`, `push` etc) and the JSON string received from a hook, and have it parse the data and return an Octokit object.

The rationale is that I'm implementing a service that is hooked up, but I'd like to avoid doing my own potentially buggy parsing and processing of the data I get back.
- Is this already possible?
- If it's not, do you think it could be done? I'm open to coding it up, but I'd need some guidance.

**Comment by sdorunga1** [comment]
I know this is quite a bit later but this definitely gets my :+1: I suppose this functionality doesn't have to be in this gem per se, but I would find it quite useful for parsing the webhook payloads.

It would definitely save time figuring out where everything is and building my own wrappers around the response.

**Comment by JeanMertz** [comment]
more than quite a bit later, but another 👍 from me 😉

**Comment by iangreenleaf** [comment]
The meat of this request was implemented in octokit/octokit.rb#567 🎉
