### ISSUE TITLE
Creating a pull request using Octokit fails

### ISSUE THREAD

**Issue by AdrienGiboire** [octokit/octokit.rb#510]
I develop the `git-pulls` gem. Sources are available here: https://github.com/schacon/git-pulls/

This is to say that everything is working fine. But yesterday, I started working on a new feature. I want to allow user to open/close pull requests using the gem.

Here is what I currently have:

```ruby
      def open
        while arg = @args.shift
          case arg
          when '-t'
            title = @args.shift
          when '-m'
            description = @args.shift
          end
        end
    
        head = File.read(File.join(GIT_PATH.call, '/HEAD')).sub!('ref: ', '')
        base = "refs/remotes/#{GIT_REMOTE}/master"
    
        url_memo = Hash.new { |h,k| h[k]=[] }
        git('remote -v').to_s.split("\n").map do |line|
          next if line !~ /^(.+?)\t(.+) \(/
          name, url = $1, $2
          url_memo[name] << url
        end
        url = url_memo[GIT_REMOTE].uniq[0]
        if url
          repo = url.scan(/^git@github.com:(.+)\.git/)[0][0]
    
          Octokit.create_pull_request(repo, base, head, title, description)
        end
      end
```

For some reasons, the PR creation doesn't work. I keep getting this error:

    $ ./bin/git-pulls open -t "Fake PR" -m "Fake PR description"

    /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/schacon/git-pulls/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client.rb:144:in `post'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit/client/pull_requests.rb:66:in `create_pull_request'
        from /Users/Adrien/.gem/ruby/2.1.2/gems/octokit-3.3.1/lib/octokit.rb:27:in `method_missing'
        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:184:in `open'
        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:34:in `run'
        from /Users/Adrien/code/git-pulls/lib/git-pulls.rb:21:in `start'
        from ./bin/git-pulls:6:in `<main>'

Yet, https://api.github.com/repos/schacon/git-pulls/pulls exists and according to the [documentation](https://developer.github.com/v3/pulls/#create-a-pull-request) it doesn't seem to be violating any rules.

Currently running:

* Ruby 2.1.2
* Octokit 3.3.1

Parameters sent to the `Octokit#create_pull_request` in this example are:

* `repo` equals `schacon/git-pulls`
* `base` equals `refs/remotes/origin/master`
* `head` equals `refs/heads/feature/open_close_commands`
* `title` equals `Fake PR`
* `description` equals `Fake PR description`

Any hints?

**Comment by simtel12** [comment]
I'm having the same issue - though I'm just trying to list the existing pull requests in a repository.  I'm using username/password authentication (so that it can more readily match curl) and the curl command for the same URL works just peachily.

```ruby
require "octokit"

client = Octokit::Client.new(:login => "simtel12", :password => "REDACTED")

user = client.user
user.login


puts "Trying ouya/docs - public repo"
puts Octokit.pull_requests("ouya/docs").inspect
puts "Trying ouya/UnrealEngine - private repo"
puts Octokit.pull_requests("ouya/UnrealEngine").inspect
```

Results in:
```
Trying ouya/docs - public repo
[]
Trying ouya/UnrealEngine - private repo
/Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/octokit-3.7.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/ouya/UnrealEngine/pulls: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/response.rb:9:in `block in call'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/response.rb:63:in `on_complete'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/response.rb:8:in `call'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/connection.rb:106:in `get'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/octokit-3.7.0/lib/octokit/client.rb:339:in `request'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/octokit-3.7.0/lib/octokit/client.rb:200:in `paginate'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/octokit-3.7.0/lib/octokit/client/pull_requests.rb:32:in `pull_requests'
	from /Users/gleach/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/octokit-3.7.0/lib/octokit.rb:27:in `method_missing'
	from test.rb:23:in `<main>'
```

The curl version:
```
curl --user "simtel12:REDACTED" https://api.github.com/repos/ouya/UnrealEngine/pulls
[

]
curl --user "simtel12:REDACTED" https://api.github.com/repos/ouya/docs/pulls
[

]
```

It appears that the Octokit.pulls call isn't able to access private repos for some reason, even though the actual https GET api exists and functions as documented.

Thoughts?  Am I missing something?

**Comment by joeyw** [comment]
@simtel12 You are not making the call with the Octokit client that you created with your credentials. 

Octokit creates a default unauthenticated client when you call `Octokit.some_method`. Change your call to `client.pull_requests("ouya/UnrealEngine").inspect` and you will get the desired results.

If you want to configure the default client you can do so with a block:

```ruby
Octokit.configure do |c|
  c.login = 'defunkt'
  c.password = 'c0d3b4ssssss!'
end
```

Then your calls would work in this case.

**Comment by simtel12** [comment]
That.... makes a lot of sense and I feel bad that I didn't notice it.  Thanks!
