### ISSUE TITLE
`list_issues` with multiple labels returns no records

### ISSUE THREAD

**Issue by bjacobel** [octokit/octokit.rb#525]
Reproduction steps:
- Create an issue on a public repository
- Add two labels to it, e.g., `bug` and `question`
- Create an octokit client:

```
> @github = Octokit::Client.new :access_token => github_access_token
```
- Verify that the issue can be found from either of its labels:

```
> @github.list_issues("bjacobel/.dotfiles").count
=> 1

> @github.list_issues("bjacobel/.dotfiles", {:labels => "bug"}).count
=> 1

> @github.list_issues("bjacobel/.dotfiles", {:labels => "question"}).count
=> 1

> @github.list_issues("bjacobel/.dotfiles", {:labels => "question"})[0].id == @github.list_issues("bjacobel/.dotfiles", {:labels => "bug"})[0].id
=> true
```
- Try to find the issue by both labels at the same time:

```
@github.list_issues("bjacobel/.dotfiles", {:labels => "bug,question"}).count
=> 0
```

[The docs say that](http://octokit.github.io/octokit.rb/Octokit/Client/Issues.html#list_issues-instance_method) `list_issues` can take a comma separated list of labels, e.g., `bug,ui,@high`. This doesn't seem to be the case for me.

**Comment by buckmaxwell** [comment]
I am using this feature and it works -- kind of.  I have prioritized issues and would like to fetch items that are 'high' or 'medium'. If I do 'high,medium' I get only issues with both labels.  Any way to use or instead of and?  I can't find a way to perform this request in a simple way.
