### ISSUE TITLE
User's starred repos

### ISSUE THREAD

**Issue by Chigurh** [octokit/octokit.rb#551]
According to the pull request: #137, ```user.starred``` should give me the user's starred repo's.
I run the following lines of code:
```
client = Octokit::Client.new(:access_token => access_token)
user = client.user
user.starred
```
But ```user.starred``` only gives me nil when i print ```user.starred.class```. To be more specific, it gives me ```NilClass```.

I am sure that the user the access token belongs to has starred multiple repos.

I noticed that the pull request is quite old and that there isn't any information about starring, listing starred och unstaring in the documentation (or i couldn't find it). I can't find any starred method in the code (using the search). Does this feature still exists?

**Comment by Chigurh** [comment]
Started looking in [users.rb](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/users.rb#L165-L178) and saw the method comments/description.

Works just fine when i run the following instead:
```
client = Octokit::Client.new(:access_token => access_token)
user = client.user

starred_repos = Octokit.starred(user.login)
```

**Comment by pengwynn** [comment]
@Chigurh you can simplify that a bit:

```ruby
client = Octokit::Client.new(:access_token => access_token)
client.starred
```

The [philosophy][] behind Octokit's design is to wrap the API in an idiomatic way. Responses are pretty basic value objects. All of the methods that call API methods happen on the `Client` object, not on responses.

[philosophy]: https://github.com/octokit/octokit.rb#philosophy

**Comment by Chigurh** [comment]
Thanks @pengwynn. Kind of understood that once i realised that ```client.user``` only gives me some sort of hash-like key value object (Sawyer::Resource), that is the actual response. :smile: 

Love this lib. :+1:
