### ISSUE TITLE
Changing auto_paginate on Octokit doesn't affect current instances

### ISSUE THREAD

**Issue by sb8244** [octokit/octokit.rb#554]
If you have a client instance, then change `Octokit.auto_paginate`, it doesn't affect the current client instance. Changing `client.auto_paginate` does have the correct effect, of course. It's not really a bug so much as it is confusing

**Comment by pengwynn** [comment]
@sb8244 Yeah, that's pretty much by design. Sorry you found that confusing. We'd welcome a patch to updated [that section of the README][readme] to make that a bit clearer.

[readme]: https://github.com/octokit/octokit.rb#configuration-and-defaults

**Comment by sb8244** [comment]
Awesome I will do that! I ended up writing a little client extension with a method of

```ruby
def with_pagination
    self.auto_paginate = true
    yield
  ensure
    self.auto_paginate = false
  end
```

This way I could pass a `GithubClient` (my simple extension of `Octokit::Client`) around my application without having to create a new one every time. I'm not sure if this API interface is welcome or not (and it's fine either way), but I did find it useful / explicit which was nice.

**Comment by sb8244** [comment]
Love the library by the way! Thanks Wynn and other contributors!

**Comment by pengwynn** [comment]
@sb8244 That's pretty nifty. I'd be more inclined to let it ensure the pagination setting without inadvertently flipping the setting, surprising other callers. What about:

```ruby
def with_pagination
  pagination_setting = self.auto_paginate 
  self.auto_paginate = true
  yield
ensure
  self.auto_paginate = pagination_setting
end
```

Maybe we could even bake this into the `auto_paginate` method itself, yielding if a block is given, setting the value if there's no block?

**Comment by sb8244** [comment]
Good call there! Do you mind if I tackle a simple implementation and tests?

On Saturday, January 31, 2015, Wynn Netherland <notifications@github.com>
wrote:

> @sb8244 <https://github.com/sb8244> That's pretty nifty. I'd be more
> inclined to let it ensure the pagination setting without inadvertently
> flipping the setting, surprising other callers. What about:
>
> def with_pagination
>   pagination_setting = self.auto_paginate
>   self.auto_paginate = true
>   yieldensure
>   self.auto_paginate = pagination_settingend
>
> Maybe we could even bake this into the auto_paginate method itself,
> yielding if a block is given, setting the value if there's no block?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/octokit/octokit.rb/issues/554#issuecomment-72337218>.
>


-- 


  Steve Bussey •SalesLoft

•Software Engineer

e steve.bussey@salesloft.com w salesloft.com
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

a 3423 Piedmont Rd NE, Atlanta, GA 30305

[image: Facebook] <https://www.facebook.com/SalesLoft> [image: Twitter]
<https://twitter.com/SalesLoft> [image: Linkedin]
<https://www.linkedin.com/company/salesloft> [image: wordpress]
<http://blog.salesloft.com/blog/> [image:
http://salesloft.com/prospector/#video]
<http://salesloft.com/prospector/#video>  [image: Software Engineer Logo]
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

**Comment by pengwynn** [comment]
@sb8244 nope, go for it!

**Comment by tommy2269** [comment]
Call me 203 8602 I'm not mad or anything this one. Try to kick me out of here unblock me what is this with your wife

**Comment by aruzmeister** [comment]
@pengwynn i have been running into same kind of problem. I have enabled auto_paginate which is not able to paginate means it couldn't display for what i ask for?

**Comment by pengwynn** [comment]
@aruzmeister can you share a code snippet to see if you're running into the same issue as the original topic here?

**Comment by aruzmeister** [comment]
@pengwynn It's good. auto_paginate works fine the problem was with my server which couldn't get too much request at once. I have already figured out :)

**Comment by sb8244** [comment]
I think github changed something. It's nearly impossible for me to page the
1k prs on a repo. Freezes my console continuously for minutes at a time

On Wednesday, August 12, 2015, Aruj Parajuli <notifications@github.com>
wrote:

> @pengwynn <https://github.com/pengwynn> It's good. auto_paginate works
> fine the problem was with my server which couldn't get too much request at
> once. I have already figured out :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/octokit/octokit.rb/issues/554#issuecomment-130467042>.
>


-- 


  Steve Bussey •SalesLoft

•Software Engineer

e steve.bussey@salesloft.com w salesloft.com
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

a 3423 Piedmont Rd NE, Atlanta, GA 30305

[image: Facebook] <https://www.facebook.com/SalesLoft> [image: Twitter]
<https://twitter.com/SalesLoft> [image: Linkedin]
<https://www.linkedin.com/company/salesloft> [image: wordpress]
<http://blog.salesloft.com/blog/> [image:
http://salesloft.com/prospector/#video]
<http://salesloft.com/prospector/#video>  [image: Software Engineer Logo]
<http://salesloft.com/?v=1&utm_expid=76406993-1.E5ncJhwyTAW9uGaR1WdBTA.1?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

**Comment by aruzmeister** [comment]
@sb8244 I think so you can configure that by increasing the incoming limit so that it won't freezes.

**Comment by pyaephyoswe** [comment]
Better ' Good.
pyaephyoswe569@gmail.com

**Comment by PhyoWaiMaung92** [comment]
sb8244

**Comment by PhyoWaiMaung92** [comment]
#554
