### ISSUE TITLE
Confusing behaviour of create_pull_request_for_issue

### ISSUE THREAD

**Issue by grn** [octokit/octokit.rb#556]
# Problem

Imagine a GitHub repo with two comitters A and B. I run into the following problem:

1. A opened an issue 2 months ago.
2. B creates a PR today using `#create_pull_request_for_issue` for the issue.
3. GitHub lists the PR as created by A not B. The PR's creation date equals to the issue's creation date i.e. 2 months ago instead of today.

My code looks like this:

```ruby
  def submit_pull_request
    octokit.create_pull_request_for_issue('user/repo', 'master', 'feature-branch', issue_id, assignee: 'grn')
  end

  def octokit
    @octokit ||= Octokit::Client.new(
      access_token: 'my GitHub token'
    )
  end

  submit_pull_request
```

# Question

Is this behaviour intentional or am I doing something wrong?

**Comment by pengwynn** [comment]
@grn You're not doing anything wrong. That confusion is one reason why we plan to deprecate that API method.

I recommend just using [`Client#create_pull_request`][cpr] and linking it to the issue in the body with `Fixes #123` or `Refs #123`.

[cpr]: https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/pull_requests.rb#L62-L70
