### ISSUE TITLE
Update_organization argument order incorrect

### ISSUE THREAD

**Issue by ghostlurker** [octokit/octokit.rb#575]
Documentation for this call in the ruby octokit API wrapper indicates you pass in org, then values in a hash, then an optional has to update an org.  The code, however, requires the org, an empty has, the the values hash to properly update an org entry.  This was validated using ocktokit ruby gem 3.8.0 and github enterprise 2.1.3.

**Comment by zqzas** [comment]
@ghostlurker Do you mean this line? 

[def update_organization(org, values, options = {})](https://github.com/octokit/octokit.rb/blob/8de5a8c22ad76891e72f88fffc291a4d15984b7d/lib/octokit/client/organizations.rb#L46)

This funciton requires the org, a values hash, and a optional hash. Any problem with it?

**Comment by ghostlurker** [comment]
Yes,  it actually appears to require (org, {}, values) rather than (org, values, options = {}) <https://github.com/octokit/octokit.rb/blob/8de5a8c22ad76891e72f88fffc291a4d15984b7d/lib/octokit/client/organizations.rb#L46>.
If I provide the org and values hash leaving of the optional hash at the end, the update does not occur (it keeps the original org content/config rather than the change represented in values) .

**Comment by zqzas** [comment]
@ghostlurker Do you mean it would work if the values to be updated are passed in the 3rd parameter `options`?

**Comment by ghostlurker** [comment]
correct

**Comment by zqzas** [comment]
@ghostlurker OK. Let me check it.

**Comment by zqzas** [comment]
@ghostlurker I've tested what you said. You're right. it works only if the desired values are passed in `options`. In the code, the `values` are wrapped in an additional level when calling the `patch`. Let me see if I could fix this.

**Comment by ghostlurker** [comment]
Thanks!

**Comment by ghostlurker** [comment]
Sounds good.  Thanks!

**Comment by pengwynn** [comment]
Closed via https://github.com/octokit/octokit.rb/pull/579.
