### ISSUE TITLE
API returning 404 on call

### ISSUE THREAD

**Issue by luizkowalski** [octokit/octokit.rb#577]
I have this piece of code: `@client.organization_public_members 'github'`where `@client` is `Octokit::Client.new(access_token: @user.access_token)`. 
Turns out that when I try to get public memeber from, for example, gtithub org, I get 404: 
```
@client.organization_public_members 'github'
12:06:29 web.1  | *** Octokit::NotFound Exception: GET https://api.github.com/orgs/github/public_members: 404 - Not Found // See: https://developer.github.com/v3
```
if I paste this url on browser, I get the public member as json without any problem.

Edit: If i try to call the `client` without the access token, the call works

**Comment by pengwynn** [comment]
Hey @luizkowalski. I think this turned out to be a problem with the token and Organization Access Policies, and not Octokit, right? If not, let me know and we'll reopen.

**Comment by luizkowalski** [comment]
Sure, you are right. I sent this to GitHub and they said it was probably a bug...I'll post an update here when they get back to me :)
thanks!
