### ISSUE TITLE
Contents#update_contents not setting the branch properly

### ISSUE THREAD

**Issue by schof** [octokit/octokit.rb#581]
According to the RDoc you're supposed to set the branch as an options param but that parameter is not honored by the API which expects the branch as a "top level" parameter.  Getting a `Octokit::Conflict` as a result since the `sha` I'm passing is not on the master branch.

**Comment by pengwynn** [comment]
@schof Can you share a code snippet or stack trace that would help us troubleshoot?

**Comment by schof** [comment]
I've done some more testing and the problem seems to be related to whether or not the file already exists. Strangely, I can only update if the file already exists.  Here's an example:

```
@client.update_contents(repo, 'VERSION', 'Bumping version', head_sha, version, branch: branch)
```

This works fine if there is no 'VERSION' file on the specified branch.  Once It's been created, I get a the following error the next time I try to update.

```
409 - VERSION does not match 484ab9a881bad27772906b6cb65810b3514318ec // See: https://developer.github.com/v3/repos/contents/ (Octokit::Conflict)
```

The sha referenced in the above error message is exactly the same as the HEAD sha on the remote Github branch where I'm trying to update. IMO, the whole requirement to supply a sha is confusing and API should update the HEAD by default. In any event, I'm assuming if I supply the HEAD sha from the requested branch that should be sufficient but looks like a possible bug here.

**Comment by pengwynn** [comment]
@schof You'll want to send the _blob sha_ that you want to update, not the head sha. If you don't have it locally, you can [fetch it via the API][api].

[api]: https://developer.github.com/v3/repos/contents/#get-contents

**Comment by schof** [comment]
Ok that worked.  Totally confused by the blob sha and how that is different from the sha of the commit and why that would be needed.  Closing this out because it works but I would recommend some type of enhancement to the docs so that one can "click through" and find out what exactly a blob sha is.

Thanks for your quick response.  Love the octokit gem!

**Comment by vivekweb2013** [comment]
> 

Could you please let me know how did you calculated the sha. I'm facing the same issue.

**Comment by vivekweb2013** [comment]
> Ok that worked. Totally confused by the blob sha and how that is different from the sha of the commit and why that would be needed. Closing this out because it works but I would recommend some type of enhancement to the docs so that one can "click through" and find out what exactly a blob sha is.
> 
> Thanks for your quick response. Love the octokit gem!

Could you please let me know how did you generated the sha. I'm facing the same issue

**Comment by jason-jjxy** [comment]
> > Ok that worked. Totally confused by the blob sha and how that is different from the sha of the commit and why that would be needed. Closing this out because it works but I would recommend some type of enhancement to the docs so that one can "click through" and find out what exactly a blob sha is.
> > Thanks for your quick response. Love the octokit gem!
> 
> Could you please let me know how did you generated the sha. I'm facing the same issue

The SHA is generated by completing the following get request on your desired file `GET /repos/{owner}/{repo}/contents/{path} <http://docs.github.com/en/rest/reference/repos#contents>`.
