### ISSUE TITLE
Sha Comparison

### ISSUE THREAD

**Issue by Souldjinn** [octokit/octokit.rb#585]
As a user of octokit, I would like to be able to provide:
sha1 (created two days ago)
sha2 (created today)

And have octokit get the commit history of sha2 and check if sha1 exists in that history. This would allow me to know if sha2 contains the code that sha1 has. 

Is this possible?

**Comment by joeyw** [comment]
You might have a look at the compare method:

http://octokit.github.io/octokit.rb/Octokit/Client/Commits.html#compare-instance_method
https://developer.github.com/v3/repos/commits/#compare-two-commits

**Comment by pengwynn** [comment]
To build on what @joeyw mentioned, you can use that `compare` method and check the `behind_by` value for the resulting comparison object.

```ruby
irb(main):005:0> sha1 = "197f19e66d4c0d4f666da902cc899251d4ceebf3"
=> "197f19e66d4c0d4f666da902cc899251d4ceebf3"
irb(main):006:0> sha2 = "b0cb620d1fc74c33c351d77ad8dfef7da851e920"
=> "b0cb620d1fc74c33c351d77ad8dfef7da851e920"
irb(main):007:0> Octokit.compare("octokit/octokit.rb", sha1, sha2).behind_by
=> 0
```

A `0` means the first sha is included in the second. You can also use ref names instead of shas. I'd entertain a patch to package this up into a `Octokit::Client#contains_ref?` method.

**Comment by Souldjinn** [comment]
Thats wonderful. I'll look into using that. Thanks @pengwynn. I did see the compare method but I had no idea about `behind_by`. 

Just out of curiosity where would I normally look for a method like `behind_by`? Is this an Octokit module method or is it a method specific to compare?

**Comment by pengwynn** [comment]
@Souldjinn: `behind_by` is a field on the resource returned by the Compare API:

https://api.github.com/repos/octokit/octokit.rb/compare/bjfish:master...master

**Comment by Souldjinn** [comment]
Thanks @pengwynn i'm convinced this helped me out.
