### ISSUE TITLE
Question about Organization Memberships API

### ISSUE THREAD

**Issue by tarebyte** [octokit/octokit.rb#590]
Hi There,

I hope this is the right place to ask this question if not I apologize. I'm trying to use the GitHub id of an organization with my personal OAuth token to get the status of my membership in that organization.

Looking at [organization_membership](https://github.com/octokit/octokit.rb/blob/f5f9f2fab804cd2231bd8a33c3a3234504782243/lib/octokit/client/organizations.rb#L543) it looks like this isn't supported as of right now with Octokit.

So I tried to make the API call myself using Postman, the call looks like this:
```
GET /user/memberships/organizations/1800808?access_token=REDACTED HTTP/1.1
Host: api.github.com
Accept: application/vnd.github.moondragon+json
Cache-Control: no-cache
Postman-Token: 08c9cf3b-2fc4-573b-aa7e-ce2353f13044
```

But I get the following response.

```json
{
"message": "Not Found",
"documentation_url": "https://developer.github.com/v3"
}
```

Am I not doing something correct, or is this not supported by the API.

Thanks!

**Comment by pengwynn** [comment]
@tarebyte No problem asking here. 

It appears that method is only routed for name-based paths instead of IDs. I've opened an internal issue for the API team to look into why. Since this isn't an Octokit issue, I'm going to close this, but I'll report back when I know more. :bow:

**Comment by tarebyte** [comment]
Thanks @pengwynn!
