### ISSUE TITLE
Support new authorizations endpoint

### ISSUE THREAD

**Issue by mattbaker** [octokit/octokit.rb#604]
[This](https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app-and-fingerprint) endpoint was introduced [last year](https://developer.github.com/changes/2014-12-08-removing-authorizations-token/). It doesn't look like this is currently supported (please let me know if I missed it)

**Comment by pengwynn** [comment]
Oops, you're totally right. :scream_cat: I think it makes sense to have [`create_authorization`][code] accept a `fingerprint` option and build the path accordingly if present. Care to send over a patch?

[code]: https://github.com/octokit/octokit.rb/blob/update-client-cassettes/lib/octokit/client/authorizations.rb#L61-73

**Comment by mattbaker** [comment]
Glad I wasn't just missing it :) I'll try and find some time to create a PR.

Any idea on the timeline for the next official Octokit release?

**Comment by pengwynn** [comment]
> I'll try and find some time to create a PR.

@mattbaker Thanks.

> Any idea on the timeline for the next official Octokit release?

I'm hoping to write the upgrade guide and release `4.0.0` in the next day or two.
