### ISSUE TITLE
Question about checking if a team manages a repository

### ISSUE THREAD

**Issue by tarebyte** [octokit/octokit.rb#606]
[According to the docs](https://developer.github.com/v3/orgs/teams/#get-team-repo) you can check to see if a team manages a repository.

In theory I should be able to do the same API call with the repo id if I format the request like this
`https://api.github.com/teams/:id/repositories/:id?access_token=token`

I am correct in this line of thinking?

Thanks!

**Comment by pengwynn** [comment]
@tarebyte Your intuition is solid, but alas, those three repository routes nested under `/teams/:id` aren't wired up for id-based paths. I'll link this issue to the internal tracker and we'll follow up when we can fix that.
