### ISSUE TITLE
Branches with slash in their names as SHAs return 404s

### ISSUE THREAD

**Issue by jeromegn** [octokit/octokit.rb#608]
I found that referencing a branch name as a SHA for requests will fail if the branch name has a slash in it.

I've written some failing tests, but I'm not entirely sure where the fix should be applied. Here's the diff: https://github.com/octokit/octokit.rb/compare/master...jeromegn:branch-slash

My understanding is that pretty much everywhere a SHA is accepted, a branch name also is. In the case where the branch has a slash in it, a 404 is returned (correctly):

```ruby
irb(main):002:0> Octokit.tree('bem/bem-tools', 'support/0.9.x')
Octokit::NotFound: GET https://api.github.com/repos/bem/bem-tools/git/trees/support/0.9.x?client_id=bbb6aa3e2e9db58ce884&client_secret=(redacted): 404 - Not Found // See: https://developer.github.com/v3
```

However, if I try to `CGI::escape` the name and provide it to `Octokit#tree`, it double escapes it (could be the HTTP client) and will send the request with the branch as "support%252F0.9.x". Example:

```ruby
irb(main):001:0> Octokit.tree('bem/bem-tools', CGI::escape('support/0.9.x'))
Octokit::NotFound: GET https://api.github.com/repos/bem/bem-tools/git/trees/support%252F0.9.x?client_id=bbb6aa3e2e9db58ce884&client_secret=(redacted): 404 - Not Found // See: https://developer.github.com/v3
```

I've been able to successfully request it from the API from a raw request (not using Octokit) by encoding the slash manually like so: (here, I'm using HTTPie)

```bash
$ http GET https://api.github.com/repos/bem/bem-tools/git/trees/support%2F0.9.x                                                     
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: public, max-age=60, s-maxage=60
Content-Encoding: gzip
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Tue, 16 Jun 2015 01:38:02 GMT
ETag: W/"1f0e637713aca005d74723e698d922ed"
Last-Modified: Fri, 01 May 2015 01:01:04 GMT
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Transfer-Encoding: chunked
Vary: Accept
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-GitHub-Media-Type: github.v3
X-GitHub-Request-Id: 6BB3FFE6:5FD5:83BC1DF:557F7DFA
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 50
X-RateLimit-Reset: 1434420429
X-Served-By: 5aeb3f30c9e3ef6ef7bcbcddfd9a68f7
X-XSS-Protection: 1; mode=block

{
    "sha": "9cac8a1b14c28d6101696e99858b238b4859792d",
    "tree": [
        {
# ...
```

Any idea how we can fix this? I don't mind escaping the branch name myself.

(I've stumbled on this for documentup.com -> https://github.com/jeromegn/DocumentUp)

**Comment by sigmavirus24** [comment]
Nice catch

**Comment by pengwynn** [comment]
Thanks @jeromegn. The fix for this turned out to be server-side. 

https://api.github.com/repos/bem/bem-tools/git/trees/support/0.9.x

**Comment by grosser** [comment]
This still happens to me and is not serverside

%2F works:
https://api.github.com/repositories/602326/git/trees/support%2F0.9.x

but octokit produces %252F which does not work because it means `"52F`
https://api.github.com/repositories/602326/git/trees/support%2252F0.9.x

because it escapes the full path ... which is wrong ...
https://github.com/octokit/octokit.rb/blob/master/lib/octokit/connection.rb#L156

fixed it here with a weird hack https://github.com/zendesk/samson/pull/1885 ... 

@pengwynn please reopen
