### ISSUE TITLE
Passing Octokit.repository? bad arguments returns true

### ISSUE THREAD

**Issue by henare** [octokit/octokit.rb#614]
```
2.0.0-p353 :001 > Octokit.repository?(nil)
 => true 
2.0.0-p353 :002 > Octokit.repository?(false)
 => true 
2.0.0-p353 :003 > Octokit.repository?(true)
 => true 
```

It should return `ArgumentError: Invalid Repository. Use user/repo format.` like it does if you pass `Octokit.repository?("foo")`.

**Comment by pengwynn** [comment]
Nice find. The integer case is legit. It looks like we need an `else` [here][] to catch the others. Care to send over a patch?

[here]: https://github.com/octokit/octokit.rb/blob/07036916bfb42e98a0627616aeabc68582296737/lib/octokit/repository.rb#L29
