### ISSUE TITLE
Ability to manage public keys as an admin

### ISSUE THREAD

**Issue by kylemacey** [octokit/octokit.rb#636]
As documented in https://developer.github.com/v3/users/administration/#list-all-public-keys, it would be nice to be able to view and delete public keys for other users with `Octokit::EnterpriseAdminClient`.

**Comment by gjtorikian** [comment]
Yep! There's a pending PR for this here: https://github.com/octokit/octokit.rb/pull/628

**Comment by kylemacey** [comment]
Whoops, thanks! Forgot to search PRs
