### ISSUE TITLE
Authenticated search call, return just 10 page with 100 per_page 

### ISSUE THREAD

**Issue by lgs** [octokit/octokit.rb#638]
Authenticated search call, return just 100 items but `resp.total_count` is 1122745, while the client is set to `auto_paginate: true`.  Moreover, even shows 30 rate limit but stop at 10 because of not `next page` in the `last_response.rels` ?!?

<pre>
irb(main):016:0> @client = Octokit::Client.new(client_id: ENV['GITHUB_CLIENT_ID'], client_secret: ENV['GITHUB_CLIENT_SECRET'], auto_paginate: true)
irb(main):017:0> resp = @github_client.search_repositories('stars:>1', per_page: 100)     
irb(main):018:0> resp.total_count
=> 1122745
...
irb(main):052:0> last_response.rels
= > { :first= >#<Sawyer::Relation: first: get #< Addressable::Template:0x007fc6cfe71448 > >, :prev = >#< Sawyer::Relation: prev: get #<Addressable::Template:0x007fc6cfe70de0 > >}
irb(main):053:0> @client.rate_limit
= > #< struct Octokit::RateLimit limit=30, remaining=20, resets_at=2015-08-30 17:57:44 +0200, resets_in=0 >
</pre>

**Comment by izuzak** [comment]
As documented [here](https://developer.github.com/v3/search/#about-the-search-api) -- the search API will return up to 1000 results per query. With 100 results per page, that means you can fetch up to 10 pages.

Depending on what exactly you're searching for, you could slice your queries intelligently, get the results for individual slices, and then combine them to get all the results. For example, if you're searching repositories, you could slice the query based on [when the repository was created](https://help.github.com/articles/searching-repositories/#search-based-on-when-a-repository-was-created-or-last-updated) using a [time slice](https://help.github.com/articles/search-syntax/#query-for-values-between-a-range).

**Comment by lgs** [comment]
@izuzak   ok thank you, 
I'm gonna try something like you suggested.
