### ISSUE TITLE
CHANGELOG?

### ISSUE THREAD

**Issue by iainbeeston** [octokit/octokit.rb#639]
Should Octokit have a CHANGELOG file? Or should issues be attached to a milestone?

I've just noticed that Octokit 4.1 has been released, and I'm unsure (other than by taking a diff in github between the 4.0 tag and the 4.1 tag) what changes have been introduced. Normally I would look in the CHANGELOG for a project.

**Comment by gjtorikian** [comment]
The releases page serves as the changelog: https://github.com/octokit/octokit.rb/releases

**Comment by iainbeeston** [comment]
Great, thanks for pointing that out. I always struggle to distinguish between git tags, github releases and github milestones.

Would you mind if I added that information to the readme? (Perhaps under [versioning](https://github.com/octokit/octokit.rb#versioning))

**Comment by gjtorikian** [comment]
Go for it! I'd be very delighted for it.

**Comment by Ladiijae** [comment]
Of course any more problems  support team https://github.com/octokit/octokit.rb/support
