### ISSUE TITLE
Pass additional headers into Octokit::Client::Authorizations#scope

### ISSUE THREAD

**Issue by tarebyte** [octokit/octokit.rb#643]
Currently the [scopes method](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/authorizations.rb#L118) doesn't allow us to pass additional headers for the request.

My use case is that I want to set the

```ruby
'Cache-Control' => 'no-cache, no-store'
```

header so that the response isn't cached.

Is this a change that would be welcome?

/cc @johndbritton

**Comment by pengwynn** [comment]
Sure, we can add an options hash and merge the headers like we do in `Client#get` and friends.
