### ISSUE TITLE
add_collab behaviour with improved organization permissions

### ISSUE THREAD

**Issue by joeyfreund** [octokit/octokit.rb#645]
Hi there, I discovered some unexpected behaviours with the `add_collb` method, when using the improved organization permissions.

Here are the details.

_Note:_ `repo_name` is an organization repository, and my Octokit client is using a token with full organization permissions.

```
octokit.add_collab(repo_name, my_test_user)
```

**Problem 1:** The above call grants `my_test_user` __write permission__ to the repo, __instead of read__ permission (the [expected default](https://developer.github.com/v3/repos/collaborators/#add-collaborator))

Next, suppose `my_test_user` forks the repo, `repo_name`, on GitHub.
I (the organization owner) wants to give some other user, `my_test_user2` read permission to the fork.

First, I tired

```
octokit.add_collab(fork_name, my_test_user2, {permission: 'pull'})
```

**Problem 2:** The above call returned True, but __no permissions were added__.            
Since I really want to add the read permission, here's a work-around ...

Start with

```
octokit.add_collab(fork_name, my_test_user2)
```

Just as before, write permission was added. And then call

```
octokit.add_collab(fork_name, my_test_user2, {permission: 'pull'})
```

And the write permission is changed to a read permission.

----

Some extra info: I am using Octokit 4.1.1 (and I discovered the issue on 4.1.0) and Ruby 2.2.2

**Comment by pengwynn** [comment]
@joeyfreund Could you [get in touch][contact] via support and provide some additional info to help us troubleshoot:

- The authenticating username
- The repo "owner/name"
- The collaborator username you're adding

[contact]: https://github.com/contact?form%5Bsubject%5D=[API]+Help+adding+collaborator

**Comment by mrmoody45** [comment]
Actually I thought I would try make an app but the truth is I don't have a clue what to do, this is new to me.

**Comment by joeyfreund** [comment]
@pengwynn , done.

**Comment by pengwynn** [comment]
Thanks @joeyfreund. Since it appears to be vanilla API issues and not Octokit, I'm going to close this.
