### ISSUE TITLE
Git log to list commits between two commit shas

### ISSUE THREAD

**Issue by EGlenfield22** [octokit/octokit.rb#647]
Does Octokit have any way of listing commits between two commit shas? The equivalent of git log basically. I've tried using Octokit.compare but this only compares the two commit shas, rather than listing the commits between them

**Comment by jessicayang15** [comment]
Hello, does the commits array in the compare response give you what you want?

**Comment by EGlenfield22** [comment]
It only gives me information about the two commit shas I give as a comparison, but I need access to all the commits between them as well

**Comment by pengwynn** [comment]
@EGlenfield22: if you're working in a public repo, can you share your Octokit call? The commits array in the response lists all those, unless I'm misunderstanding what you're looking for:

```ruby
comparison = Octokit.compare("rails/rails", "172c25e7b62b4b7f7c8ef7c7174ed4d17c8dacfe", "a7bd1c7c886686934333cd60b18e6661bdd1cffa")
comparison.commits.map(&:sha)
=> ["bcfbd8ba2192c82aadef6a1d6ba3e87a603ca4f5", "c2854af74784a059318d691d4e021c04719028cf", "fd37486e072fc946da6405eb92a1664b5a735615", "5ddf6df9665c2af2f52593090694327cd9507454", "da832016bf775a5b1daeec40d642bf6424a3018a", "11a3e02237495fcb106297af875b2708d63c279e", "54f3a18eeceb12c99a7a7463048cd13ee6a51778", "fef1064052aeda3701913d3171f17fd4fc84d3f0", "eaa0cb7924d5ffd0de04492a7198e0d79088aaae", "705847578ef41f60e85ad6bd5a606bbadea99ce0", "94d2499156a020a1aee9fedd737975bcaef1b127", "c750ca5da8683833109b5b980d029a918c2c0989", "9b4ec029f661ecde17af08d1e4e38851e57d7a58", "8be6b47d1f078cafd62b38441bbb49d81f2bb0af", "8a6cfbf3ac9dfddef00a527c35b16baf68311ad7", "4516bb93e913a24949345ed5a7c319f3829eaa82", "326f303c78c9c8b0eed658ed322063e74281ef1a", "bd65ba772199bf3284708eb74e91776d361a26ae", "d985c5d23eda396bbc349f01db02d1efccf7af52", "0d4aa374a2d3358c79d2e3f83e1327bc7c81fa1d", "9a57e7f9bb50ef3d4090d75354c254906d4905b7", "a7bd1c7c886686934333cd60b18e6661bdd1cffa"]

**Comment by EGlenfield22** [comment]
Ahhhh didn't see the map function, thanks! :)

**Comment by EGlenfield22** [comment]
How would you access the messages for each commit by doing this?

**Comment by pengwynn** [comment]
@EGlenfield22: the map function is the standard one from Enumerable in Ruby. I just used it in the example to list all the shas from this array of commits.

> How would you access the messages for each commit by doing this?

The [docs][] might help visualize the response structure. To get the message for each commit you can again use `map`, with a block:

```ruby
comparison.commits.map {|c| c.commit.message }
```

[docs]: https://developer.github.com/v3/repos/commits/#response-2

**Comment by EGlenfield22** [comment]
Thanks for the help, I'll give it a go :+1:
