### ISSUE TITLE
Create `doc` folder for documentation?

### ISSUE THREAD

**Issue by mattr-** [octokit/octokit.rb#654]
Hi!

I was skimming through the README, and noticed that it's become quite large. I was going to split up the documentation and move it into a `doc` folder, which seems to be a common pattern for some other projects I'm involved with, but wanted to check to see if that was a wanted thing before I spent the time on it.

**Comment by pengwynn** [comment]
Hey Matt. I originally had it that way but YARD's include syntax seemed to confuse people with the README was rendered on GitHub. Got any suggestions on how to get around that?

**Comment by mattr-** [comment]
No suggestions at the moment. I can play around with it and see what I find out, or we can just drop it. I didn't think to check the git history to see what the past looked like.

**Comment by exstacyinme** [comment]
I just want to know if maybe my soon to be x sent it to me just to hurt me
