### ISSUE TITLE
Better regex in "Traversing With Pagination" GitHub Developer guide

### ISSUE THREAD

**Issue by veloandy** [octokit/octokit.rb#656]
Not sure if you all are the folks who maintain the GitHub Developer guides re: Octokit...if you're not, feel free to disregard or forward this along to the right team.

The [Traversing With Pagination GitHub Developer guide](https://developer.github.com/guides/traversing-with-pagination/) has the following example about how to get the number of pages available from a GitHub API call:

```ruby
last_response = client.last_response
number_of_pages = last_response.rels[:last].href.match(/page=(\d+)$/)[1]

puts "There are #{total_count} results, on #{number_of_pages} pages!"
```

It would be better if it was:
```ruby
last_response = client.last_response
number_of_pages = last_response.rels[:last].href.match(/page=(\d+).*$/)[1]  # note .* before $

puts "There are #{total_count} results, on #{number_of_pages} pages!"
``` 

The href could be something like ```https://api.github.com/repositories/228/pulls?page=15&state=all"``` so we need the regex to match and discard  everything from after the page# until the end of the line.

**Comment by joeyw** [comment]
Sent a pull request to the api documentation since this isn't an octokit issue. Thanks!
