### ISSUE TITLE
Auto decode Base64 content

### ISSUE THREAD

**Issue by pengwynn** [octokit/octokit.rb#663]
As requested in https://github.com/octokit/octokit.rb/pull/652#issuecomment-149708107, we should explore a module-level config option to auto-decode Base64 content from the README, Licenses, and other APIs that return Base64 content.

**Comment by sigmavirus24** [comment]
FWIW, github3.py does this by default and preserves the original base64 encoded content.

**Comment by pengwynn** [comment]
>  and preserves the original base64 encoded content.

Good idea, @sigmavirus24. :bulb:
