### ISSUE TITLE
create_ref error message can be unhelpful

### ISSUE THREAD

**Issue by bhuga** [octokit/octokit.rb#675]
`Octokit::Client.create_ref` will return a message from the API about how to format refs verbatim:

```
POST https://api.github.com/repos/foo/bar/git/refs: 422 - Reference name must contain at least three slash-separated components. // See: https://developer.github.com/v3/git/refs/#create-a-reference
```

But this message isn't very helpful, because Octokit will prepend `refs/` to anything given. If one follows the error message's advice, sending in `refs/heads/whatever`, the result is:

```
POST https://api.github.com/repos/foo/bar/git/refs: 422 - refs//refs/heads/potential-master-foo is not a valid ref name. // See: https://developer.github.com/v3/git/refs/#create-a-reference
```

Since we're going to pass the error message back to the client, and we're going to edit the data the client gives us, should we strip a leading `refs/` from client input? I'm don't think `refs/refs` is ever valid anyway, and it would make following the error message's advice work.

**Comment by pengwynn** [comment]
> Since we're going to pass the error message back to the client, and we're going to edit the data the client gives us, should we strip a leading refs/ from client input?

I like that idea. :+1:

**Comment by pengwynn** [comment]
@bhuga I know you have a full plate. Were you in progress on this or are you looking for someone else to whip up that patch?

**Comment by bhuga** [comment]
I just wanted to write it down; I might get to this on a Friday. Certainly not a blocker or anything.
