### ISSUE TITLE
Not working well patch is used in some method

### ISSUE THREAD

**Issue by yuta17** [octokit/octokit.rb#676]
I often use octkit !  
Thank you everyone for everything ! 

I report because find the problem while I have used .
It may be due to my mistake . but In the case, I think it's document is need to improve. 

First, [lib/octokit/client/issue.rb at 113](https://github.com/octokit/octokit.rb/blob/a2b1217f9662b7ef2ab718ec32f54283c9562546/lib/octokit/client/issues.rb) is working well using get

[issue method](https://octokit.github.io/octokit.rb/Octokit/Client/Issues.html#issue-instance_method)

```
[1] pry(main)> Octokit.issue("yuta17/Tourism","4")                                                                                                                            
=> {:url=>"https://api.github.com/repos/yuta17/Tourism/issues/4",
 :labels_url=>
  "https://api.github.com/repos/yuta17/Tourism/issues/4/labels{/name}",
:comments_url=>
  "https://api.github.com/repos/yuta17/Tourism/issues/4/comments",
 ...
```

https://github.com/yuta17/Tourism/issues/4

But, [at 129, 145](https://github.com/octokit/octokit.rb/blob/a2b1217f9662b7ef2ab718ec32f54283c9562546/lib/octokit/client/issues.rb) is not working well using patch.

```
[2] pry(main)> Octokit.close_issue("yuta17/Tourism","4")
Octokit::NotFound: PATCH https://api.github.com/repos/yuta17/Tourism/issues/4: 404 - Not Found // See: https://developer.github.com/v3/issues/#edit-an-issue
from /Users/yuta/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
```

```
[3] pry(main)> Octokit.reopen_issue("yuta17/Tourism","2")
Octokit::NotFound: PATCH https://api.github.com/repos/yuta17/Tourism/issues/2: 404 - Not Found // See: https://developer.github.com/v3/issues/#edit-an-issue
from /Users/yuta/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
```

https://github.com/yuta17/Tourism/issues/2

I frustrate I can't resolve, What's the problem?

**Comment by pengwynn** [comment]
A `404` often means insufficient permissions. Can you share how you're [authenticating][], (please don't paste any passwords or tokens)? :see_no_evil:

[authenticating]: https://github.com/octokit/octokit.rb#authentication

**Comment by yuta17** [comment]
Thanks for your reply.

I tried ...

```
client = Octokit::Client.new(access_token: "xxxxxxxxx")
Octokit.close_issue("#{client.user.login}/Tourism", "4")

>Octokit::NotFound: PATCH https://api.github.com/repos/yuta17/Tourism/issues/4: 404 - Not Found // See: https://developer.github.com/v3/issues/#edit-an-issue
from /Users/yuta/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete'

```
What should I do?

**Comment by pengwynn** [comment]
@yuta17 thanks for the snippet. You're setting your token correctly, now try making the call with the authenticated client:

```ruby
client = Octokit::Client.new(access_token: "xxxxxxxxx")
client.close_issue("#{client.user.login}/Tourism", "4")
```

**Comment by yuta17** [comment]
@pengwynn 
I tried after reissue an access_token. but..

[2] pry(main)> client = Octokit::Client.new(access_token: "xxxxxxxxxx")
=> #<Octokit::Client:0x3fda698b6784>
[3] pry(main)> client.close_issue("yuta17/Tourism","4")
Octokit::NotFound: PATCH https://api.github.com/repos/yuta17/Tourism/issues/4: 404 - Not Found // See: https://developer.github.com/v3/issues/#edit-an-issue
from /Users/gitan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
[4] pry(main)> client.user
=> {:login=>"yuta17",
 :id=>8072432,
 :avatar_url=>"https://avatars.githubusercontent.com/u/8072432?v=3",
 :gravatar_id=>"",
 :url=>"https://api.github.com/users/yuta17",
 :html_url=>"https://github.com/yuta17",
[5] pry(main)> client.user.login
=> "yuta17"
[6] pry(main)> client.close_issue("#{client.user.login}/Tourism","4")
Octokit::NotFound: PATCH https://api.github.com/repos/yuta17/Tourism/issues/4: 404 - Not Found // See: https://developer.github.com/v3/issues/#edit-an-issue
from /Users/gitan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete'

**Comment by joeyw** [comment]
Hello @yuta17, can you please use show the scopes your token was created with?

```ruby
client = Octokit::Client.new(access_token: "xxxxxxxxxx")
client.scopes
```

The output should include the `repo` scope to be able to close issues in your repository.

**Comment by yuta17** [comment]
@joeyw , Thanks for your reply.

It went well in this way [Creating an access token for command-line use](https://help.github.com/articles/creating-an-access-token-for-command-line-use/).

but, not working well in the case of getting access_token using omniauth-github

pry(main)>client = Octokit::Client.new(access_token: "getting access_token by omniauth-github")
pry(main)> client.scopes
=> []

I want to create web service use close_issue.
Should It asks for username and password to user?

**Comment by pengwynn** [comment]
Thanks for the additional details @yuta17. Be sure you [configure omniauth][link] to ask for the right scopes. Since this isn't an Octokit issue, I'm going to go ahead and close it. If you're still having trouble, I recommend you open an issue over in that project.

[link]: https://github.com/intridea/omniauth-github#scopes
