### ISSUE TITLE
Gist at specific revision

### ISSUE THREAD

**Issue by joeyw** [octokit/octokit.rb#681]
https://developer.github.com/v3/gists/#get-a-specific-revision-of-a-gist is currently unsupported in octokit. Should [#gist](https://github.com/octokit/octokit.rb/blob/28a594ff371ff3faf8ec50dd25bd65bd779ff43f/lib/octokit/client/gists.rb#L50) be extended to take the revision SHA or add a new method specifically for it?

**Comment by pengwynn** [comment]
>  Should #gist be extended to take the revision SHA or add a new method specifically for it?

I like adding a `:sha` option to that method.
