### ISSUE TITLE
Add stats timeout configuration options

### ISSUE THREAD

**Issue by kv109** [octokit/octokit.rb#685]
Hi!

Github API [statistics](https://developer.github.com/v3/repos/statistics/) call returns `202` if they are not calculated yet. I think it would be useful to add `stats_timeout` configuration option, which would tell Octokit to try to retrieve this data for a given amount of time. PR could look like [this](
https://github.com/octokit/octokit.rb/compare/master...kv109:master?diff=unified&name=master).

What do you think?

PS. Thank you for this project, it works amazing.

**Comment by pengwynn** [comment]
@kv109 the idea is intriguing. Wanna open a PR so we could have a conversation on the diff?

**Comment by kv109** [comment]
@pengwynn With pleasure: https://github.com/octokit/octokit.rb/pull/687. No idea how to test this functionality, though.
