### ISSUE TITLE
Rels[type] doesn't seem to work for Orgs

### ISSUE THREAD

**Issue by GregSutcliffe** [octokit/octokit.rb#691]
I'm trying to get a list of repos for an Org. For a user it would be:

```
> user = Octokit.user 'GregSutcliffe'
> user.repos
```

This didn't work well as an Org (only returns ~30 of our repos), so I tried to use the URL from the `rels` collection (i.e. `org.rels[:repos_url].get`)

```
> org = Octokit.org 'theforeman'
> org.rels                                                                                              
=> {:self_url=>"https://api.github.com/orgs/theforeman",
 :repos_url=>"https://api.github.com/orgs/theforeman/repos",
 :events_url=>"https://api.github.com/orgs/theforeman/events",
 :members_url=>"https://api.github.com/orgs/theforeman/members",
 :public_members_url=>"https://api.github.com/orgs/theforeman/public_members",
 :avatar_url=>"https://avatars.githubusercontent.com/u/1439844?v=3",
 :html_url=>"https://github.com/theforeman"}
> org.rels[:repos_url]                                                                                  
=> nil
```

Firstly this seems just wrong (hence the bug report). Secondly, is there an Octokit way to grab the data from "https://api.github.com/orgs/theforeman/repos" ?

**Comment by GregSutcliffe** [comment]
Ok, I'm a fool, it's the pagination kicking in. `repos = Octokit.repos 'theforeman', :per_page => 150` seems to work, although we have 103 repos and this returns 100... still investigating that.

In any case, the rels thing above still seems like a bug unless I'm also using that wrong.

**Comment by pengwynn** [comment]
@GregSutcliffe it looks like you've answered most of your own questions. :wink: 

> In any case, the rels thing above still seems like a bug unless I'm also using that wrong.

The `<name>_url` link relations become just `<name>` in the `rels` hash. We could make that clearer [in the README](https://github.com/octokit/octokit.rb#hypermedia-in-octokit). (Patches welcome.)

So in this case you want:

```ruby
Octokit.org('theforeman').rels[:repos].get
```

Does that help? Can we close this one out?

**Comment by GregSutcliffe** [comment]
Ah, I missed that. It's a huge README though ;)

Yeah that works as expected, just a PEBKAC error. Now that I see the section the README, I think the wording is fine - at least, it makes sense having already tried the sample code. Thanks for the clarification!
