### ISSUE TITLE
Create blob containing double quotes fails

### ISSUE THREAD

**Issue by twcclegg** [octokit/octokit.rb#696]
Trying to create a blob that contains double quotes (") fails:
```c#
await Client.GitDatabase.Blob.Create(Owner, repo, new NewBlob {Content = "﻿<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<configuration xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />\r\n" });
```
This returns a sha but when trying to make a tree based on this blob I get error that that sha is not a valid blob.

**Comment by gjtorikian** [comment]
That doesn't look like any Ruby I'm familiar with. :wink: Did you mean to open this up at https://github.com/octokit/octokit.net?

**Comment by twcclegg** [comment]
oops yes, thanks
