### ISSUE TITLE
How do I add a user as a member to my organization via my organization?

### ISSUE THREAD

**Issue by lifeiscontent** [octokit/octokit.rb#703]
``` rb
    client = Octokit::Client.new(Octokit.exchange_code_for_token(params[:code]))
    admin_client = Octokit::Client.new(
      login: 'lifeiscontent',
      password: '...'
    )

    admin_client.update_organization_membership(
      'moderndeveloper-students',
      user: client.user[:login],
      role: 'member',
      accept: 'application/vnd.github.moondragon+json'
    )

```

with the following code, an invite gets sent via my username `lifeiscontent` is there any way to update a membership via the actual organization?

I've tried using the `client.as_app` functionality but it tells me I am not logged in when running the update organization membership.

**Comment by pengwynn** [comment]
@lifeiscontent looks like you're trying to add yourself in that example. The `user` parameter should be the login of the user you want to add.

**Comment by lifeiscontent** [comment]
@pengwynn Yes, in that example I'm using my id, but how would I do it on behalf of a organization?

**Comment by pengwynn** [comment]
> how would I do it on behalf of a organization?

I'm not quite sure I follow. To add _other-user_ to _some-org_ you need to authenticate as an admin of _some-org_ and the call would look like:

```ruby
client = Octokit::Client.new(
  login => 'your-username',
  passwor => 'your password'
)

client.update_organization_membership(
  'some-org',
  user => 'other-user',
  role => 'member'
)
```

Usually, though, you'll want to [add them to a team][team] instead.

[team]: http://octokit.github.io/octokit.rb/Octokit/Client/Organizations.html#add_team_membership-instance_method

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as there's been no movement on it in the past 6 months, and it's not quite clear what the request is.

@lifeiscontent if you're still having trouble with this, please reopen it with more information so we can help you get this sorted.
