### ISSUE TITLE
Would like a way to get an Octokit::Repository from an issue or PR Hash

### ISSUE THREAD

**Issue by aroben** [octokit/octokit.rb#704]
I'm writing a script to show me all PRs opened by me in the last year, and I want to group the PRs by repository. I'm using `Octokit::Client#search_issues` to get the list of PRs. To group them by repository, I need to figure out what repository each PR is in.

The Hash returned by https://developer.github.com/v3/search/#search-issues doesn't include any direct information about the repository. `html_url` of course includes the repository's name-with-owner, so I can use a regex or similar to extract that. It would be nicer if something like `Octokit::Repository.from_url` could do that for me (right now that API only accepts repository URLs, not issue/PR URLs).

Another option would be for the API response to include some information about the repository. That change would happen on github.com, not in Octokit, of course.

**Comment by joeyw** [comment]
Added in #704
