### ISSUE TITLE
How do I get the permission level of a user to a specific repository?

### ISSUE THREAD

**Issue by jiaxinyu19843** [octokit/octokit.rb#711]
I could not find a way to achieve this directly, so what I tried is first getting a list of teams that have admin access to the repo and then check if the user belongs to any of them. I am now stuck at the first step. The first way I tried is "client.teams('my_repo')" and check the "permission" attribute of the result, but what I get is only the owner team has the "admin" permission, and all the other ones have "pull" permission, though I can see all of them having "admin" access on the Github Webpage.  The second way I tried is for each team received in the first way, I call "client.team_repositories(team['id'])", and then for each repo received, check if "repo['permissions']['admin']" is true. However, it seems the admin attribute is always true, no matter if the team has admin access to the repo. I am not sure if this is expected or a Github API bug. BTW, I am using Github Enterprise 2.4.3.

**Comment by gjtorikian** [comment]
> However, it seems the admin attribute is always true, no matter if the team has admin access to the repo. I am not sure if this is expected or a Github API bug. BTW, I am using Github Enterprise 2.4.3.

I've confirmed that this is true, and will file a bug internally with the API team. Sorry for the trouble there.

**Comment by jakeboxer** [comment]
Regarding the question in the issue's title ("How do I get the permission level of a user to a specific repository?"): there's currently no single way to do this. Checking teams is a good first step, but you'd also have to check whether or not the user is a direct collaborator on the repository, and whether or not the organization that owns the repository has a default repository permission (and whether or not the user is a member of that organization).

I definitely agree that a "Get user's permission on repository" API would be valuable, so I've added an item for it to our API wish list. Thanks a bunch for suggesting it!

**Comment by richiebres** [comment]
@jakeboxer I have a related question: How do you determine the **Default repository permission** for members of an organization using the GitHub API.

Expected to find it here, but no joy:
https://developer.github.com/v3/orgs/#get-an-organization

This is what I'm referring to btw
![screen shot 2016-06-10 at 11 56 16 am](https://cloud.githubusercontent.com/assets/1798345/15975461/6d1e3eae-2f02-11e6-81d3-75412a13f9b6.png)

**Comment by jakeboxer** [comment]
@richiebres you currently can't find this information in the API, but we've got an issue open internally to add it!

**Comment by LizzHale** [comment]
The ability to get the permission level for a given user on a given repository was [added to the API recently](https://developer.github.com/changes/2016-11-28-preview-org-membership/). That preview also includes the ability to get/set the `default_repository_permission` setting. 

I have a PR open to add these changes to octokit [here](https://github.com/octokit/octokit.rb/pull/841)

**Comment by aabbccddff9961** [comment]
Hi
