### ISSUE TITLE
Can't find closed pulls/issues

### ISSUE THREAD

**Issue by jandudulski** [octokit/octokit.rb#715]
I would like to fetch all pulls/issues from repo but only open are returned:

```ruby
repo.rels[:pulls].get(state: "all")
```

The same thing when I use `state: "closed"`.

**Comment by gjtorikian** [comment]
Could you list which repository you're trying to work on?

**Comment by jandudulski** [comment]
Hah, it seems that I was using `get` in a [wrong way](https://github.com/octokit/octokit.rb/blob/28a594ff371ff3faf8ec50dd25bd65bd779ff43f/lib/octokit/connection.rb#L190). It should be:

```ruby
repo.rels[:pulls].get(query: { state: "all" })
```

It would be nice to have this in readme :)

**Comment by tarebyte** [comment]
@jandudulski another way you can achieve this would be something like this:

```ruby
gh_client = Octokit::Client.new(access_token: token)
gh_client.pull('tarebyte/dotfiles', state: 'all')
```

I feel like this syntax might be a little easier to use, what do you think?

**Comment by pengwynn** [comment]
Glad you figured it out @jandudulski.

> It would be nice to have this in readme :)

Since you're using they Hypermedia link relations, perhaps an example of using query params in [that section](https://github.com/octokit/octokit.rb#hypermedia-agent) would be helpful. Patches welcome.
