### ISSUE TITLE
cannot load such file -- octokit.rb 

### ISSUE THREAD

**Issue by prathimak** [octokit/octokit.rb#716]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- octokit.rb (LoadError)

**Comment by pengwynn** [comment]
@prathimak The gem name is "octokit". Is that what you've got in your Gemfile?

**Comment by joeyw** [comment]
@prathimak I am closing this issue since it has been a while without a response.

**Comment by addison-grant** [comment]
I am getting this error, too
```
>> feature
Traceback (most recent call last):
        5: from /home/agrant/bin/feature:23:in `<main>'
        4: from /home/agrant/bin/feature:23:in `load'
        3: from /usr/local/share/gems/gems/git-scripts-0.9.0/bin/feature:3:in `<top (required)>'
        2: from /usr/local/share/gems/gems/git-scripts-0.9.0/bin/feature:3:in `require_relative'
        1: from /usr/local/share/gems/gems/git-scripts-0.9.0/lib/github.rb:3:in `<top (required)>'
/usr/local/share/gems/gems/git-scripts-0.9.0/lib/github.rb:3:in `require': cannot load such file -- octokit (LoadError)
```

I am using git-scripts's `feature`. Before I add a file called Gemfile, `feature` works fine.
