### ISSUE TITLE
Octokit::EnterpriseAdminClient create_organization method 

### ISSUE THREAD

**Issue by veesa** [octokit/octokit.rb#719]
I am trying to programmatically create some Organizations. 

In the code I have:

``` ruby
admin_client.create_organization('<loginname>', 'false', {:name=>'Research'})
```

When executed it gives me:

```
POST https://172.16.165.25.xip.io/api/v3/admin/organizations: 422 - Invalid request. (Octokit::UnprocessableEntity)

"admin", "login" weren't supplied. // See: https://developer.github.com/enterprise/2.4/v3/enterprise/organizations/
```

What are the values of "admin" and "login" that I need to supply in order to get this method working?  The supplied URL (https://developer.github.com/enterprise/2.4/v3/enterprise/organizations/) returns a 404.

Cheers!

**Comment by gjtorikian** [comment]
So sorry about he incorrect URL. I'll file an issue internally to get that resolved.

In the meantime, the actual documentation URL is https://developer.github.com/enterprise/2.4/v3/enterprise/orgs/. Does reading about the endpoint there help you out?

**Comment by keeran** [comment]
This is due to the gem release having an incomplete `create_organization` method:

````
def create_organization(login, admin, options = {})
  post "admin/organizations", options
end
````

The `login` and `admin` args are ignored. This is not the case on [master](https://github.com/octokit/octokit.rb/blob/d7d47e595ce93393baef6c7375023b457d095b71/lib/octokit/enterprise_admin_client/orgs.rb#L19).

The workaround is to duplicate the fields in the options arg:

````
admin_client.create_organization 'dummy', 'params', { :login => 'new-org-name', :admin => 'ghe-admin', :profile_name => 'new org!'}
````

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since there have been new releases since the issue was opened, which would have fixed the `create_organization` method.
