### ISSUE TITLE
How to get a list of teams with their associated permissions for a specific repository?

### ISSUE THREAD

**Issue by nBerg** [octokit/octokit.rb#720]
At first I tried getting the `repository_teams` and checking the permissions attribute, but that field appears to be incorrect.

Next I noticed this endpoint https://developer.github.com/v3/orgs/teams/#check-if-a-team-manages-a-repository with the "alternative response" - but it looks like octokit does not support that? Or at least I can't find it.

Right now, I'm getting the list of teams from `repository_teams`, and then for each team calling `team_repositories`, and searching for the repository I'm interested in to get the permissions information.

Is there a better way to accomplish this?

**Comment by gjtorikian** [comment]
> Next I noticed this endpoint https://developer.github.com/v3/orgs/teams/#check-if-a-team-manages-a-repository with the "alternative response" - but it looks like octokit does not support that? Or at least I can't find it.

You can provide [the media type](https://github.com/octokit/octokit.rb#upgrading-guide) as a global or pre-request value.

**Comment by kytrinyx** [comment]
I'm going to assume that the above response resolved this issue. If not, please feel free to reopen this.
