### ISSUE TITLE
Is there a method to import a Github repo?

### ISSUE THREAD

**Issue by hackerkid** [octokit/octokit.rb#721]
https://developer.github.com/v3/migration/source_imports/

Is this supported yet ?

**Comment by pengwynn** [comment]
Methods like `Octokit::Client#start_import` do not yet exist (patches welcome :bowtie:), but you can drop down and use the lower-level HTTP interface. Something like:

```ruby
options = {
  :vcs => "subversion",
  :vcs_url => "http://svn.mycompany.com/svn/myproject",
  :vcs_username => "octocat",
  :vcs_password => "secret",
  :headers => {:accept => "application/vnd.github.barred-rock-preview"}
}
client = Octokit::Client.new :access_token => "yours"
client.put "https://api.github.com/repos/hackerkid/myrepo/import", options
```

**Comment by hackerkid** [comment]
Thanks. I have added this to my todo list. I will send a PR when I complete :smile:

**Comment by gjtorikian** [comment]
Head's up to @spraints who I also strong armed into trying to implement this. :grin:
