### ISSUE TITLE
How can I set the Member Privileges options using Octokit?

### ISSUE THREAD

**Issue by AnalogJ** [octokit/octokit.rb#726]
Hey, I'm trying to figure out how to modify/update the "Default repository permission" and "Repository creation" options in the "Member Privileges" section of an Organization

I've looked for a while, but I haven't seen anything in gem, or on the Github API docs. 

<img width="762" alt="screen shot 2016-03-07 at 7 11 45 pm" src="https://cloud.githubusercontent.com/assets/891875/13590894/a1f55ea0-e498-11e5-8410-84797846426c.png">

**Comment by tarebyte** [comment]
@AnalogJ there actually isn't a way to do that through the GitHub API.

There are lots of actions that you can perform on GitHub the website but that you can't do through the API. This happens to be one of them.

**Comment by AnalogJ** [comment]
@tarebyte Thanks for the quick response!
Thats unfortunate, we use Enterprise Github, and I was hoping to configure those two settings for a organization setup script. 
Thanks anyways :)
