### ISSUE TITLE
addressable v2.5.0 causing issue in octokit.rb v4.6.0

### ISSUE THREAD

**Issue by pvdb** [octokit/octokit.rb#727]
Hi peeps,

After installing the latest release version of `octokit.rb` - i.e. `v4.3.0` - I noticed that the following query:

``` ruby
Octokit::Client.new.repository('octokit/octokit.rb').rels[:ssh].href
```

... which used to work in earlier releases, and returned:

``` ruby
"git@github.com:octokit/octokit.rb.git"
```

... now throws this exception instead:

``` ruby
Addressable::URI::InvalidURIError: Invalid scheme format: git@github.com
from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/addressable-2.4.0/lib/addressable/uri.rb:867:in `scheme='
```

This is demonstrated in a bit more detail in the below `pry` sessions... I haven't had a chance yet to dig into the `sawyer` or `addressable` changes to determine whether this new behaviour is a bug or a feature, but I thought I'd raise it here already for awareness, as it is definitely a regression issue.

Thanks,

@pvdb

---

**previous release: `octokit.rb v4.2.0` with `sawyer v0.6.0` and `addressable v2.3.8`**

``` ruby
[1] pry(main)> Octokit::VERSION
=> "4.2.0"
[2] pry(main)> Sawyer::VERSION
=> "0.6.0"
[3] pry(main)> Addressable::VERSION::STRING
=> "2.3.8"
[4] pry(main)> repo = Octokit::Client.new.repository('octokit/octokit.rb') ; nil
=> nil
[5] pry(main)> repo.rels[:git].href
=> "git://github.com/octokit/octokit.rb.git"
[6] pry(main)> repo.rels[:svn].href
=> "https://github.com/octokit/octokit.rb"
[7] pry(main)> repo.rels[:ssh].href
=> "git@github.com:octokit/octokit.rb.git"
[8] pry(main)> _
```

**current release: `octokit.rb v4.3.0` with `sawyer v0.7.0` and `addressable v2.4.0`**

``` ruby
[1] pry(main)> Octokit::VERSION
=> "4.3.0"
[2] pry(main)> Sawyer::VERSION
=> "0.7.0"
[3] pry(main)> Addressable::VERSION::STRING
=> "2.4.0"
[4] pry(main)> repo = Octokit::Client.new.repository('octokit/octokit.rb') ; nil
=> nil
[5] pry(main)> repo.rels[:git].href
=> "git://github.com/octokit/octokit.rb.git"
[6] pry(main)> repo.rels[:svn].href
=> "https://github.com/octokit/octokit.rb"
[7] pry(main)> repo.rels[:ssh].href
Addressable::URI::InvalidURIError: Invalid scheme format: git@github.com
from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/addressable-2.4.0/lib/addressable/uri.rb:867:in `scheme='
[8] pry(main)> _
```

**Comment by pengwynn** [comment]
@pvdb Ooof, thanks for reporting. While we investigate a fix, are you able to pin Sawyer to v0.6.0 in your Gemfile as a workaround?

**Comment by pvdb** [comment]
Hey @pengwynn - as a quick workaround, we started using `repo.rels[:git].href` instead of `repo.rels[:ssh].href`, because - for our purposes at least - they are pretty much interchangeable... so no, I didn't test any version permutations yet.

On that note, I blame the bug on `sawyer v0.7.0` in my PR title, but I have no concrete evidence for that: it could be an issue in `addressable` or indeed `octokit.rb` itself for that matter... I may have some time later today to dig a bit deeper, in which case I will report back here.

**Comment by pvdb** [comment]
> While we investigate a fix, are you able to pin Sawyer to v0.6.0 in your Gemfile as a workaround?

So I have now pinned `sawyer` to `v0.6.0`, and ran my little test snippet again against the `v4.3.0` version of `octokit.rb`, and things work as expected:

```ruby
[1] pry(main)> Octokit::VERSION
=> "4.3.0"
[2] pry(main)> Sawyer::VERSION
=> "0.6.0"
[3] pry(main)> Addressable::VERSION::STRING
=> "2.3.8"
[4] pry(main)> repo = Octokit::Client.new.repository('octokit/octokit.rb') ; nil
=> nil
[5] pry(main)> repo.rels[:git].href
=> "git://github.com/octokit/octokit.rb.git"
[6] pry(main)> repo.rels[:svn].href
=> "https://github.com/octokit/octokit.rb"
[7] pry(main)> repo.rels[:ssh].href
=> "git@github.com:octokit/octokit.rb.git"
[8] _
```

So as far as I can tell, it appears to be in issue in either `sawyer v0.7.0` or else in `addressable v2.4.0`

**Comment by pvdb** [comment]
@pengwynn - I think this is the culprit: https://github.com/sporkmonger/addressable/commit/e2325b8a29c85fec0091d22602c38058ca11bff9 : by anchoring the scheme regex, something like `git@github.com` no longer matches, whereas before it did... not exactly sure what a correct and/or acceptable fix/workaround would look like, though, as adherence to RFC 3986 is probably "A Good Thing"™ :smile:

**Comment by pvdb** [comment]
@pengwynn - on further reflection, I guess the root cause of this issue is that the GitHub.com API returns a scheme-less, `scp`-like URI for `repo.rels[:ssh]`, something like:

    git@github.com:octokit/octokit.rb.git

... instead of a proper, RFC 2396 compliant, `ssh`-scheme URI, something like:

    ssh://git@github.com/octokit/octokit.rb.git

Due to the lack of a scheme, the former doesn't pass the RFC 3986 compliance introduced in sporkmonger/addressable#205, whereas the latter would.

The GitHub.com API behavior is consistent with the GitHub.com web UI, which also returns the `scp`-like URI, but perusing [the relevant `git` documentation][gitdoc] I get the impression that `git` itself only accepts the `scp`-like URI as a convenience method when cloning repos, and really expects the proper `ssh`-scheme URI:

> ### The SSH Protocol
>
> ...
>
> To clone a Git repository over SSH, you can specify `ssh://` URL like this:
>
>     $ git clone ssh://user@server/project.git
> 
> Or you can use the shorter `scp`-like syntax for the SSH protocol:
>
>     $ git clone user@server:project.git
>

[gitdoc]: https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#The-SSH-Protocol

I guess changing the GitHub.com API to return RFC 2396 compliant SSH URLs is too much of an ask :smiley: so for our internal purposes, we are monkey-patching `repo.rels[:ssh]` to convert the `scp`-like URL into a proper `ssh` URL on the fly:

```ruby
[1] pry(main)> repo = Octokit::Client.new.repository('octokit/octokit.rb') ; nil
=> nil
[2] pry(main)> ssh_relation = repo.rels[:ssh]
=> #<Sawyer::Relation: ssh: get #<Addressable::Template:0x007fc9558afb58>>
[3] pry(main)> href_template = ssh_relation.href_template
=> #<Addressable::Template:0x3fe4aac57dac PATTERN:git@github.com:octokit/octokit.rb.git>
[4] pry(main)> scp_pattern = href_template.pattern
=> "git@github.com:octokit/octokit.rb.git"
[5] pry(main)> ssh_pattern = "ssh://%s/%s" % scp_pattern.split(':', 2)
=> "ssh://git@github.com/octokit/octokit.rb.git"
[6] pry(main)> href_template.instance_variable_set(:"@pattern", ssh_pattern)
=> "ssh://git@github.com/octokit/octokit.rb.git"
[7] pry(main)> ssh_relation.href
=> "ssh://git@github.com/octokit/octokit.rb.git"
[8] pry(main)> _
```

That probably doesn't help much in resolving this particular issue in the latest version of `octokit.rb`, but - for our purposes at least - this monkey-patch gives us parity with earlier versions of `octokit.rb`.

**Comment by pvdb** [comment]
> Due to the lack of a scheme in the `scp`-like URI, the former doesn't pass the RFC 3986 compliance introduced in sporkmonger/addressable#205

Put differently:

```shell
$  ruby -r uri -e "puts URI('git@github.com:octokit/octokit.rb.git')"
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): git@github.com:octokit/octokit.rb.git (URI::InvalidURIError)
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/uri/common.rb:714:in `URI'
	from -e:1:in `<main>'
$ _
```

**Comment by pengwynn** [comment]
@pvdb thanks for reporting. I'm trying to determine if this is a server-side or an Octokit fix. I'll circle back 🔜.

**Comment by pvdb** [comment]
Hey @pengwynn - any update on this issue?

I've just re-tested the issue against all the latest versions - of `octokit.rb`, `sawyer` and `addressable` -  and it is still a problem I'm afraid :frowning:

```ruby
[1] pry(main)> Octokit::VERSION
=> "4.6.0"
[2] pry(main)> Sawyer::VERSION
=> "0.8.0"
[3] pry(main)> Addressable::VERSION::STRING
=> "2.5.0"
[4] pry(main)> repo = Octokit::Client.new.repository('octokit/octokit.rb') ; nil
=> nil
[5] pry(main)> repo.rels[:git].href
=> "git://github.com/octokit/octokit.rb.git"
[6] pry(main)> repo.rels[:svn].href
=> "https://github.com/octokit/octokit.rb"
[7] pry(main)> repo.rels[:ssh].href
Addressable::URI::InvalidURIError: Invalid scheme format: git@github.com
from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/addressable-2.5.0/lib/addressable/uri.rb:874:in `scheme='
[8] pry(main)> _
```

Thanks!

**Comment by pvdb** [comment]
BTW: I am more than happy to submit a PR along the lines of the monkey patch I described and demoed in an earlier comment, but you wrote:

>  I'm trying to determine if this is a server-side or an Octokit fix. 

So my PR would only be relevant if your conclusion is that it requires an Octokit fix instead of a server-side fix.

**Comment by pengwynn** [comment]
@pvdb thanks for the ping. I'll take a look at what we can do. If you want to push up a monkey patch, that'd be great.

**Comment by pvdb** [comment]
> If you want to push up a monkey patch, that'd be great.

Done in #830 ... :monkey_face:

**Comment by pvdb** [comment]
hey @stormyyz, I noticed you reacted to the previous comment... I would be keen to find out if and how this issue has impacted you? I know for a fact it also impacted TravisCI - travis-ci/travis.rb#342 - but I'm wondering just how wide the blast radius is?
