### ISSUE TITLE
Caching Octokit::Client::Repositories#repositories() call 

### ISSUE THREAD

**Issue by vincentvankrunkelsven** [octokit/octokit.rb#728]
I'm using Octokit to create repositories on GitHub with **Octokit::Client::Repositories#create_repository**. When I create a repository and check out the repositories of my account right after using **Octokit::Client::Repositories#repositories**, the new repository doesn't appear. Takes up to 40 seconds for it to appear.

Does this have something to do with caching? Can I disable it? I can't remember having this problem a few weeks ago.

Some screenshots of the process

**Creating the repo**
<img width="706" alt="create_repo" src="https://cloud.githubusercontent.com/assets/2217728/13644241/03abe8a2-e625-11e5-98fe-ee967ca2c780.png">

**Checking after +- 30 secs (not there yet)**
<img width="993" alt="not_yet" src="https://cloud.githubusercontent.com/assets/2217728/13644247/0805a032-e625-11e5-8caa-4435393f8eb9.png">

**And it's there**
<img width="984" alt="repo_is_there" src="https://cloud.githubusercontent.com/assets/2217728/13644257/0cea48d2-e625-11e5-9acf-e6a37c50dbe2.png">

**Comment by pengwynn** [comment]
@vincentvankrunkelsven thanks for reporting. Indeed, there is some cache tuning going on in that high traffic method. We're considering how to improve the behavior here. For now, there will be a small delay between the create operation and when your repository shows up in that list.
