### ISSUE TITLE
Recurring 502 - Server Error on API calls

### ISSUE THREAD

**Issue by jkim0120** [octokit/octokit.rb#729]
Hey,

I've been experimenting with the octokit gem, trying to extract issue comments of a rather large repository with `client.issues_comments(<REPO>, <OPTIONS>)`. I've noticed that on a good majority of the calls, I get a `502 - Server Error` with the following headers:

![screen shot 2016-03-10 at 3 21 05 pm](https://cloud.githubusercontent.com/assets/8285179/13683646/d10c2914-e6d5-11e5-8a9b-3b9c49c855dc.png)

Are the servers being overloaded or is this some other issue?

**Comment by gjtorikian** [comment]
Cool. We're also seeing these errors on our internal logs. Thanks for reporting this! We'll look into it.

As this is not an Octokit issue per se, I'm going to close this issue. Also, in the future, I highly recommend you contact us via https://github.com/contact. We'll be able to better serve API users that way!

**Comment by jkim0120** [comment]
@gjtorikian great thanks! I'll keep that in mind. Is there someone I can keep in contact with to hear about any updates on this issue?

**Comment by gjtorikian** [comment]
Sure—I'll send you an email when we've got it sorted out.

**Comment by jkim0120** [comment]
Thanks!

**Comment by gjtorikian** [comment]
@jkim0120 I believe this should be fixed. Give it another try if you like.

**Comment by jkim0120** [comment]
Thanks for the update, but the 502 errors are making a comeback

**Comment by paulodero** [comment]
@jkim0120 How was this fixed? I'm getting the same issues.
