### ISSUE TITLE
Cannot Create Public Repo For Organisation

### ISSUE THREAD

**Issue by veesa** [octokit/octokit.rb#736]
I have the following code to create a repository within an organisation:

```
client.create_repository 'canaries_repo', {:description => 'Norwich City Football Team Repo',
                                                   :private => 'false',
                                                   :has_issues => 'true',
                                                   :has_wiki => 'true',
                                                   :has_downloads => 'true',
                                                   :organization => 'football',
                                                   :team_id => club[:id],
                                                   :auto_init => 'true'}
```

The repository is created, but it is private, not public. The `has_issues` is `true` and so is `has_wiki` as I can see when I curl back the repo. Can you give me a clue as to where to start debugging this? Thanks!

**Comment by tarebyte** [comment]
@veesa for a public repo you don't have to set private to `false` be default `private` is set to false. https://developer.github.com/v3/repos/#create

That doesn't really explain your issue though

**Comment by veesa** [comment]
As a workaround leaving the parameter out does create a public repo. It's not really a fix, though.

**Comment by pengwynn** [comment]
@veesa We should do a better job of validating this server-side, but you're passing `"false"` as a string, which is truthy on our end. 

Can you try passing `:private => false` and letting me know if you're still seeing the issue?

**Comment by veesa** [comment]
@pengwynn Passing `:private => false` solves the issue.  Thanks!

**Comment by pengwynn** [comment]
:zap:
