### ISSUE TITLE
Is It Possible To Set User Password via Octokit.rb?

### ISSUE THREAD

**Issue by veesa** [octokit/octokit.rb#740]
I am programmatically creating users and I would like to be able to set their initial passwords.

If I understand this documentation correctly the [password is writeable](http://www.rubydoc.info/gems/octokit/Octokit%2FConfigurable%3Apassword%3D)

The code I have finishes with exit 0 but when I try and login as a user that was just created, I cannot, I get the error 'Incorrect username or password.'

```ruby
users = @client.all_users()
users.each do |user|
  user[:password] = ("passworD1")
end
```
Can you please let me know if there is a way to accomplish setting the password of a user?

Thanks!

**Comment by joeyw** [comment]
@veesa The writable part is referring to the ruby variable, meaning you can set the password for the Octokit client to use when authenticating requests made by Octokit. There isn't any support for updating a user's password from the API that I know about, even on the enterprise side of things, in the public GitHub API at least.
