### ISSUE TITLE
Do you accept pull requests for development preview APIs?

### ISSUE THREAD

**Issue by stmllr** [octokit/octokit.rb#741]
e.g. `Octokit::Client::Issues::lock_issue()` https://developer.github.com/v3/issues/#lock-an-issue
is not yet implemented in octokit.rb

Currently, some development preview APIs are implemented, e.g. [`Octokit::Client::Repositories::protect_branch()`](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/repositories.rb#L498)

Just want to be sure...

**Comment by pengwynn** [comment]
@stmllr you bet. Maybe https://github.com/octokit/octokit.rb/pull/722 will provide some prior art?

**Comment by stmllr** [comment]
@pengwynn thanks. though #722 handles source import, not lock_issue. PR will follow
