### ISSUE TITLE
Update documentation to reflect permissions are attached to team:repo now, not to team

### ISSUE THREAD

**Issue by alexanderdean** [octokit/octokit.rb#743]
Referring to:

1. http://octokit.github.io/octokit.rb/Octokit/Client/Organizations.html#add_team_repository-instance_method
2. http://octokit.github.io/octokit.rb/Octokit/Client/Organizations.html#create_team-instance_method

The `:permission => 'push'` example should be moved from the second method (`create_team`) to the first (`add_team_repository`).

**Comment by joeyw** [comment]
Updated 466b971f35da3983c0345ced492e672f9ca1bfb0
