### ISSUE TITLE
Intermittent error when invoking octokit 

### ISSUE THREAD

**Issue by beattiedb** [octokit/octokit.rb#744]
When executing the startup lines of code in a ruby program I occasionally get an error when trying to execute line 6 that is doing a 'require oktokit'  3.4.0

Line 1: gem 'ecapi', '=1.1.172'
Line 2: gem 'octokit', '=3.4.0'
Line3:
Line 4: require 'ec'
Line5: require 'octokit'
Line 6: require 'pp'
Line 7: require 'mysql2'
...

The code is executed every 10 minutes and fails perhaps once every couple of hours.
The error looks as follows:
```
/opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/stub_specification.rb:131:in `missing_extensions?': undefined method `missing_extensions?' for nil:NilClass (NoMethodError)
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/basic_specification.rb:67:in `contains_requirable_file?'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:937:in `block in find_inactive_by_path'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:936:in `each'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:936:in `find'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:936:in `find_inactive_by_path'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:187:in `try_activate'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/addressable-2.3.8/lib/addressable/idna/native.rb:19:in `<top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/addressable-2.3.8/lib/addressable/idna.rb:20:in `<top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/addressable-2.3.8/lib/addressable/uri.rb:20:in `<top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/addressable-2.3.8/lib/addressable/template.rb:20:in `<top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/sawyer-0.5.5/lib/sawyer/agent.rb:2:in `<top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/sawyer-0.5.5/lib/sawyer.rb:17:in `block in <top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/sawyer-0.5.5/lib/sawyer.rb:17:in `each'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/sawyer-0.5.5/lib/sawyer.rb:17:in `<top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/octokit-3.4.0/lib/octokit/client.rb:1:in `<top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/octokit-3.4.0/lib/octokit.rb:1:in `<top (required)>'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/ecmdrAgent/agent.SGV78J7G24EA90TL.run-1716751-88181962.cmd:5:in `<main>'
```
Any idea what may be causing this problem?

**Comment by pengwynn** [comment]
> The code is executed every 10 minutes and fails perhaps once every couple of hours.

Are you changing ruby versions out from under running code? If it loads once successfully, that would indicate an environment problem.

**Comment by beattiedb** [comment]
To my knowledge we only have and run version of Ruby on this system.

**Comment by beattiedb** [comment]
Do you have any thoughts on why this problem is happening?

**Comment by joeyw** [comment]
@beattiedb Can you log `puts $LOAD_PATH` in your script and provide the output when it runs fine and also when it crashes?

**Comment by beattiedb** [comment]
I finally put in the puts and obtained a failed run as well as successful runs. I've attached a file showing the  $LOAD_PATH results.
[Octokit_Load_Paths_Results.txt](https://github.com/octokit/octokit.rb/files/259954/Octokit_Load_Paths_Results.txt)

**Comment by joeyw** [comment]
@beattiedb That was not as helpful as I had hoped. 

Going back to your stack trace it is showing addressable trying to load native idn. Addressable does a check to try to load the native version See https://github.com/sporkmonger/addressable/blob/addressable-2.3.8/lib/addressable/idna.rb#L20

In your case you are not getting  a load error, it is a another exception when loading the native, so it is not rescuing and falling back on the pure ruby implementation provided by addressable. As far as it working sometimes, that puzzles me. Currently the only explanation I have for that is rubygems is loading different versions, which does not seem possible if you are only using one ruby versions.

I believe the root cause is a bug in rubygems. I think if you type `gem environment` you will see Rubygems < v2.5.2? There was an additional guard added to 2.5.2. If possible I would try bumping rubygems to see if it resolves the issue. 

 I would be curious to see `gem environment` output before each run.

**Comment by beattiedb** [comment]
We have rubygems 2.4.5 in place on the system running this code. It's interesting then that it succeeds so frequently based on your comment. It only fails around 1 time out of a hundred of more times ran.
I will discuss with the system owner about upgrading rubygems to >= 2.5.2.

**Comment by joeyw** [comment]
If you aren't able to I would open an issue over in the rubygems project they may be more helpful than me on this.

**Comment by joeyw** [comment]
Closing this out as it's rather stale. If there is any followup needed feel free to comment or open a new issue referencing this.
