### ISSUE TITLE
CI Issue

### ISSUE THREAD

**Issue by joeyw** [octokit/octokit.rb#749]
@pengwynn Can you check the CI settings? Something seems off. Builds are going through but it says octokit isn't activated on travis. /cc #748 

![image](https://cloud.githubusercontent.com/assets/478247/15033825/fa3c4140-1234-11e6-9fbb-07476ba66de2.png)

**Comment by pengwynn** [comment]
@joeyw I clicked the green button. Not sure what happened on the other end of the Internet. We good?

**Comment by joeyw** [comment]
![image](https://cloud.githubusercontent.com/assets/478247/15059993/875d9ac6-12ec-11e6-9217-2bc8eba337fd.png)

Looks good now, thanks :+1:
