### ISSUE TITLE
How do I call add_collaborator with pull only permission?

### ISSUE THREAD

**Issue by radar** [octokit/octokit.rb#756]
I'm trying to add a collaborator by making this call:

``` ruby
client.add_collab('radar/rails_4_in_action', login)
```

However, this adds the collab with write permission, when I want them to be added with read (pull) permission. So I try this:

``` ruby
client.add_collab('radar/rails_4_in_action', login, permission: "pull")
```

This does not even add the user to the repo. 

What's the correct incantation for this method?

**Comment by radar** [comment]
Ok, so supposedly the `permission` thing is only allowed for organisations. There is no indication of this in the API response; it's just a standard 204 response, which is what you'd expect from a _successful_ addition of a collaborator.

Is it possible to change this endpoint to allow the `permission` parameter for users as well as organisations? If not, could the endpoint return something other than a 204 status when a user attempts to add another collaborator with the `permission` parameter? I think returning a 204 is misleading here.

**Comment by estebangarcia** [comment]
I know this is old, but it seems that the third parameter needs to be a hash: https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/repositories.rb#L312

**Comment by estebangarcia** [comment]
I'm pretty sure that you already solved your issue. But I'm sending the permission inside a hash and it works just fine.

`client.add_collab("org/repo", "user", {:permission => :pull})`

**Comment by radar** [comment]
@estebangarcia `client.add_collab('radar/rails_4_in_action', login, permission: "pull")` will pass the `permission: "pull"` bit through as a Hash. In Ruby, you can leave the hash brackets off.
