### ISSUE TITLE
Error when attempting to set permission with add_team_repository

### ISSUE THREAD

**Issue by franfabrizio** [octokit/octokit.rb#757]
When I call this on my GitHub Enterprise instance:

client.add_team_repository(team.id, "myorg/#{repo.name}", :permission => 'pull')

I get this error:

/Users/fran/.rvm/gems/ruby-2.3.0@octokit/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': PUT https://<my.enterprise.github.url>/api/v3/teams/<my team id>/repos/<my organization>/<my repo name>: 415 - If you would like to help us test the Direct Org Membership API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details. // See: https://developer.github.com/enterprise/2.4/v3 (Octokit::UnsupportedMediaType)
    [SNIP]
    from /Users/fran/.rvm/gems/ruby-2.3.0@octokit/gems/octokit-4.3.0/lib/octokit/client/organizations.rb:423:in`add_team_repository'

When I remove the :permission => 'pull' all works fine, but I'd like to be able to explicitly set the permission.  I couldn't find anything online about the Direct Org Membership API at that URL.  Is this a GitHub issue or an Octokit issue?  Am I specifying the permission correctly in the call?

**Comment by allandrick** [comment]
Hi @franfabrizio,

FYI this is working for me in octokit (4.3.0) - the only syntactic difference is I pass the permission thusly:

```ruby
        status = client.add_team_repo(teamId, sprintf("%s/%s", org, repo), {
                :permission => perm
                })
```

**Comment by jcronk** [comment]
I just had this same issue, but it has a simple solution.  Go to the URL in the error message and find the custom media type they want you to send, then just add `accept: 'application/some.custom.type'` to your options.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since it seems like this is likely resolved with one of the two responses. If not, please don't hesitate to reopen the issue @franfabrizio.
