### ISSUE TITLE
Support the Reactions API preview

### ISSUE THREAD

**Issue by pengwynn** [octokit/octokit.rb#759]
Since folks often ask if patches are accepted for Preview APIs - **we most definitely do**.

You can read more about the [Reactions API Preview](https://developer.github.com/changes/2016-05-12-reactions-api-preview/) on the GitHub Developer blog.

**Comment by malamel** [comment]
Thank

**Comment by SophieDeBenedetto** [comment]
seems like this issue was closed by this PR https://github.com/octokit/octokit.rb/pull/760

**Comment by tarebyte** [comment]
Yes it was 😃  thanks for pointing that out @SophieDeBenedetto!
