### ISSUE TITLE
Support verification key in commit

### ISSUE THREAD

**Issue by acidprime** [octokit/octokit.rb#762]
```json
    "comment_count": 0,
      "verification": {
        "verified": true,
        "reason": "valid",
        "signature": "-----BEGIN PGP MESSAGE-----\n...\n-----END PGP MESSAGE-----",
        "payload": "tree 6dcb09b5b57875f334f61aebed695e2e4193db5e\n..."
      }
```
I think the GPG key stuff is new thus the gem doesn't support but its in the official API spec

https://developer.github.com/v3/repos/commits/

**Comment by pengwynn** [comment]
You should be able to get this during the API preview period by passing the preview media type explicitly:

    client.commits("me/my-repo", :sha => "deadbeef", :accept => "application/vnd.github.cryptographer-preview")

**Comment by acidprime** [comment]
Thanks this worked
