### ISSUE TITLE
Is it possible to pluck an attribute from all issues, without loading each one fully?

### ISSUE THREAD

**Issue by onebree** [octokit/octokit.rb#766]
I want to query all closed issues for Rails, grabbing the total size and ids of each issue. But as I found out, with `auto_pagination` enabled, grabbing 8000+ records takes quite some time.

```ruby
client = Octokit::Client.new(
  access_token: ENV["GITHUB_ACCESS_TOKEN"],
  auto_paginate, true
)

issues = client.list_issues("rails/rails", state: "closed")
```

I want to do something similar that ActiveRecord supports, like so:

```ruby
repo.issues.pluck(:id)
```

**Comment by tarebyte** [comment]
@onebree unfortunately the GitHub API doesn't really support just grabbing the `id` of every issue to make it faster like in ActiveRecord.

However, if you want to just grab all of the ids from the response, you could do something like this.

```ruby
issue_ids = client.list_issues("rails/rails", state: "closed").map(&:id)
```

**Comment by onebree** [comment]
Thank you for the help, @tarebyte. I will close this issue now.

If I had further questions, is there a chat or Google Groups forum I can post to?

**Comment by tarebyte** [comment]
> If I had further questions, is there a chat or Google Groups forum I can post to?

Nope! Feel free to open as many question issues as you'd like 😁
