### ISSUE TITLE
Octokit::Client#issues size returns 30 if page<1

### ISSUE THREAD

**Issue by onebree** [octokit/octokit.rb#767]
I am not sure if this is a bug or intended, but consider the following scenario:

```ruby
issues_a = Octokit.issues("rails/rails", state: "closed", page: 0)
issues_b = Octokit.issues("rails/rails", state: "closed", page: -1)
puts issues_a.size, issues_b.size
# => 30
# => 30
```

Now, it makes sense if `-1` represents the last page, but `0` does not make sense as page numbers begin at 1.

**Comment by tarebyte** [comment]
So if the page you specify is less than or equal to 1, the GitHub API will just give you the first page of results.

I think it's just a way of handling weird cases like the one you pointed out.

**Comment by onebree** [comment]
Thank you, I was not sure if it was a bug, so I wanted to file in case.
