### ISSUE TITLE
Failure/Error: raise Octokit::MissingContentType.new(msg)

### ISSUE THREAD

**Issue by ZeroChaos-** [octokit/octokit.rb#768]
I get this on armv7:

Failures:

  1) Octokit::Client::Releases handling release assets .upload_release_asset guesses the content type for an asset
     Failure/Error: raise Octokit::MissingContentType.new(msg)

     Octokit::MissingContentType:
       Please pass content_type or install mime-types gem to guess content type from file
     # ./lib/octokit/client/releases.rb:158:in `rescue in content_type_from_file'
     # ./lib/octokit/client/releases.rb:152:in `content_type_from_file'
     # ./lib/octokit/client/releases.rb:87:in `upload_asset'
     # ./spec/octokit/client/releases_spec.rb:97:in `block (4 levels) in <top (required)>'

Finished in 1 minute 17.42 seconds (files took 3.83 seconds to load)
598 examples, 1 failure

**Comment by pengwynn** [comment]
@ZeroChaos- what does `gem list mime-types` show?

**Comment by ZeroChaos-** [comment]
It shows nothing. Absolutely nothing. Despite the fact that mime-types is obviously listed in the Gemfile it wasn't in the deps for the gentoo ebuild :-)

Installing mime-types fixes the problem, thanks for the obvious help :-)
