### ISSUE TITLE
Faraday::ConnectionFailed (execution expired)

### ISSUE THREAD

**Issue by albertnetymk** [octokit/octokit.rb#769]
I am using lazy initialization for client, sth like:

```
def self.client
  @@client ||= Octokit::Client.new :access_token => 'my_token'
end
```
I think that's the reason why I am getting this expiration error. How could I detect the connection is expired? Or, what's the recommended way of saving `client`?

**Comment by joeyw** [comment]
The lazy initialization isn't affecting the connection times. No requests are made at this point.

I believe Faraday has strict timeouts underneath, perhaps you could explore more lenient timeouts by overriding the defaults and adjust to your needs. For example:

```ruby
Octokit::Client.new(
  :access_token => 'my_token',
  :connection_options => {
    :request => {
      :timeout => 15,
      :open_timeout => 15
    }
  }
)
```

**Comment by albertnetymk** [comment]
Possibly, I didn't make myself clear.
```
GH.client.create_status
# later on, possibly another request
GH.client.create_status
```
The first `create_status` call would open the connection, if the connection is not established yet. If the lazy initialization shown above is used, the second call to `create_status` could encounter the expiration failure, couldn't it?

Anyway to check the status of the connection used by the `client`? Then, I know when to re-initialize `client` to start a new connection.

**Comment by pengwynn** [comment]
> If the lazy initialization shown above is used, the second call to create_status could encounter the expiration failure, couldn't it?

No, the expiration is per network call. @albertnetymk if you're still running into this, could you send us some details on your remote address [to support](https://github.com/contact) so we can help troubleshoot?

**Comment by albertnetymk** [comment]
I see. Thanks for the explanation. I tried the lazy initialization again, and the problem doesn't seem to manifest any more.
