### ISSUE TITLE
Do not treat redirects as 'normal' responses

### ISSUE THREAD

**Issue by grosser** [octokit/octokit.rb#771]
Atm redirects return objects that return nil for everything, which makes consumers of these objects fail with strange errors (response.commits/files is nil) ... please raise an `Octokit::Redirected` or similar error when the response code is 300..399 ... not sure about 304 ...

Alternatively it could follow-redirect, but that means an extra request which in most cases is easily avoided ... could be part of a followup-PR to make this optional

I can open a PR to fix this if that sounds good.

hotfix:

```
# we don't want to forever pay the price of redirects, but make users fix them
class Octokit::RedirectAsError < Faraday::Response::Middleware
  private
  def on_complete(response)
    if [301, 302].include?(response[:status].to_i)
      raise Octokit::RepositoryUnavailable, response
    end
  end
end

Octokit.middleware = Faraday::RackBuilder.new do |builder|
  ...
  builder.use Octokit::Response::RaiseError
  builder.use Octokit::RedirectAsError
  ...
  builder.adapter Faraday.default_adapter
end

```

**Comment by pengwynn** [comment]
@grosser are you using the [`FollowRedirects`](https://github.com/octokit/octokit.rb/blob/719483524b930146580a997284fdd9719a5b0cdf/lib/octokit/middleware/follow_redirects.rb) middleware and still getting nil objects? Are you looking for an alternative behavior that would simple raise? (I'm not sure why.)

**Comment by grosser** [comment]
Not using follow redirects, so I get a redirect as response ... which breaks the code that reads commits etc ... and checking for redirect is a bit strange at this code level ...

So yes, there is a workaround, but I'd prefer if it raised so our repo urls get fixed and not hidden behind invisible redirect.

**Comment by pengwynn** [comment]
> Not using follow redirects

Ah, gotcha. I understand your motivation to want to update URLs and not make extra network hops indefinitely. You're always free to wire up a custom middleware like you sketched out above, but raising an error seems a bit heavy handed to include as an option in the main library.

A couple of other alternatives to think about:

- You could follow redirects and use the `.rels[:self].href` to see if the resource had been renamed.
- You could add a callback option to the `FollowRedirects` middleware to have it notify you when something was renamed.

**Comment by grosser** [comment]
If you do not have follow redirects set up, would you expect to get a
normal response that is a redirect (has none of the fields you'd expect) or
blow up (like all other unusual responses ... 400-500) ?

Atm it returns an unusable response object which I think is weird ...

**Comment by kytrinyx** [comment]
I think this would make sense as opt-in middleware. I don't think we could add it as the default behavior, at least not until we do a major release, since that would be a breaking change.
