### ISSUE TITLE
Making a new commit takes 5 API calls

### ISSUE THREAD

**Issue by camertron** [octokit/octokit.rb#772]
This is probably a limitation of the Github API itself, so please let me know if I should be asking somewhere more appropriate.

I maintain a library that connects Github and Transifex, a translation management system. [Here's](https://github.com/lumoslabs/txgh/blob/master/lib/txgh/github_api.rb#L36) the method that makes a commit and updates a git ref using Octokit. At the minimum it takes 5 API calls to do this, which I think is fairly excessive. This is especially true when one considers the number of steps it takes to make a commit via the command line (i.e. `git commit -m "message"`). I'm now running up against the rate limit for my access token.

Am I missing something? Is there an easier way to commit to a github repo and update a ref?

**Comment by pengwynn** [comment]
@camertron As you discovered, REST is a poor abstraction for manipulating Git objects directly. Have you checked out the higher-level [Repository Contents API](https://developer.github.com/v3/repos/contents/)?

**Comment by camertron** [comment]
@pengwynn no, I didn't know about it! Thanks, I'll check it out.

**Comment by camertron** [comment]
@pengwynn ok, I looked over the documentation for the repository contents API, but I don't think it will work for my use case. For one thing, the endpoint that updates a file requires you to give it the blob SHA of the file you're replacing, or as the docs put it, "The blob SHA of the file being replaced." It doesn't make sense to me that the SHA of the existing file is something the API needs to know - why doesn't it just create a new commit on the branch you pass in? For another thing, it's not straightforward to get the blob SHA for a given file, since the blob API doesn't let you look up blobs by path. I'd have to fetch the entire tree and loop over the files to find the specific one I care about.

**Comment by ymendel** [comment]
@camertron: I worked on the repo-contents API (years ago), and I can give you some background and thoughts about the blob-SHA requirement.

The idea is a sort of locking, keeping you from overwriting (or removing) file changes you're not expecting. So when you try to update (or delete) a file, you have to verify that you know the current file contents. If you're correct, you get to change the file. If not, you get a response that should get you to look at the current file contents and see if your change is still what you want.

About getting the blob SHA, you're correct that [the get-a-blob endpoint][get-blob] doesn't allow lookup by path. But [the get-contents endpoint][get-contents] does, and it returns the SHA. If you have the repository locally, you can get the SHA by a command like `git ls-tree HEAD <filename>`. But if you know the file contents, you can compute the SHA on your own. It's the SHA1 of the string "blob " followed by the length of the contents, a null character, and then the contents. So if the file contains the string "hello", the blob SHA would be

```
$ printf "blob 5\0hello"| sha1sum
b6fc4c620b67d95f953a5c1c1230aaab5db5a1b0  -
```

(This is admittedly kind of clunky.)

[get-blob]: https://developer.github.com/v3/git/blobs/#get-a-blob
[get-contents]: https://developer.github.com/v3/repos/contents/#get-contents

**Comment by camertron** [comment]
@ymendel thanks for the thorough explanation! I did consider using the "get contents" endpoint but didn't want to incur the bandwidth/speed penalty of actually downloading the file. The locking aspect you mentioned totally makes sense though, and I suppose it's a reasonable price to pay for minimizing the number of API calls my library has to make (unfortunately I don't have a local clone I can use). I have long wished for a way to (safely) query git data like you might query a relational database, but sadly I know of no such technology.
