### ISSUE TITLE
[Question] Can we use this library for GitLab ?

### ISSUE THREAD

**Issue by ahmadhasankhan** [octokit/octokit.rb#776]
Hi,

Is octokit is also compatible with GitLab ? if not then can someone suggest some similar library for gitlab please.

Thanks you.

**Comment by tarebyte** [comment]
Hi @ahmadhasankhan, the octokit.rb is not compatible with GitLab. And I'm not sure of a library that is.

**Comment by alaxalves** [comment]
@ahmadhasankhan We have this, but you might have already found one :smile:  : https://github.com/narkoz/gitlab

**Comment by yamlCase** [comment]
@ahmadhasankhan he may have found one, but I hadn't.  Thanks for posting!
