### ISSUE TITLE
How do I get a diff for one file across two commits?

### ISSUE THREAD

**Issue by marcamillion** [octokit/octokit.rb#781]
I know how to get the commit for a file via the API, along with the SHA and all that nice stuff, and I know how to get all the changes in a diff between two sets of commits.

But, what I am struggling with is how do I get the diff of a file in 1 commit or the diff of the same file across two commits (even when there are multiple commits in a diff).

For instance, in [this commit](https://github.com/rails/rails/commit/ea759cb76161a7a0003c3cd3b38a8a125a99af3c#diff-a215bfc911ab0913d92695a0f20310ef), say I wanted just the `, :counter_sql` along with the documentation changes at the top in the `activerecord/lib/active_record/associations.rb`.

Assuming I have the two SHAs for both commits in two variables `a` and `b`, I would do something like this:

```
client = Octokit::Client.new(access_token: ENV["MY_ACCESS_TOKEN"])
comparison = client.compare("rails/rails", a, b)
```

This issue is that this results in a diff between both commits, which includes changes to many other files and a lot of information I don't want.

All I want is the diff from this specific file across these two commits. So, ideally, I would have loved to be able to do something like this:

```
comparison = client.compare("rails/rails", a, b, path: "activerecord/lib/active_record/associations.rb")
```

Which would just return the specific diffs for this one file (and not other diffs for other files within the commit).

But that doesn't work like I would expect.

How do I do what I am trying to do, or is that not possible?

**Comment by kytrinyx** [comment]
@marcamillion It's been a while, so I don't know if you found a solution to this. Your best bet is probably to email GitHub support to ask if this is possible with the API. If it is, then open an issue here and we can help you translate that to use the octokit.
