### ISSUE TITLE
all_users should auto paginate

### ISSUE THREAD

**Issue by Karamorf** [octokit/octokit.rb#783]
Why have everyone reprogram how to do the pagination? The gem should do this in the all_users call:

def all_users()
   users = []
   id = 0
   enum = Enumerator.new do |y|
     loop do
       if users.empty?
         users = paginate "users", :since => id
         break if users.empty?
       end
       u = users.pop.to_h
       id = u[:id] if u[:id] > id
       y << u
     end
   end
   return enum
 end

**Comment by pengwynn** [comment]
That method supports [auto pagination](https://github.com/octokit/octokit.rb#auto-pagination), but as the docs point out, you'll likely want a different approach. Traversing all GitHub users with our API rate limits will take days.
