### ISSUE TITLE
How do I get the total count of resources without having to paginate through all of them?

### ISSUE THREAD

**Issue by csgyuricza** [octokit/octokit.rb#787]
According to the documentation:

> Many GitHub API resources are paginated

I cannot use the obvious **.length** or **.count** because they only return the length and count of the items in the page. Do I really need to paginate through all pages in order to get a total count? It seems like there should be a simple method that returns the total count. I couldn't this anywhere it in the documentation.

Is there a simple way to get the total count of a paginated resultset?

**Comment by csgyuricza** [comment]
I'm specifically referring to methods that return an Array of Sawyer::Resource objects, for example the **pull_requests**. Those are the ones I'd like to have a total count without having to paginate through all pages.

**Comment by kytrinyx** [comment]
The GET Repository endpoint (https://developer.github.com/v3/repos/#get) has an `open_issues_count` field, but not an `open_pull_requests_count` field.

The best you can do, as far as I can tell, is to get the `:last` related link from the header and compute the number from that. Something like this:

```
require 'octokit'

client = Octokit::Client.new(:access_token => ENV['ADMIN_ORG_TOKEN'])

client.pull_requests('rails/rails')
if client.last_response.rels[:last].nil?
  total = last_request.data.count
else
  per_page = client.last_response.data.count
  last_page = client.last_response.rels[:last].href[/\d+$/, 0].to_i

  # get the last page so you can count the items on it
  client.last_response.rels[:last].get
  total = (per_page * (last_page - 1)) + client.last_response.data.size
end

puts total.inspect
```

The GitHub support folks might know more about whether the API has a way of returning the data that you want. If it does, feel free to reopen this with more information so we can help you get that information via the octokit client.
