### ISSUE TITLE
Access Tokens in download_url field from GitHub.connect.contents for a private repo.

### ISSUE THREAD

**Issue by joecannatti** [octokit/octokit.rb#788]
Hi,

  I'm not able to find any documentation about the `download_url` field returned from `GitHub.connect.contents` for a private repo.

That link contains a token that makes the file accessible. Best I can tell, (from experimenting) that token is specific per file, and never expires.

I'm able to access it from any machine via `curl`.

How does that token work? Does it ever expire? Can I audit any use of the link? Can I force previously created `download_url` links to expire?

Thanks!
Joe

**Comment by niskajace8** [comment]
idk

**Comment by RayPylant** [comment]
idk either thats what i am asking any of you so we can put our heads together. to come up with something, i have been going through this since my post and still came up with a dead end,

**Comment by AutoshopR** [comment]
Help

**Comment by Sherie1988** [comment]
gitignore

**Comment by kytrinyx** [comment]
@joecannatti I'm so sorry we missed this for (literally) a year. That's unacceptable, I promise to do better.

I am pretty sure that those tokens expire. That said, if you ask support@github.com, they'll be able to give you all the details about it.

I'm going to go ahead and close this (so sorry again!) 🌷
