### ISSUE TITLE
branch protection "who can push to this branch" missing/not working?

### ISSUE THREAD

**Issue by allandrick** [octokit/octokit.rb#798]
G'day,

I'm trying out the branch protection preview in 4.3.0 and have figured out most of what I need with the sole exception of ticking the box "Restrict who can push to this branch" and assigning the teams or people with push access... that last bit I cannot make work.  I even tried crafting the URL manually and using client.PATCH and client.PUT... here's my working code - does anyone know what would I need to add to assign push access to a protected branch?  

``` ruby
def protectBranch(client, org, repo, branch, team)

        puts magenta(sprintf("Protecting branch %s on repo %s/%s to team %s", branch, org, repo, team))
        begin
                # https://developer.github.com/v3/repos/branches/#update-branch-protection
                client.protect_branch(sprintf("%s/%s", org, repo), branch,
                        {
                                :include_admins => true,
                                :strict => true,
                                :contexts => [],
                                :enforcement_level => "everyone",
                        },
                        {
                                :accept => "application/vnd.github.loki-preview+json"
                        }
                )
                rescue Exception => e
                        puts red(sprintf("ERROR: Unable to protect branch %s on repo %s/%s to team %s", branch, org, repo, team))
                        puts red(sprintf("ERROR: response from server was: %s", e))
                        exit -1
        end
end

```

I think what I need to pass is something like this along with the above:

``` ruby
        :restrictions => {
            :teams => [
                    team
            ]

```

but I can't figure it out.  Appreciate any guidance - love the API so far!  #notadeveloper

Cheers,

Leigh

**Comment by Budgerous** [comment]
Hey, @allandrick,

I don't know if you're still stuck here, but I had the same problem a couple of weeks ago.

Basically, if you check the [Github API documentation](https://developer.github.com/v3/repos/branches/#update-branch-protection), Octokit only covers the `required_status_checks` part of the branch protection functionality. So, with Octokit, you won't be able to do that part.

Personally, what I did was use [RestClient](https://github.com/rest-client/rest-client) and send something like:

`RestClient.put "https://api.github.com/repos/#{repository}/branches/#{branch}/protection",
{required_status_checks: nil, restrictions: {users: [], teams: []}}.to_json,
{accept: "application/vnd.github.loki-preview+json", Authorization: "Token #{token}"}`

This way, I was able to lock branch `master` for all users. You can use something like this to only allow that team to push to this branch.

Hope this works for you. Good luck

**Comment by jcii** [comment]
So...it looks like the code in octokit.rb is more current than 4.3.0, the release from March. Does someone from github know when they might release a newer version of octokit.rb?

**Comment by tarebyte** [comment]
@jcii not sure, but if you want to use the latest and greatest you could always do

```ruby
gem 'octokit', :git => 'https://github.com/octokit/octokit.rb.git', :ref => ''c1e66093eeb499c59e49212ca10c2a4efc356836"
```

**Comment by RayPylant** [comment]
but you did already list at one point "everyone" quote unquote

**Comment by allandrick** [comment]
Hi @Budgerous,

I did try that but get an error: wrong number of arguments (3 for 1..2)...  we are upgrading our github enterprise soon - hopefully the new version will have it updated and I'll update octokit as well.

Thanks for the suggestions though!

**Comment by kytrinyx** [comment]
@allandrick It's been a few months on this one. Did you get this sorted out?

I'm going to go ahead and close this, but if it's not sorted, please reopen it and we can figure out exactly what is hurting and how to fix it.
