### ISSUE TITLE
user.rels[:repos].get doesn't paginate

### ISSUE THREAD

**Issue by netiko** [octokit/octokit.rb#800]
user.rels[:repos].get(:query => { :sort => 'created_at', :direction =>  'asc'}).data should call paginate method in order to get all repositories and not only 30

**Comment by pengwynn** [comment]
The low-level HTTP interface is simple by design. You can work around this by passing the URL to `Client#paginate`:

```ruby
client.paginate(user.rels[:repos].href)
```
