### ISSUE TITLE
Add support for protected branches API

### ISSUE THREAD

**Issue by aspiers** [octokit/octokit.rb#802]
As everyone knows, [GitHub recently released a new code review system](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features).  It's now possible to protect a branch so that a PR to that branch can only be merged after it has been approved by at least one reviewer and had no disapprovals.  However AFAICS it's not possible to get or set this configuration parameter via the API, let alone via Octokit (I've filed isaacs/github#781 for that).  So this is a placeholder issue for updating Octokit once that API has been provided.

**Comment by kytrinyx** [comment]
I believe this is now supported in the API: https://developer.github.com/v3/repos/branches/

It doesn't look like it has been added to octokit yet.

**Comment by pengwynn** [comment]
@kytrinyx I think @tarebyte added those methods [here](https://github.com/octokit/octokit.rb/blob/ad74f84e818ee15d2e49422d51978a40b2d957a0/lib/octokit/client/repositories.rb#L532-L570).

**Comment by bigwormit** [comment]
W hat do i need to do

**Comment by kytrinyx** [comment]
@pengwynn there are a lot more endpoints in the API docs than what we have there. I'll take a look at what's missing.

@bigwormit I don't understand your question. Would you please elaborate?

**Comment by bigwormit** [comment]
Pa11y

**Comment by jblac** [comment]
I use protected branches myself, I'll be updating my PR #890 with the necessary endpoints for the reviewers' portion of this, but can definitely look into building out more options in different PR's if we can figure out functionality and what we're missing in octokit that's currently available in the API.

**Comment by PhyoWaiMaung92** [comment]
#802

**Comment by aspiers** [comment]
Thanks for the response @nickfloyd.  I don't *personally* have a strong need for this right now, and unless that changes, sadly probably won't have time to implement it any time soon.  But of course I'll come back here if the situation does change.

On a more general note, my personal recommendation (which of course you are free to take or leave) is that it is often more productive to leave issues open until there is a clear resolution (e.g. a fix, or a decision such as "we're not going to implement this").

When issues or feature requests are marked as closed without resolution, then people are more likely to miss them, resulting in duplicate reports.  And people searching for ways to contribute are more likely to miss them too.  Here's [someone else's blog post on the same topic](https://www.reddit.com/r/emacs/comments/j9hi9x/an_example_of_why_bug_reports_and_feature/).

However I understand it is annoying to have open issues going nowhere.  IMHO one solution for this is to label short-lived and long-lived issues differently to distinguish them.  Another is assigning issues to different milestones. This makes it clear to users which issues are likely to be fixed sooner rather than later.

Hope this is useful food for thought.  Thanks again!
