### ISSUE TITLE
farday adapter nethttppersitent: uninitialized  constant process

### ISSUE THREAD

**Issue by prashantkb** [octokit/octokit.rb#807]
when i start rails server..
it is giving this error

C:\clinico>rails s
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/middleware.rb:2
0:in `new': missing dependency for Faraday::Adapter::NetHttpPersistent: uninitia
lized constant Process::RLIMIT_NOFILE (RuntimeError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ra
ck_builder.rb:48:in `build'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ra
ck_builder.rb:163:in `block in to_app'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ra
ck_builder.rb:163:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ra
ck_builder.rb:163:in `inject'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ra
ck_builder.rb:163:in `to_app'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ra
ck_builder.rb:152:in `app'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ra
ck_builder.rb:139:in `build_response'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/co
nnection.rb:377:in `run_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/co
nnection.rb:140:in `get'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-core-6.1.5/lib/neo4j-s
erver/cypher_session.rb:50:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-core-6.1.5/lib/neo4j-s
erver/cypher_session.rb:6:in `block in <module:Server>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-core-6.1.5/lib/neo4j/s
ession.rb:125:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-core-6.1.5/lib/neo4j/s
ession.rb:125:in `create_session'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-core-6.1.5/lib/neo4j/s
ession.rb:110:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-7.1.4/lib/neo4j/railti
e.rb:107:in `block in open_neo4j_session'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-7.1.4/lib/neo4j/railti
e.rb:120:in `block in wait_for_value'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-7.1.4/lib/neo4j/railti
e.rb:117:in `wait_for_value'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/r
ailtie.rb:193:in `public_send'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/r
ailtie.rb:193:in `method_missing'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-7.1.4/lib/neo4j/railti
e.rb:103:in `open_neo4j_session'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-7.1.4/lib/neo4j/railti
e.rb:160:in `block (2 levels) in <class:Railtie>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-7.1.4/lib/neo4j/railti
e.rb:159:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/neo4j-7.1.4/lib/neo4j/railti
e.rb:159:in `block in <class:Railtie>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/i
nitializable.rb:30:in `instance_exec'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/i
nitializable.rb:30:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/i
nitializable.rb:55:in `block in run_initializers'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in e
ach_strongly_connected_component'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connect
ed_component_from'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongl
y_connected_component'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connect
ed_component'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/i
nitializable.rb:54:in `run_initializers'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/a
pplication.rb:352:in `initialize!'
        from C:/clinico/config/environment.rb:5:in `<top (required)>'
        from C:/clinico/config.ru:3:in `require_relative'
        from C:/clinico/config.ru:3:in `block in <main>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.1/lib/rack/builder.
rb:55:in `instance_eval'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.1/lib/rack/builder.
rb:55:in `initialize'
        from C:/clinico/config.ru:in `new'
        from C:/clinico/config.ru:in `<main>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.1/lib/rack/builder.
rb:49:in `eval'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.1/lib/rack/builder.
rb:49:in `new_from_string'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.1/lib/rack/builder.
rb:40:in `parse_file'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.1/lib/rack/server.r
b:318:in `build_app_and_options_from_config'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.1/lib/rack/server.r
b:218:in `app'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/server.rb:59:in `app'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.1/lib/rack/server.r
b:353:in `wrapped_app'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/server.rb:124:in `log_to_stdout'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/server.rb:77:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:90:in `block in server'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:85:in `tap'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:85:in `server'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:49:in `run_command!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by prashantkb** [comment]
i included net-http-persistent in gem file and run bundle install its worked fine...
but it showing 

C:\clinico>rails s
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-3.0.0/lib/net/http/pe
rsistent.rb:205:in `<class:Persistent>': uninitialized constant Process::RLIMIT_
NOFILE (NameError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-3.0.0/li
b/net/http/persistent.rb:190:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:105:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:105:in `rescue in block in require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:82:in `block in require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:75:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:75:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.13.1/lib/bundler.r
b:106:in `require'
        from C:/clinico/config/application.rb:8:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:88:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:88:in `block in server'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:85:in `tap'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:85:in `server'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands/commands_tasks.rb:49:in `run_command!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/c
ommands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by pengwynn** [comment]
This doesn't appear to be an Octokit issue?
