### ISSUE TITLE
Credentials examples set bad example

### ISSUE THREAD

**Issue by ilyash** [octokit/octokit.rb#823]
The readme contains many authentication examples with credentials embedded in the code. Please stop setting bad example. These will be committed with the code, sometimes to public repositories.

**Comment by joeyw** [comment]
Hello @iylash. I agree unsuspecting newcomers may take this approach. So far it's really out of the scope of providing a basic get going examples of how to use the library. There are a lot of ways to bring in credentials. If you have some ideas as to how we could improve this to still fit into the goal of concise and easy to get started while still be informative, I would be glad to see and discuss them as a pull request.
