### ISSUE TITLE
Member List is incomplete

### ISSUE THREAD

**Issue by Alfredo-Moreira** [octokit/octokit.rb#827]
I'm using Octokit ruby library to perform some management within my team when it comes to GitHub. It is more like an audit. The problem is the Octokit method:

Octokit.organization_members('github')

that in itself calls this GitHub API:

GET /orgs/:org/members

I have noticed that the call is only retrieving the first page of users. In other words in a total of 81 users it is only retrieving 30. Thank you in advance.

**Comment by joeyw** [comment]
Hi @Alfredo-Moreira most lists in the API are paginated, in this case the default 30 per page is being retrieved. The readme has a section on pagination https://github.com/octokit/octokit.rb#pagination

**Comment by Alfredo-Moreira** [comment]
Thank you so much. Nothing like a one code line to fix problems! 
Answer:
(Octokit Client Object).auto_paginate = true
