### ISSUE TITLE
Update branch from target in a pull request

### ISSUE THREAD

**Issue by kevinrobayna** [octokit/octokit.rb#828]
AKA git pull origin master 

Hi all, I was trying pull all the changes from master to a branch i've created using Octokit but is not working as expected.
```
#update_branch(repo, branch, sha, force = true, options = {}) ⇒ Array<Sawyer::Resource>
```

I manage to override master with my branch (because of the force = true by default)

thank you in advance 😄

**Comment by joeyw** [comment]
Hi @kevinrobayna. I believe you are looking for the merge endpoint [#merge](http://octokit.github.io/octokit.rb/Octokit/Client/Commits.html#merge-instance_method) which would merge the changes from your branch into the destination. The basic syntax follows:

```ruby
@client.merge repo, 'master', 'new-branch'
````

By doing this with #update_branch you are essentially doing the following:

```bash
git checkout new-branch
# make changes and commit
git branch -D master
git branch -m new-branch master
```

**Comment by kevinrobayna** [comment]
Ah! my bad then! Thank you very much @joeyw 👍
