### ISSUE TITLE
Octokit should support setting the 'Merge Button' options

### ISSUE THREAD

**Issue by trevor-vaughan** [octokit/octokit.rb#835]
I have a large number of repos and wish to eliminate the basic 'Merge' option from all of them but leave the new capabilities.

Octokit should expose this setting to make switching over legacy repositories easier and to bulk change new ones in the future.

**Comment by pengwynn** [comment]
@trevor-vaughan you should be able to do this today if you pass the preview media type in the method options:

```ruby
client.merge_pull_request("trevor-vaughan/my-repo", 123, "Fixing all the things", :merge_method => "rebase", :accept => "application/vnd.github.polaris-preview+json")
```

**Comment by pengwynn** [comment]
@trevor-vaughan Sorry, I was confused by the title on this one. Another read of the body and it appears you're wanting an API to set those merge button settings in each repo?

**Comment by trevor-vaughan** [comment]
@pengwynn Yes, thanks.

Also, am I missing something, or is there no API for all of the Branch Protection features?

Thanks

**Comment by kytrinyx** [comment]
@trevor-vaughan Your first post is talking about the merge options.
These are available via the _edit repo_ endpoint, with the parameters `allow_squash_merge`, `allow_merge_commit`, and `allow_rebase_merge`.

https://developer.github.com/v3/repos/#edit
