### ISSUE TITLE
Installing octokit barfs on Yard documentation

### ISSUE THREAD

**Issue by miketheman** [octokit/octokit.rb#84]
Using Ruby 1.9.3 p194

Output:

```
$ gem install octokit
Successfully installed octokit-1.0.4
1 gem installed
Installing ri documentation for octokit-1.0.4...
Building YARD (yri) index for octokit-1.0.4...
[error]: ParserSyntaxError: syntax error in `LICENSE`:(1,18): syntax error, unexpected tINTEGER, expecting $end
[error]: Stack trace:
    /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/ruby/ruby_parser.rb:517:in `on_parse_error'
    /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/ruby/ruby_parser.rb:49:in `parse'
    /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/ruby/ruby_parser.rb:49:in `parse'
    /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
    /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/source_parser.rb:438:in `parse'
    /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/source_parser.rb:361:in `parse_in_order'

Installing RDoc documentation for octokit-1.0.4...
```

May have something to do with how yard (0.7.5) is being called for the LICENSE file.

**Comment by Prateek032** [comment]
I am still facing this kind of issue.PFB the screen  shot

![des](https://cloud.githubusercontent.com/assets/10941328/9573328/ca741452-4fd8-11e5-80a1-130296eefed3.PNG)

and can anybody provide installation steps ( correct one)

**Comment by pengwynn** [comment]
@Prateek032 This doesn't appear related to this previous issue. Could you open a new issue with the output of `gem install -V octokit`, please.

**Comment by juniorsro** [comment]
> Using Ruby 1.9.3 p194
> 
> Output:
> 
> ```
> $ gem install octokit
> Successfully installed octokit-1.0.4
> 1 gem installed
> Installing ri documentation for octokit-1.0.4...
> Building YARD (yri) index for octokit-1.0.4...
> [error]: ParserSyntaxError: syntax error in `LICENSE`:(1,18): syntax error, unexpected tINTEGER, expecting $end
> [error]: Stack trace:
>     /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/ruby/ruby_parser.rb:517:in `on_parse_error'
>     /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/ruby/ruby_parser.rb:49:in `parse'
>     /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/ruby/ruby_parser.rb:49:in `parse'
>     /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
>     /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/source_parser.rb:438:in `parse'
>     /Users/michael/.rvm/gems/ruby-1.9.3-p194@github/gems/yard-0.7.5/lib/yard/parser/source_parser.rb:361:in `parse_in_order'
> 
> Installing RDoc documentation for octokit-1.0.4...
> ```
> 
> May have something to do with how yard (0.7.5) is being called for the LICENSE file.
