### ISSUE TITLE
OAuth Token invalid.

### ISSUE THREAD

**Issue by kc8pnd** [octokit/octokit.rb#850]
I committed my OAuth Token in code and now I am unable to get my application to authenticate with a new Token. Are there other steps I need to take other than remove the code from the Repo and create a new OAuth application / Token?

**Comment by tarebyte** [comment]
@kc8pnd if you commit and push a GitHub OAuth token to GitHub we automatically make it invalid.

So you're correct all you have to do is make a new application and token and you should be set.

**Comment by kc8pnd** [comment]
I tried creating two new applications and these Tokens are also throwing the same "Bad credentials" exception. 
Any suggestions?
Mike.
