### ISSUE TITLE
Inconsistent results for :size in Octokit.repo result

### ISSUE THREAD

**Issue by jfmull** [octokit/octokit.rb#856]
I have seen inconsistent results getting the size of a repo from the Octokit.repo API.
The following gives a result of 7270:
```
Octokit.repo 'matlab2tikz/matlab2tikz'
```
If you download the zip from https://github.com/matlab2tikz/matlab2tikz using the 'Download ZIP' link under the 'Clone or download' button, the file size is 201 KB.

The size field for other repos, however, does match the actual zip file size on download:
* daniel-frisch-kit/plot-ecg (size reported is 20 and actual zip download is 20.5 KB)
* BCampforts/SPLM (size reported is 112 and actual zip download is 113 KB)
* BCampforts/topotoolbox (size reported is 12945 and actual zip download is 12.3 MB)

**Comment by pengwynn** [comment]
Octokit reports what it gets from the API so you'll need to [contact GitHub support](https://github.com/contact) for this one.
