### ISSUE TITLE
Support for `Octokit.ref?`

### ISSUE THREAD

**Issue by maikokuppe** [octokit/octokit.rb#861]
I'm missing the method `Octokit.ref?(repo, ref, options = {})` which returns true if the ref exists or false otherwise. Since it suffices for me to monkeypatch it, and I do not have time to make a proper pull request, I'm proposing the new method here:

```
module Octokit
  class Client

    # Methods for the Repositories API
    #
    # @see https://developer.github.com/v3/repos/
    module Repositories

      # Check if a ref exists
      #
      # @see https://developer.github.com/v3/repos/#get
      # @param repo [Integer, String, Hash, Repository] A GitHub ref
      # @param ref [String] A GitHub ref
      # @return [Sawyer::Resource] if a ref exists, false otherwise
      def ref?(repo, ref, options = {})
        !!ref(repo, ref, options)
      rescue Octokit::NotFound
        false
      end
    end
  end
end
```

**Comment by tarebyte** [comment]
@maikokuppe thanks for the suggestion, but I don't think that's a patch we want as part of Octokit.

This is more of a convenience method than anything else.
