### ISSUE TITLE
OpenSSL issue

### ISSUE THREAD

**Issue by samjarman** [octokit/octokit.rb#867]
Seeing an openssl issue I haven't been able to figure out just yet

```/Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/openssl/buffering.rb:322:in `syswrite': Broken pipe (Faraday::ConnectionFailed)
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/openssl/buffering.rb:322:in `do_write'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/openssl/buffering.rb:340:in `write'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:211:in `write0'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:185:in `block in write'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:202:in `writing'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/protocol.rb:184:in `write'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http/generic_request.rb:188:in `send_request_with_body'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http/generic_request.rb:121:in `exec'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1435:in `block in transport_request'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1407:in `request'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /Users/sam/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:33:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `post'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /Users/sam/.rvm/gems/ruby-2.3.3/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'```

OS: MacOS Sierra
Ruby Version: ruby 2.3.3p222
openssl version: OpenSSL 0.9.8zh 14 Jan 2016

Any ideas?

**Comment by tarebyte** [comment]
@samjarman this looks like an issue with Faraday/Sawyer not Octokit.

Maybe open an issue with those projects?
