### ISSUE TITLE
Repositories#repository(repo) fails if repo is an Integer

### ISSUE THREAD

**Issue by maikokuppe** [octokit/octokit.rb#868]
Let's consider `id` to be an Integer which represents a Github repo ID which is accessible by our Octokit installation.

Then `Octokit.repository(id)` raises the following error message:

```
Octokit::NotFound (PATCH https://api.github.com/repos/: 404 - Not Found // See: https://developer.github.com/v3):
```

Excerpt from the Octokit source code:

```
 File 'lib/octokit/client/repositories.rb', line 28

def repository(repo, options = {})
  get Repository.path(repo), options
end

# File 'lib/octokit/repository.rb', line 49

def path
  return named_api_path if @owner && @name
  return id_api_path if @id
end
```

The source code indicates, that the ID should be handled somehow, but the error message shows, that the resulting Github URL is wrong. It should be `/repos/:owner/:repo` as documented [here](https://developer.github.com/v3/repos/#get)

**Comment by maikokuppe** [comment]
I just mixed up `edit_repository` with `repository`. Neither documentation nor the code indicate that an Integer is allowed as the first argument.
My bad.

**Comment by tarebyte** [comment]
Pr's are welcome if you want to update the comments for that method: https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/repositories.rb#L36

**Comment by maikokuppe** [comment]
I'll rephrase this more clearly:

The docs and comments are fine and consistent. I just mixed up two methods ;)
