### ISSUE TITLE
build new release for review api support?

### ISSUE THREAD

**Issue by ketonkss4** [octokit/octokit.rb#872]
I am in need of the new reviews API and I see that someone has already contributed the update here https://github.com/octokit/octokit.rb/pull/860 

This is now in master but no new release has been built. The last release for the octokit project was back in November last year. Is there a reason why updates have been going into the master branch without any new releases being made?

**Comment by gylaz** [comment]
@pengwynn Any ETA on a release?

**Comment by pengwynn** [comment]
Oof, I thought this was already done. I just cut 4.7.0.

**Comment by gylaz** [comment]
Thank you! 🎉

**Comment by ketonkss4** [comment]
Thanks guys!
