### ISSUE TITLE
Faraday Cache and Rails

### ISSUE THREAD

**Issue by rafaelfragosom** [octokit/octokit.rb#873]
I hope this is just some silly mistake I made, but I have the following situation:

I configured a brand new Rails 5.0.2 app and installed Octokit and the faraday-http-cache gem to make conditional requests.

I was reading through the Docs and I saw that I had to add it as a custom middleware. So I created an initializer with the following code:

```ruby
stack = Faraday::RackBuilder.new do |builder|
  builder.use Faraday::HttpCache, serializer: Marshal, shared_cache: false, store: Rails.cache
  builder.use Octokit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end

Octokit.middleware = stack
```

And I even tried to set the middleware directly into my instance variable like so:

```ruby
stack = Faraday::RackBuilder.new do |builder|
  builder.use Faraday::HttpCache, serializer: Marshal, shared_cache: false, store: Rails.cache
  builder.use Octokit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end

github_api = Octokit::Client.new access_token: 'myaccesstokenhere'
github_api.middleware = stack

# Made my requests bellow ...
```

And for some reason, I'm still getting `200 OK` in all my exact requests. It's not caching. I can see the ratelimit Header in the responses decreasing.

I was expecting [THIS](https://developer.github.com/v3/#rate-limiting) behavior when I make conditional requests, like when I use CURL to make the requests.

Did I do everything right or am I missing something?

**Comment by lucasmazza** [comment]
@rafaelfragosom which cache store you are using in your Rails app? By default Rails uses a `null_store`, so nothing will be cached unless you configure to use something else (like memcache/redis or a file store)

**Comment by rafaelfragosom** [comment]
I knew it was something silly.
Thank you @lucasmazza
