### ISSUE TITLE
Retries are not consistently applied on API errors

### ISSUE THREAD

**Issue by ohookins** [octokit/octokit.rb#888]
It seems that the repo statistics methods of the client support retrying when there is an error or timeout from the API:
https://github.com/octokit/octokit.rb/blob/836948b6c176d7829e250e65caea790721c96523/lib/octokit/client/stats.rb#L91-L101

It would be very useful to have this universally applied throughout the SDK on the client itself (rather than per endpoint) so that the application doesn't have to implement its own retry logic.

**Comment by kytrinyx** [comment]
@ohookins that's a good point, this is definitely inconsistent.

I think that having retry logic within the calls to the individual endpoints is probably not the right approach for the client, but it would be very useful to have helpers to make it easy for people to add retry logic themselves if they need/want it.

**Comment by ohookins** [comment]
@kytrinyx I can appreciate that approach. In practice, with something like the Retryable gem, I would say that the experience is less than optimal. I feel that the AWS Ruby SDK does a very good job of encapsulating this logic though, if that's something you could look into.

**Comment by kytrinyx** [comment]
Thank you, I will definitely look into that one.

**Comment by kytrinyx** [comment]
We've discussed this, and we've decided that we want to add functionality that makes it easy to do retries, however we won't be adding it automatically to all the endpoints.

**Comment by AbNoir** [comment]
rery_timeout = options.delete ( : retry_timeout )
   retry_wait = options.delete ( : retry_wait ) ||  0.5 
   مهلة =  الوقت . الآن + retry_timeout
 النهاية 
 حلقة  القيام به 
   البيانات = الحصول على ( " # { مستودع .path الريبو } / احصائيات / # { قياس } " ، والخيارات)
   العودة البيانات إذا last_response.status ==  200 
   العودة  شيء  ما لم retry_timeout
   العودة  لا شيء  إذا  الوقت . الآن > = المهلة
   سليب retry_wait إذا retry_wait
 النهاية

**Comment by ohookins** [comment]
I haven't done anything about this on my end, although I was looking into making a Faraday middleware to implement the retries. Perhaps that's an acceptable alternative without introducing a new concern into the SDK? But it might help to have an example implementation somewhere.

**Comment by kytrinyx** [comment]
> it might help to have an example implementation somewhere.

Yeah, definitely. If you do get something working at the middleware level, would you post something here?

**Comment by kytrinyx** [comment]
> Seems the "fix" to this issue is simply to add it to the README default config?

That is my favorite kind of fix :) Looking at your PR now.

**Comment by kytrinyx** [comment]
Fixed in #1021
