### ISSUE TITLE
Using the methods directly on `Octokit` are not thread safe

### ISSUE THREAD

**Issue by wagenet** [octokit/octokit.rb#893]
When using methods directly on the `Octokit` module, the client is shared across all threads. This would be ok, except for the fact that the client maintains state. One place this happens in `last_response` which, if two threads are making requests at once, could easily end up out of order. If an explicit instance of `Octokit::Client` is created, this problem can be avoided.

See https://gist.github.com/chancancode/0061e8972b8e738b3734ceef6fe5ab23#file-octokit_threads-rb for a reproduction. Run with `GLOBAL=1` to see it fail. (Note that it can take a minute or so to see output from the script.)

My recommendation would be to deprecate use of methods directly on `Octokit`. Alternatively, there probably are some other routes you could take to ensure that the client is per-thread even when using the `Octokit` module directly.

/cc @chancancode

**Comment by chancancode** [comment]
To be more precise for the benefits of future readers – the client itself is still not threadsafe, as in if you make a client and hand that to multiple threads you will still run into the same problem. However, if you can make each thread *own* one client then as far as I can tell there aren't other obvious global shared sates floating around, which would match most people's use cases and expectations IMO

**Comment by kytrinyx** [comment]
> My recommendation would be to deprecate use of methods directly on Octokit

Yes, we'll go ahead and deprecate the use of those methods directly, and add a warning that the client is not threadsafe and that if people are using threads, they should be sure to make a new client for each thread.

**Comment by chancancode** [comment]
@kytrinyx thank you!

**Comment by abinoda** [comment]
@kytrinyx As part of this, do you think the README should be updated to not use examples where methods are being called on `Octokit` directly? Want me to open a PR for this?
