### ISSUE TITLE
Add topics to repository via API

### ISSUE THREAD

**Issue by RedaBenh** [octokit/octokit.rb#903]
Hi,
There is any way to add topics to a repository ?

Thanks

**Comment by kytrinyx** [comment]
@RedaBenh It's not currently possible with the v3 REST API and the Octokit, however if you're up for a workaround it is possible with the GraphQL API:

https://developer.github.com/v4/reference/mutation/updatetopics

**Comment by kytrinyx** [comment]
This is now available via the REST API: we've opened an issue about adding support. https://github.com/octokit/octokit.rb/issues/933
