### ISSUE TITLE
Where should I add Marketplace API

### ISSUE THREAD

**Issue by sotayamashita** [octokit/octokit.rb#906]
I am implementing [marketplace API](https://developer.github.com/v3/apps/marketplace/).  Here is the URL: https://github.com/sotayamashita/octokit.rb/tree/feature/marketplace.

**Comment by tarebyte** [comment]
@sotayamashita the best place would probably be in [this directory](https://github.com/octokit/octokit.rb/tree/ad74f84e818ee15d2e49422d51978a40b2d957a0/lib/octokit/client) under `marketplace.rb`

**Comment by sotayamashita** [comment]
@tarebyte Thanks
