### ISSUE TITLE
How to get rid of "WARNING: The preview version of the Reactions API ..."?

### ISSUE THREAD

**Issue by 5chdn** [octokit/octokit.rb#910]
Each call to the `issue_reactions` API generates the following warning when using octokit.rb 4.7.0:

> WARNING: The preview version of the Reactions API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.

However, I supply a custom media type as per the README:

    preview = Octokit::Client.new :access_token => ARGV.first.to_s
    preview.default_media_type = "application/vnd.github.squirrel-girl-preview+json"

Is this desired? What did I miss?

**Comment by kytrinyx** [comment]
@5chdn if you pass the custom media type with `:accept` to the method call in question, this warning should go away.

I'm going to go ahead and close this, but if this doesn't resolve your issue, let us know and we'll help sort it out.

**Comment by mib32** [comment]
If the of the Integrations API is not yet suitable for production, which API should I use in production in order to list app installation repositories?

**Comment by tarebyte** [comment]
@mib32 that is the only API available, it will be coming out of preview by the end of the year and we don't expect any changes.

If we do we'll make sure you're alerted well before on the blog https://developer.github.com/changes/

**Comment by aaronlippold** [comment]
This still seems to be an issue. Does anyone have a working example for this using the 'topics' preview.

**Comment by ianfixes** [comment]
> if you pass the custom media type with :accept to the method call in question, this warning should go away.

Can you spell out what that means?

**Comment by digglife** [comment]
> > if you pass the custom media type with :accept to the method call in question, this warning should go away.
> 
> Can you spell out what that means? Is it this?
> 
> ```diff
>   preview = Octokit::Client.new :access_token => ARGV.first.to_s
> - preview.default_media_type = "application/vnd.github.squirrel-girl-preview+json"
> + preview.default_media_type = { accept: "application/vnd.github.squirrel-girl-preview+json" }
> ```

@ianfixes 

I think @kytrinyx means calling `issue_reactions` with `:accept` option.
 
```ruby
preview.issue_reactions("octokit/octokit.rb", 910, {:accept => "application/vnd.github.squirrel-girl-preview+json"})
```

**Comment by digglife** [comment]
Setting `default_media_type` for the client object itself does not work because there are a bunch of predefined `PREVIEW_TYPES` which overrides the `default_media_type` when methods such as `issue_reactions` being called. The one defined for `reactions` is `application/vnd.github.squirrel-girl-preview` in the code instead of `application/vnd.github.squirrel-girl-preview+json` noted in the [API documentation](https://developer.github.com/v3/reactions/#list-reactions-for-an-issue).

https://github.com/octokit/octokit.rb/blob/6d6078a8c517d2233539786e537d481b2d1e106c/lib/octokit/preview.rb#L16

I figured it out with debugging.
```ruby
>> client.issue_reactions("octokit/octokit.rb", 910)
WARNING: The preview version of the Reactions API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.
I, [2020-04-02T18:17:07.598618 #82323]  INFO -- request: GET https://api.github.com/repos/octokit/octokit.rb/issues/910/reactions
D, [2020-04-02T18:17:07.598732 #82323] DEBUG -- request: Accept: "application/vnd.github.squirrel-girl-preview"
User-Agent: "Octokit Ruby Gem 4.18.0"
Content-Type: "application/json"
```

They didn't change the string back then because as @tarebyte said, the API would be coming out of preview by the end of **2018** except it didn't make it. So should it be changed now?

**Comment by ianfixes** [comment]
Thanks, this worked.  

Is it just me, or is the documentation very lacking on the association between setting header variables and arbitrary keyword args that can be passed to API functions?  A section on "how to enable beta API features" or something to attract Google searches would be useful.

**Comment by fifitrixabelle** [comment]
while this is in preview a nice way to use this (using topics as an example) is:

`topics = client.topics(repo ,{:accept => Octokit::Preview::PREVIEW_TYPES[:topics]})`

from https://github.com/octokit/octokit.rb/blob/6d6078a8c517d2233539786e537d481b2d1e106c/lib/octokit/preview.rb
