### ISSUE TITLE
[Question] Can octokit be used to download the audit for an org?

### ISSUE THREAD

**Issue by jason-riddle** [octokit/octokit.rb#911]
I would like to automate downloading the audit log for an organization every week. Right now the download link looks like the following.

```
https://github.com/orgs/<org>/audit-log/export?token=5c1db9b2-c499-47cd-90aa-44070909dc74
```

It's not clear how the token is being generated, so I was wondering if octokit could help with download this file?

**Comment by tarebyte** [comment]
@jason-riddle this is out of the scope of Octokit and is more of a feature request for GitHub itself. Would you mind reaching out to support@github.com? Thanks!

**Comment by jason-riddle** [comment]
Sounds good. Thanks!
