### ISSUE TITLE
Bug when using stats API on empty repos

### ISSUE THREAD

**Issue by nwoodthorpe** [octokit/octokit.rb#912]
When called on an empty repository, all of the stats endpoints except `participation` return a `204 no content`.

This causes delays in the `get_stats` method, which waits until it receives a 200. It should either be waiting for a non-202, or a 200/204 to return data.

I can implement a fix and write some specs for this. What kind of return do we want when we hit a 204 though? nil?

**Comment by tarebyte** [comment]
@kytrinyx I'd love your thoughts on this 🏈

**Comment by kytrinyx** [comment]
My first thought is: why is `participation` different? Should this also be a 204? Should the others be 200 with some default payload that says some variation of "nothing"? This is not something we can tackle at the octokit.rb level, but worth asking anyway.

As written, it should probably wait for either 200 or 204 to return data, not just 200.

> What kind of return do we want when we hit a 204 though? nil?

If we provide nil, then the client code will have to check for nil and do something if it gets nil. I would prefer to provide a good zero value that the client code wouldn't have to check. This is similar to the idea of "identity" in arithmetic. You add or subtract 0, and the result is whatever you started out with. You multiply by 1, and you get whatever you started out with.

Or maybe we could liken it to a no-op: we provide something that lets the client process it, without any other result than an extra instruction having been run.

**Comment by tansaku** [comment]
we've noticed our scheduled processes hanging on empty repos ... @nwoodthorpe any progress on a fix?  If it was in a branch somewhere we could try it out on are system ... I guess otherwise we'll have to add a fixed timeout - what do you think @praveendhawen?

**Comment by praveendhawan** [comment]
@tansaku we could probably fix the issue here as suggested by @nwoodthorpe by checking for 200 or 204, or we can also send `retry_timeout` as options to `get_stats`. I was able to find the [code](https://github.com/octokit/octokit.rb/blob/836948b6c176d7829e250e65caea790721c96523/lib/octokit/client/stats.rb#L90 ) which might be causing problem.

**Comment by tansaku** [comment]
@praveendhawan if we don't hear from @nwoodthorpe soon we could put a PR into Octokit?

**Comment by tarebyte** [comment]
@tansaku @praveendhawan feel free to make a PR as @nwoodthorpe is out on vacation until October 😄

**Comment by Kadaaran** [comment]
We've been encountering this issue in Classroom recently, can I start working on a PR if it's still up for grabs 👍

**Comment by tarebyte** [comment]
@Kadaaran go for it 👍
