### ISSUE TITLE
Add support to assign as reviewer

### ISSUE THREAD

**Issue by BasThomas** [octokit/octokit.rb#915]
It seems like we can't add a user as a reviewer, but can add them as an assignee.

**Comment by tarebyte** [comment]
@BasThomas are you referring to this API endpoint https://developer.github.com/v3/pulls/review_requests/#create-a-review-request?

**Comment by BasThomas** [comment]
@tarebyte yep!

**Comment by shujin** [comment]
I think this is what you're looking for: https://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html#request_pull_request_review-instance_method
