### ISSUE TITLE
How do you make a GraphQL query?

### ISSUE THREAD

**Issue by Bilge** [octokit/octokit.rb#918]

**Comment by tarebyte** [comment]
@Bilge I wrote up a little example to see if I can help you get started

```ruby
# frozen_string_literal: true

require 'awesome_print'
require 'octokit'
require 'json'

client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])

query = <<-GRAPHQL
query {
  viewer {
    login
  }
}
GRAPHQL

response = client.post '/graphql', { query: query }.to_json
ap response
```

```ruby
{
    :data => {
        :viewer => {
            :login => "tarebyte"
        }
    }
}
```

**Comment by Bilge** [comment]
Hey @tarebyte. Thanks! Unfortunately I couldn't wait to get started so I already wrote a solution using the v3 API. However, I don't think your effort need go to waste: we should probably put something like this in the documentation, don't you think? 😃

**Comment by tarebyte** [comment]
@Bilge there is a WIP PR https://github.com/octokit/octokit.rb/pull/834 for initial GraphQL support, I'm looking at finishing it up and then adding it to the README 😄
