### ISSUE TITLE
Adding collaborators to a repository always returns false

### ISSUE THREAD

**Issue by spappier** [octokit/octokit.rb#921]
It seems after [todays changes to the github api](https://developer.github.com/changes/2017-08-23-repository-invitation-api/), adding someone to a repository sends them an invitation to become a collaborator and returns a 201 status code instead of 204. [Octokit always checks for a 204 for success](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/connection.rb#L165), maybe it should check for any successful status code?

**Comment by tarebyte** [comment]
@spappier if you use https://github.com/octokit/octokit.rb/blob/dc09f52e80377b912031951810c6f861e0af3ed4/lib/octokit/client/repository_invitations.rb#L9-L21

You should get the correct response.

**Comment by spappier** [comment]
@tarebyte Thanks! I'll use that method, was just caught by surprise by the change (it broke a couple of our processes).

Still think the other method should be changed now that the api responds a different status code :)
