### ISSUE TITLE
Better exception handling?

### ISSUE THREAD

**Issue by 3minus1** [octokit/octokit.rb#925]
Why don't we return `nil` whenever a `404` occurs while trying to `get` a resource? I think this will still serve the purpose of not serving a `401` and would also gracefully assert that the requested resource was either not found or doesn't exist at all.

For eg: `client = Octokit::Client.new(:login => 'defunkt', :password => 'c0d3b4ssssss!')` would pop a `404` error if the credentials are invalid or if the user doesn't exist. If we handle the `404` here and return `nil`, it would be easier for apps using octokit to handle exceptions by just checking if the octokit method returns `nil`

**Comment by 3minus1** [comment]
I just realised that Client.new() will return a `401` if the credentials are invalid. Regardless, the issue prevails because the execution will still halt because of the exception.

**Comment by kytrinyx** [comment]
Thanks for bringing this up, @3minus1. We need to pass the 404 through to the caller. If we change it to `nil`, that overloads the meaning of `nil` which could get confusing.
