### ISSUE TITLE
users resource method

### ISSUE THREAD

**Issue by lucasdchamps** [octokit/octokit.rb#927]
Is there a method for the `/users` route? (https://developer.github.com/v3/users/#get-all-users)

For example, `Octokit.repositories` works fine for the Repositories resource but `Octokit.users` doesn't seem to exist.

Thanks for your help.

**Comment by tarebyte** [comment]
There sure is!

It's located here: https://github.com/octokit/octokit.rb/blob/30e29f6a4fba1cad347d9abe38c63a43c97a3487/lib/octokit/client/users.rb#L9-L23

**Comment by lucasdchamps** [comment]
oh thanks! I tried calling this method but I had to instantiate a Octokit::Client first... My bad!
