### ISSUE TITLE
Octokit::Client.repos for an organization doesn't return all results

### ISSUE THREAD

**Issue by jvergeldedios** [octokit/octokit.rb#930]
I create a new client using a personal access token:
```ruby
client = Octokit::Client.new(access_token: GITHUB_TOKEN)
```
Then I attempt to fetch all of my org's repos:
```ruby
repos = client.repos(ORG_NAME, per_page: 100)
repos.length # returns 43
```
It returns 43 results when I was expecting a full page of 100 since my org has well over 100 repos.

I also attempted the (what I assume is) the same request using `curl`:
```bash
curl -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100"
```
And the above request returns the expected full page of 100.

This is using octokit v4.7.0, ruby v2.4.0, and rubygems v2.6.13.

**Comment by jvergeldedios** [comment]
Just attempted:
```ruby
repos = client.org_repos(ORG_NAME, per_page: 100)
repos.length # still returns 43
```

**Comment by tarebyte** [comment]
@jvergeldedios is this consistent across all organizations? Or just this one organization?

**Comment by jvergeldedios** [comment]
@tarebyte This is the only one I've tried with, and it's also the only org I have that has private repos. Let me try adding a private repo to another org and see if the same problem arises.

**Comment by iCreateJB** [comment]
I believe this is a client level setting, not an individual call based setting. 

```ruby
  client = Octokit::Client.new(access_token: GITHUB_TOKEN, per_page: 1000)
```

[Reference](https://github.com/octokit/octokit.rb/blob/8404007e9e11d3695df0907adcb3514decd23287/lib/octokit/connection.rb#L80-L82)

**Comment by iCreateJB** [comment]
cc @kytrinyx

**Comment by kytrinyx** [comment]
@iCreateJB While I think a client-level option does work, I don't think that comes into play here. Pagination works for me when I use the method-level per_page option:

```
token = "<my token>"
org_name = "<my org name>"
client = Octokit::Client.new(access_token: token)
client.org_repos(org_name, per_page: 10).count
=> 10
client.org_repos(org_name, per_page: 100).count
=> 100
```

**Comment by kytrinyx** [comment]
@jvergeldedios would you try using the middleware shown in the debugging section of the README? This might show how the octokit request is different from the `curl` request.

https://github.com/octokit/octokit.rb#debugging

**Comment by tarebyte** [comment]
This looks like this has been solved so I'm going to close it. @jvergeldedios please feel free to open this back up if you need more assistance.

Thanks!
