### ISSUE TITLE
Contents API does not take ref into account

### ISSUE THREAD

**Issue by gjtorikian** [octokit/octokit.rb#931]
Given a call like this:

``` ruby
client.contents(public_repo, path: public_folder_path, ref: branch)
```

Octokit always responds with the contents of the `master` ref. This is in contrast to [the API docs](https://developer.github.com/v3/repos/contents/#get-contents), which permits selection based on the branch.

In curl, the right call here is:

``` command-line
curl -u gjtorikian:${GITHUB_TOKEN} https://api.github.com/repos/:owner/:repo/contents/:path?ref=branch
```

I'm not sure where that `?ref=` query param is going or why it is dropped.

**Comment by kytrinyx** [comment]
@gjtorikian Thanks for reporting this, we'll take a look!

**Comment by iCreateJB** [comment]
Not a bug.

Looking at the interface, you should probably call it like this : 

```ruby
# master
api.contents('octokit/octokit.rb', path: 'lib/octokit/version.rb')
 => {:name=>"version.rb",
 :path=>"lib/octokit/version.rb",
 :sha=>"dea89b175d3d0c51c47d8307e8b01e2857ca958a",
 :size=>301,
 :url=>
  "https://api.github.com/repos/octokit/octokit.rb/contents/lib/octokit/version.rb?ref=master",
  ...
  ...
```

```ruby
api.contents('octokit/octokit.rb', path: 'lib/octokit/version.rb', query: { ref: 'refactor-middleware' })
 => {:name=>"version.rb",
 :path=>"lib/octokit/version.rb",
 :sha=>"eaf67c482f4185a9508617afee2db02f5a7c2a81",
 :size=>301,
 :url=>
  "https://api.github.com/repos/octokit/octokit.rb/contents/lib/octokit/version.rb?ref=refactor-middleware",
```

**Comment by kytrinyx** [comment]
@iCreateJB Thank you—yes, that does look right.

@gjtorikian I'm going to de-classify this as a bug, but add a documentation label, because this could use some extra emphasis.

**Comment by iCreateJB** [comment]
I could add some plus an example or two. 

Do you have a designation of where you would like it @kytrinyx ?

**Comment by kytrinyx** [comment]
That would be lovely, @iCreateJB. How about the "making requests" section of the README?
