### ISSUE TITLE
Getting 404 when trying to obtain pull requests

### ISSUE THREAD

**Issue by tekHudson** [octokit/octokit.rb#935]
I am trying to obtain a list of pull requests open in my repo for a specific set of users.

First I setup my Octokit `@github = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])`
If I were to call `@github.client` this is what is returned:
```
{:login=>"tekHudson", :id=>6435726, :avatar_url=>"https://avatars2.githubusercontent.com/u/6435726?v=4", :gravatar_id=>"", ...
```
If I then call `@github.pulls("is:pr state:open user:#{ORGANISATION}")` or if I call `@github.pull_requests("is:pr state:open user:#{ORGANISATION}")` I get:
```
Octokit::NotFound: GET https://api.github.com/repos/PulseSoftwareInc/pulse360/pulls: 404 - Not 
Found // See: https://developer.github.com/v3
```
Happy to supply more information if you need it.

**Comment by tekHudson** [comment]
I have tried this for a non-private repository as well:
```
Octokit::NotFound: GET https://api.github.com/repos/on-stie/StockAid/pulls: 404 - Not Found // See: https://developer.github.com/v3
```

**Comment by tarebyte** [comment]
@tekHudson so it looks like you're trying to cross the [Search API](https://developer.github.com/v3/search/) and the [Pull Requests API](https://developer.github.com/v3/pulls/) together.

If you'd like to explicitly search for all open pull requests on an org you could do something like this:

```ruby
client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
client.search_issues('is:pr state:open user:#{ORGANISATION}')
```

And that should get all open PRs.

Example:

```ruby
client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
client.search_issues("is:pr state:open user:octokit")
```

**Comment by tekHudson** [comment]
I think this may be access token related... Testing will get back to you.

**Comment by iCreateJB** [comment]
Substitute: organization/repo_name

You'll have to filter by user

[example]
  `octokit/octokit.rb`

```ruby
  client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'], per_page: 100)
  client.pull_requests('organization/repo_name', state: :open, direction: :desc)
```

**Comment by tekHudson** [comment]
I see what is happening I believe. I am not seeing PRs on Private repos. Should this have access to them?

**Comment by tekHudson** [comment]
OK, So issue was with the token I made in Github. Had insufficient access.

**Comment by kytrinyx** [comment]
@tekHudson your access to private repositories will depend on two things:

- the authorization for the call (e.g. if using a personal access token, does the user have access)
- the access level (e.g. for personal access tokens, it will need the `repo` scope)

_update: I see that you just figured out that it was the token scope_
