### ISSUE TITLE
Update SHA of Submodule?

### ISSUE THREAD

**Issue by chris-alation** [octokit/octokit.rb#936]
Is it possible to update the SHA of a submodule?

I can get the contents and see the return type is: `:type=>"submodule"`and SHA gets returned `:sha=>"123123123123123123123"`

But when I try to update the contents, I am getting the error: `path/to/submodule is not a file // See: https://developer.github.com/v3/repos/contents/`

Which I understand the error, as it isn't a file (obviously), but then what call do I have to do to update the SHA of the submodule?

**Comment by greysteil** [comment]
(I'm not GitHub staff.)

It's absolutely possible to update the contents of a submodule - we do it in Dependabot [like this](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator.rb#L66-L92). (Obviously you also need to create a commit with that tree, and push it.)

**Comment by tarebyte** [comment]
Looks like this has been solved. Thanks for tackling this @greysteil!
