### ISSUE TITLE
add_contents without pushing to repo

### ISSUE THREAD

**Issue by jonhue** [octokit/octokit.rb#944]
I am frequently getting an `Octokit::AbuseDetected` error because my app triggers too many API requests.

I am using the `add_contents` method to add each file inside of a specific directory to a remote repository: (one by one)

```ruby
Dir.glob(wrapper + '/**/*') do |path|
    octokit_client.create_contents(name, path.sub("#{wrapper}/", ''), 'adding content', File.read(path), branch: 'master') unless File.directory?(path)
end
```

Is there a way to either push all files inside of a directory to a remote repo at once or to first add the contents locally and then push the repo?

**Comment by kytrinyx** [comment]
> add the contents locally and then push the repo

This is how I do it. I write my scripts so that they add all the files, commit, and then push up to the remote. I think Git pushes are rate limited, but nowhere near as strictly as the API (I've never actually run into the limit, I just think that there is one).

**Comment by tarebyte** [comment]
Closing due to staleness
