### ISSUE TITLE
Failing to reset github instance endpoint

### ISSUE THREAD

**Issue by t3rse** [octokit/octokit.rb#945]
I am using Octokit successfully to obtain project/repo information. However when I attempt to reset the endpoint to work on a different github instance, the URL (and other info) are not overwritten. 

Here is the code I'm using to try to toggle my Octokit clients - one to point to a hosted instance and another to point to github.com: 

```
        @client = Octokit::Client.new(:access_token => ENV['HOSTED_GITHUB_TOKEN'])
        @extern_client =  Octokit::Client.new(:access_token => ENV['GITHUB_COM_TOKEN'])
```
...
```
      def pick_client(ep)
        target = client
          if ep == "github" 
            target = extern_client 
            Octokit.configure do |c|
              c.api_endpoint = "https://github.com/api/v3/"
            end             
          else
            Octokit.configure do |c|
              c.api_endpoint = "https://github.mycompany.net/api/v3/"
            end
          end
          target
      end
```

I am newer to Ruby but it seems as though while I can have more than one instance of an Octokit `client`, this still does not allow me to access multiple github instances. Is there a way to do this?

**Comment by iCreateJB** [comment]
Seems like you should be doing this setup on the object instantiation perhaps ? 

```ruby
  def client
    Octokit::Client.new(access_token: ENV['GITHUB_API_TOKEN'], api_endpoint: '')
  end

  def hosted_client
    Octokit::Client.new(access_token: ENV['HOSTED_GITHUB_TOKEN'], api_endpoint: '')
  end
```

**Comment by iCreateJB** [comment]
cc @kytrinyx

**Comment by kytrinyx** [comment]
@iCreateJB thanks! Yes, this is the right approach to take.

@t3rse does passing the `api_endpoint` to your client during initialization solve this problem?

If so, let's update the documentation in the [Working with GitHub Enterprise](https://github.com/octokit/octokit.rb#working-with-github-enterprise) section of the README to show both types of initialization.

**Comment by tarebyte** [comment]
This looks like it has been solved, @t3rse please feel free to open this back up if you experience this issue again.
