### ISSUE TITLE
Unable to pull organizations for an authenticated user

### ISSUE THREAD

**Issue by jedrekdomanski** [octokit/octokit.rb#957]
Hi,

According to GitHub API and Octokit documentation, a user can list his organizations:
- all public organziations if not authenticated
- all organziations including private if authenticated

Now, I authenticate using OmniAuth, I get a token back in the response, then I do:

```
client = Octokit::Client.new(:access_token => "my_token")
client.orgs
```
and I get 403 Forbidden error:
```
Octokit::Forbidden: GET https://api.github.com/user/orgs: 403 - You need at least read:org scope or user scope to list your organizations. // See: https://developer.github.com/v3/orgs/#list-your-organizations
```
In omniauth config I provide the scope:
```
provider :github, ENV['GITHUB_CLIENT_ID'], ENV['GITHUB_CLIENT_SECRET'], scope: 'read:org'
```
I tried both scopes and even both together and none of them let me through.
So I am authenticated and still this is not enough. 

The scope is properly included in the URL when I am redirected to Github:
```
https://github.com/login/oauth/authorize?response_type=code&client_id=Iv1.27d75e222d376756&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fgithub%2Fcallback&state=9d310b492950dc32dc0608d5f726a5f8b2233d3e2db68da5&scope=**read%3Aorg**
```
Does anyone know how to get this sorted? I have read through Octokit documentation and I don't see anything there.

**Comment by jedrekdomanski** [comment]
So I gave it one last shot using basic auth this time:
```
client = Octokit::Client.new(:login => "my_login", password: 'my_password')
client.orgs
```
and it worked fine. So it looks like Octokit does not support listing organizations for authenticated user using OAuth, only basic auth. Is that correct?

**Comment by iCreateJB** [comment]
Check the scope of your token, it may have only been granted with particular scopes.

**Comment by jedrekdomanski** [comment]
Nevermind, I just made deeper investigation of Github API and figured out that a token is required to access public data from it.
