### ISSUE TITLE
Can't add assignees to issue

### ISSUE THREAD

**Issue by MatheusRich** [octokit/octokit.rb#960]
Hi, 

I'm trying to add assignees to issues like this:
![image](https://user-images.githubusercontent.com/20938712/32550166-3d147c52-c473-11e7-882b-b7a09cf12285.png)

Though I'm getting this response:
![image](https://user-images.githubusercontent.com/20938712/32550225-68c329de-c473-11e7-82d0-c1005f97b8b0.png)

Is this a bug, or am I doing something wrong?

**Comment by tarebyte** [comment]
@MatheusRich it looks like `add_assignees` isn't included in the latest release of Octokit https://github.com/octokit/octokit.rb/blob/v4.7.0.

This should be resolved if you pull from master, but in the long term I need to cut a new release.
