### ISSUE TITLE
branch_protection options updated 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [octokit/octokit.rb#965]
https://developer.github.com/enterprise/2.12/v3/repos/branches/#update-branch-protection 

I used method as 
`client.protect_branch("Reponame", "master", { enforce_admins: true, required_pull_request_reviews: nil, required_status_checks: { strict: true, contexts: checks_to_enable } })` to get it working again. Comment needs to be updated to be aligned to this.

**Comment by tarebyte** [comment]
Thanks for the report, please feel free to open a pull request to fix this 😄

**Comment by malakai97** [comment]
Confirmed latest release still affected

**Comment by kytrinyx** [comment]
@malakai97 would you mind opening a pull request with a fix?
