### ISSUE TITLE
[QUESTION] Only able to access Organisation repos

### ISSUE THREAD

**Issue by FelixFortis** [octokit/octokit.rb#968]
Hi there, I've just started using the GitHub API and your library, and a have a quick newbie question for you.

I've generated a personal access token [here](https://github.com/settings/tokens).

Then I try:

    client = Octokit::Client.new(access_token: "my_pa_token")
    #<Octokit::Client:0x809b868>
    client.repos
    #=> an array of repos for organisations that I have access to

The problem with this is that my own user repo (and repo's for other users that I have admin access to) are not in the list.

It seems weird that I can't make a PR onto one of my own projects using the API and a PA token.

I'm sure I'm just missing some basic domain knowledge here, so any help would be greatly appreciated.

**Comment by tarebyte** [comment]
@FelixFortis so what' probably happening here is that you are only getting back 30 results due to [pagination in the GitHub API](https://developer.github.com/v3/#pagination)

If you want to get more results try the suggestions in the README here: https://github.com/octokit/octokit.rb#pagination

**Comment by FelixFortis** [comment]
@tarebyte that was exactly the problem, thanks for your help!
