### ISSUE TITLE
Documentation on paging is confusing

### ISSUE THREAD

**Issue by milch** [octokit/octokit.rb#971]
Here's the page I'm referring to: https://developer.github.com/v3/guides/traversing-with-pagination/

Check out the following statement, taken from the page: 

> We won't go into detail about what that is, but, suffice to say, each element in the results variable has a hash called rels, which can contain information about :next, :last, :first, and :prev, depending on which result you're on.

That `:next` and `:prev` don't (and can't) always exist is pretty clear from this, however, arguably the first and last page when only one page exists is that exact page. Further adding to the confusion is that the sample code also acts like `:last` exists without checking for nil, e.g.

```ruby
last_response = client.last_response
number_of_pages = last_response.rels[:last].href.match(/page=(\d+).*$/)[1]
```

Whereas accessing `:next` has explicit nil handling later:

```ruby
until last_response.rels[:next].nil?
  last_response = last_response.rels[:next].get
  puts last_response.data.items.first.path
end
```

To me nothing on that page suggests that the existence of `:first` and `:last` are conditional upon page count being > 1. 

I would've probably filed this as an API bug instead but I couldn't find a way to do so, or as a documentation bug but couldn't find a way to do that either. Considering that most projects have an "Edit this doc on GitHub" button I honestly find it kind of weird that GitHub doesn't even seem to have their API docs open source 🤔

**Comment by tarebyte** [comment]
> I would've probably filed this as an API bug instead but I couldn't find a way to do so, or as a documentation bug but couldn't find a way to do that either.

The best way to raise a bug or question would be to email support@github.com 😄 

I'm going to close this since it really isn't related to Octokit.

Thanks for bringing up this issue and inconsistency @milch ❇️
