### ISSUE TITLE
Pagination fails for some GitHub App APIs

### ISSUE THREAD

**Issue by stmllr** [octokit/octokit.rb#974]
It seems that Octokit is unable handle pagination for some of the GitHub Apps API. It only returns the result for the first page. Even if there are more items.

Take the APIs to list repositories as an example:

Pagination expects `last_response.data` to be of Type Array, but App API returns Sawyer::Resource instead. Therefore concat of subsequent responses fails:

```
# Octokit::Connection
def paginate
#...
  data.concat(@last_response.data) if @last_response.data.is_a?(Array)
```
https://github.com/octokit/octokit.rb/blob/master/lib/octokit/connection.rb#L92

When comparing the API responses for GitHub App and Oauth App, it gets obvious:

1. List repositories of an installation (GitHub App) https://developer.github.com/v3/apps/installations/#list-repositories
```
{
  "total_count": 1,
  "repositories": [
    {
      "id": 1296269,
      ...
    }
  ]
}

=> Hash {}
```

2. List organization repositories (OAuth App) https://developer.github.com/v3/repos/#list-organization-repositories
```
[
  {
    "id": 1296269,
    ....
    }
  }
]

=> Array []
```

**Comment by tarebyte** [comment]
@stmllr thanks for reporting this!

We've confirmed this bug, and have actually found it in multiple methods 😬 

- https://github.com/octokit/octokit.rb/blob/40e16e6b951901d4b864777c9dbbc9f321eac4a3/lib/octokit/client/apps.rb#L37
- https://github.com/octokit/octokit.rb/blob/40e16e6b951901d4b864777c9dbbc9f321eac4a3/lib/octokit/client/apps.rb#L158
- https://github.com/octokit/octokit.rb/blob/40e16e6b951901d4b864777c9dbbc9f321eac4a3/lib/octokit/client/apps.rb#L84

The [Search API](https://developer.github.com/v3/search/) has a similar response and there is a custom way to do pagination

https://github.com/octokit/octokit.rb/blob/40e16e6b951901d4b864777c9dbbc9f321eac4a3/lib/octokit/client/search.rb#L68-L73

Would you be up for making a PR to fix this?
