### ISSUE TITLE
Remove assignees API

### ISSUE THREAD

**Issue by licatajustin** [octokit/octokit.rb#983]
Unless I'm mistaken, currently we're not able to [remove assignees](https://developer.github.com/v3/issues/assignees/#remove-assignees-from-an-issue) from Issues/Pull Requests with this library.

Is this something you are open to accepting Pull Requests for? Here is the [GitHub API](https://developer.github.com/v3/issues/assignees/#remove-assignees-from-an-issue) for it.

---

P.S.: thanks for this gem 👏

**Comment by tarebyte** [comment]
@licatajustin absolutely we’d be open to that 😄

**Comment by licatajustin** [comment]
Closing this issue in favor of the open PR: https://github.com/octokit/octokit.rb/pull/984. Thanks again for this lovely library maintainer!
