### ISSUE TITLE
Wrong example in documentation

### ISSUE THREAD

**Issue by europ** [octokit/octokit.rb#988]
http://www.rubydoc.info/gems/octokit/Octokit%2FClient%2FReviews:dismiss_pull_request_review

Example with 3 arguments while 4 arguments are required.
`@client.dismiss_pull_request_review('octokit/octokit.rb', 825, 6505518)`

Missing argument:
`message (String) — The message for the pull request review dismissal`

**Comment by tarebyte** [comment]
Thanks for catching that @europ! Minding opening a Pull Request?

**Comment by europ** [comment]
@tarebyte Not a problem.

**Comment by europ** [comment]
@tarebyte Not a problem.
