### ISSUE TITLE
It should be easier to get my list of PRs

### ISSUE THREAD

**Issue by trejkaz** [octokit/octokit.rb#993]
I'm trying to get the same list of PRs which I get when I go to `/pulls` on the web site itself. Essentially, PRs I submitted which haven't been merged yet. I was investigating using an API to pull this information so that I could match it up with information in other systems here and maybe create a single output with all the info.

So I tried this:

```
client.pull_requests(nil)
```

This fails, because it wants a repository passed in. OK, that's a pain, but I think I can work around it. I just have to figure out the full list of repositories.

So I try this:

```
client.all_repositories
```

But this only returns 5 repositories, even though I know there are 16.

I then tried iterating all users and then for each user iterating their repositories - same result there.

At this point I have no idea what could be going wrong. The scopes on my access token are [repo, read:org], is that the problem? The GitHub docs don't make it very clear what level of access you need to read PRs.

**Comment by tarebyte** [comment]
Hi @trejkaz so it looks like there are a few things going on here so I'm going to do my best to break them up.

> I'm trying to get the same list of PRs which I get when I go to /pulls on the web site itself.

There isn't an endpoint in the REST API that supports that feature. However you can do this with a [GraphQL Request](https://developer.github.com/v4/)

The request would look more or less like this:

```graphql
{
  viewer {
    pullRequests(last: 30, states: [OPEN]) {
      nodes {
        number
        title
        repository {
          nameWithOwner
        }
      }
    }
  }
}
```

> But this only returns 5 repositories, even though I know there are 16.

The method you are trying to use it actually this API https://developer.github.com/v3/repos/#list-all-public-repositories which lists only public repositories which is probably why you're not seeing all of the repositories in question.

> At this point I have no idea what could be going wrong. The scopes on my access token are [repo, read:org], is that the problem?

The tokens are correct, I hope that my comments above will help point you in the right direction.

I'm going to close this out, but please feel free to still comment on this.

Thanks!

**Comment by trejkaz** [comment]
Wow... who would have thought that a method called "all" repositories would only return public ones. (Principle of least surprise...)

**Comment by trejkaz** [comment]
I got it working initially by iterating users and using `organization_repositories` when the user is `type:Organization`. It's a bit of a brute force approach, but it's giving me the data I'm after.

I tried to use GraphQL adapting an example I found on another ticket...

```
query = <<-EOS
  {
    viewer {
      pullRequests(last: 20, states: [OPEN]) {
        nodes {
          number
          title
          repository {
            nameWithOwner
          }
        }
      }
    }
  }
EOS

response = github_client.post '/graphql', {query: query}.to_json
```

This gives me a 403:

```
[gems]/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://[server]/login?return_to=https%3A%2F%2F[server]%2Fgraphql: 403 - Cookies must be enabled to use GitHub. (Octokit::Forbidden)
```

At first glance the error looks weird, but looking at the URL, I guess I'm being redirected to login for some reason. I authenticate with a personal access token but as far as I can tell, that is the supported way at the moment, so I'm not sure why I can't use it. Some difference between public GitHub and the Enterprise installation, I bet.

**Comment by jasons42** [comment]
Very old issue, but I just ran into it as well and in case anyone else ever does, the solution was to prepend `/api` to my post path, so the last line looks like:

```response = github_client.post '/api/graphql', {query: query}.to_json```
