### ISSUE TITLE
Fetch a single Github Deployment by ID

### ISSUE THREAD

**Issue by russellballestrini** [octokit/octokit.rb#995]
From the Github API I see that it is possible to fetch a single Github Deployment (https://developer.github.com/v3/repos/deployments/#get-a-single-deployment).

That said, at frst clance it doesn't appear that octokit supports this, am I mistaken?  

It seems like this file only needs the following (https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/deployments.rb):

```ruby

      # oddly enough, this isn't defined in the upstream octokit library.
      def deployment(repo, deployment_id, options={})
        get("#{Repository.path repo}/deployments/#{deployment_id}", options)
      end
      alias :list_deployment :deployment
```

If I make a PR for this would it be accepted? Am I missing some other obvious workaround?

**Comment by tarebyte** [comment]
> If I make a PR for this would it be accepted?

It would be! It does appear that we are missing that endpoint. Thanks @russellballestrini !

**Comment by russellballestrini** [comment]
I think I'm having trouble triggering VCR to create a new entry in the "cassette".  Here is my PR: https://github.com/octokit/octokit.rb/pull/996
