### ISSUE TITLE
Undefined method `search_commits`?

### ISSUE THREAD

**Issue by vladyio** [octokit/octokit.rb#999]
Maybe I am doing something in a wrong way, but an attempt to call `search_commits` method is causing this error:

```[...] octokit-4.8.0/lib/octokit.rb:53:in `method_missing': undefined method `search_commits' for Octokit:Module (NoMethodError)```

I tried calling it under 2.4.0 and 2.5.1 rubies, both crash with the same error. 

P. S. Also this method is not present at http://octokit.github.io/octokit.rb/Octokit/Client/Search.html

**Comment by tarebyte** [comment]
@vladyio we haven't cut a new release since `search_commits` was added.

Sorry for the confusion!
